/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Oscar Montes
 */
public class Dialog_VerCierre extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog_VerCierre
     */
    JPanel parent;
    public Dialog_VerCierre(JPanel parent) {
            this.parent=parent;
            initComponents();
            this.jFormattedTextField1.selectAll();
            setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextField_totalTarjetaReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalVentaReportado = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField_totalContadoReportado = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextField_gasto = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Tarjeta Bouchers");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 136, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total Contado Reportado");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 138, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Venta Reprotado");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 138, -1));

        jFormattedTextField_totalTarjetaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_totalTarjetaReportado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField_totalTarjetaReportado.setText("0.00");
        jFormattedTextField_totalTarjetaReportado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFormattedTextField_totalTarjetaReportado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField_totalTarjetaReportadoMouseClicked(evt);
            }
        });
        jFormattedTextField_totalTarjetaReportado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField_totalTarjetaReportadoPropertyChange(evt);
            }
        });
        jFormattedTextField_totalTarjetaReportado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_totalTarjetaReportadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_totalTarjetaReportadoKeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField_totalTarjetaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 178, 30));

        jFormattedTextField_totalVentaReportado.setEditable(false);
        jFormattedTextField_totalVentaReportado.setForeground(java.awt.Color.blue);
        jFormattedTextField_totalVentaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_totalVentaReportado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField_totalVentaReportado.setText("0.00");
        jFormattedTextField_totalVentaReportado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(jFormattedTextField_totalVentaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 178, 30));

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Crear Cierre");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 30));

        jFormattedTextField_totalContadoReportado.setEditable(false);
        jFormattedTextField_totalContadoReportado.setForeground(java.awt.Color.blue);
        jFormattedTextField_totalContadoReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_totalContadoReportado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField_totalContadoReportado.setText("0.00");
        jFormattedTextField_totalContadoReportado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFormattedTextField_totalContadoReportado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField_totalContadoReportadoPropertyChange(evt);
            }
        });
        jFormattedTextField_totalContadoReportado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_totalContadoReportadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_totalContadoReportadoKeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField_totalContadoReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 178, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Billetes de C1000");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 88, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Billetes de C2000");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 88, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Billetes de C5000");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 88, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Billetes de C10000");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Billetes de C20000");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Billetes de C50000");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 20));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField1.setText("0.00");
        jFormattedTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField1MouseClicked(evt);
            }
        });
        jFormattedTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField1PropertyChange(evt);
            }
        });
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 46, -1));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField2.setText("0.00");
        jFormattedTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField2MouseClicked(evt);
            }
        });
        jFormattedTextField2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField2PropertyChange(evt);
            }
        });
        jFormattedTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField2KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 46, -1));

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField3.setText("0.00");
        jFormattedTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField3MouseClicked(evt);
            }
        });
        jFormattedTextField3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField3PropertyChange(evt);
            }
        });
        jFormattedTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField3KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 46, -1));

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField4.setText("0.00");
        jFormattedTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField4MouseClicked(evt);
            }
        });
        jFormattedTextField4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField4PropertyChange(evt);
            }
        });
        jFormattedTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField4KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 46, -1));

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField5.setText("0.00");
        jFormattedTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField5MouseClicked(evt);
            }
        });
        jFormattedTextField5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField5PropertyChange(evt);
            }
        });
        jFormattedTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField5KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 46, -1));

        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField6.setText("0.00");
        jFormattedTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField6MouseClicked(evt);
            }
        });
        jFormattedTextField6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField6PropertyChange(evt);
            }
        });
        jFormattedTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField6KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 46, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Monedas de C5");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 86, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Monedas de C10");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 86, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Monedas de C25");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 86, 20));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Monedas de C50");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 86, 20));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Monedas de C100");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Monedas de C500");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, 20));

        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField7.setText("0.00");
        jFormattedTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField7MouseClicked(evt);
            }
        });
        jFormattedTextField7.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField7PropertyChange(evt);
            }
        });
        jFormattedTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField7KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 46, -1));

        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField8.setText("0.00");
        jFormattedTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField8MouseClicked(evt);
            }
        });
        jFormattedTextField8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField8PropertyChange(evt);
            }
        });
        jFormattedTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField8KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 46, -1));

        jFormattedTextField9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField9.setText("0.00");
        jFormattedTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField9MouseClicked(evt);
            }
        });
        jFormattedTextField9.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField9PropertyChange(evt);
            }
        });
        jFormattedTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField9KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 46, -1));

        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField10.setText("0.00");
        jFormattedTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField10MouseClicked(evt);
            }
        });
        jFormattedTextField10.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField10PropertyChange(evt);
            }
        });
        jFormattedTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField10KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 46, -1));

        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField11.setText("0.00");
        jFormattedTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField11MouseClicked(evt);
            }
        });
        jFormattedTextField11.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField11PropertyChange(evt);
            }
        });
        jFormattedTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField11KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 46, -1));

        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jFormattedTextField12.setText("0.00");
        jFormattedTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField12MouseClicked(evt);
            }
        });
        jFormattedTextField12.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField12PropertyChange(evt);
            }
        });
        jFormattedTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField12KeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 46, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Total Gastos");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 138, -1));

        jFormattedTextField_gasto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_gasto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField_gasto.setText("0.00");
        jFormattedTextField_gasto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFormattedTextField_gasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField_gastoMouseClicked(evt);
            }
        });
        jFormattedTextField_gasto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_gastoKeyTyped(evt);
            }
        });
        jPanel3.add(jFormattedTextField_gasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 178, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 20, 280));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Efectivo en caja");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try {
              if (this.jFormattedTextField_totalTarjetaReportado.getText().equals("")) {
                  JOptionPane.showMessageDialog(
                          null,
                          "Porfavor ingrese un monto en total tarjeta reportado",
                          "Alert!", JOptionPane.ERROR_MESSAGE);

                  this.jFormattedTextField_totalTarjetaReportado.requestFocus(true);
                  return;
              }
              if (this.jFormattedTextField_totalContadoReportado.getText().equals("")) {

                  JOptionPane.showMessageDialog(
                          null,
                          "Porfavor ingrese un monto en total contado reportado",
                          "Alert!", JOptionPane.ERROR_MESSAGE);

                  this.jFormattedTextField_totalContadoReportado.requestFocus(true);
                  return;

              }
              BigDecimal totalcont = this.StringtoBigDecimal(this.jFormattedTextField_totalContadoReportado.getText());
              BigDecimal totaltarj = this.StringtoBigDecimal(this.jFormattedTextField_totalTarjetaReportado.getText());
              BigDecimal totalvent = this.StringtoBigDecimal(this.jFormattedTextField_totalVentaReportado.getText());
              BigDecimal gastos = this.StringtoBigDecimal(this.jFormattedTextField_gasto.getText());
              
              Pan_CerrarCaja panelCreaCerrarCaja = new Pan_CerrarCaja(Pan_CerrarCaja.NEW_CALL);
              JF_Facturacion.getInstance().getPanelManager().showPanel(panelCreaCerrarCaja, 800, 471, 0, 0);
              JF_Facturacion.getInstance().setEnableTabs(false);
              
              Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
              int idCierreVigente = AdminBD.obtenerultimoidCierre();
              String fechaInicio = AdminBD.obtenerFechaInicioCierre(idCierreVigente);
              String Cajero = AdminBD.obtenerCajeroCierre(idCierreVigente);
              BigDecimal montoinicio = AdminBD.obtenerMontoInicio(idCierreVigente);
              DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
              Date date = new Date();
              panelCreaCerrarCaja.jLabel_horaCierre.setText(dateFormat.format(date));
              panelCreaCerrarCaja.personalizarTablaCierre(totalcont, totaltarj, totalvent, Cajero, fechaInicio, montoinicio, gastos);



        } catch (Exception e) {
        }
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jFormattedTextField_totalTarjetaReportadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalTarjetaReportadoKeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jFormattedTextField_totalTarjetaReportado.transferFocus();
            this.jFormattedTextField_totalVentaReportado.transferFocus();
        
        }
        if (evt.isControlDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField_totalTarjetaReportadoKeyPressed

    private void jFormattedTextField_totalTarjetaReportadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalTarjetaReportadoKeyTyped
        int tecla= evt.getKeyChar();
        
        if(tecla==KeyEvent.VK_ENTER){
            jButton3.requestFocusInWindow();
        }
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        };
        if (!Character.isDigit(tecla) & !Character.isISOControl(
            evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField_totalTarjetaReportadoKeyTyped

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
         if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton3.doClick();
        
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jFormattedTextField_totalTarjetaReportadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalTarjetaReportadoPropertyChange
        if (evt.getPropertyName().equals("value")) {
            if(evt.getNewValue()!=null){
            String text = evt.getNewValue().toString();
            BigDecimal totaltarj = this.StringtoBigDecimal(text);
            if(evt.getOldValue()!=null){
                String text2 = evt.getOldValue().toString();
                BigDecimal totaltarjold = this.StringtoBigDecimal(text2);
                BigDecimal total = this.StringtoBigDecimal(this.jFormattedTextField_totalVentaReportado.getText());
                this.jFormattedTextField_totalVentaReportado.setValue(total.add(totaltarj.subtract(totaltarjold)));
                return;
            }
            BigDecimal total = this.StringtoBigDecimal(this.jFormattedTextField_totalVentaReportado.getText());
            this.jFormattedTextField_totalVentaReportado.setValue(total.add(totaltarj));
            
            }
            
        }
        
    }//GEN-LAST:event_jFormattedTextField_totalTarjetaReportadoPropertyChange

    private void jFormattedTextField_totalContadoReportadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalContadoReportadoPropertyChange
        if (evt.getPropertyName().equals("value")) {

            if (evt.getNewValue() != null) {
                String text = evt.getNewValue().toString();
                BigDecimal totalcont = this.StringtoBigDecimal(text);
                if (evt.getOldValue() != null) {
                    String text2 = evt.getOldValue().toString();
                    BigDecimal totalcontold = this.StringtoBigDecimal(text2);
                    BigDecimal total = this.StringtoBigDecimal(this.jFormattedTextField_totalVentaReportado.getText());
                    this.jFormattedTextField_totalVentaReportado.setValue(total.add(totalcont.subtract(totalcontold)));
                    return;
                }
                BigDecimal total = this.StringtoBigDecimal(this.jFormattedTextField_totalVentaReportado.getText());
                this.jFormattedTextField_totalVentaReportado.setValue(total.add(totalcont));

            } 
            
        }
        
    }//GEN-LAST:event_jFormattedTextField_totalContadoReportadoPropertyChange

    private void jFormattedTextField_totalContadoReportadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalContadoReportadoKeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jFormattedTextField_totalContadoReportado.transferFocus();
            
        
        }
        if (evt.isControlDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField_totalContadoReportadoKeyPressed

    private void jFormattedTextField_totalContadoReportadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalContadoReportadoKeyTyped
        int tecla= evt.getKeyChar();
      
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField_totalContadoReportadoKeyTyped

    private void jFormattedTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField1PropertyChange
        
        this.agregaListenerMonedasyBilletes(evt, "1000");
    }//GEN-LAST:event_jFormattedTextField1PropertyChange
    private void agregaListenerMonedasyBilletes(PropertyChangeEvent evt, String valor){
        if (evt.getPropertyName().equals("value")) {

            if (evt.getNewValue() != null) {
                String text = evt.getNewValue().toString();
                BigDecimal Billetes1000 = this.StringtoBigDecimal(text);
                BigDecimal mil = new BigDecimal(valor);
                if (evt.getOldValue() != null) {
                    String text2 = evt.getOldValue().toString();
                    BigDecimal billetesold = this.StringtoBigDecimal(text2);
                    BigDecimal totalcontado = this.StringtoBigDecimal(this.jFormattedTextField_totalContadoReportado.getText());
                    this.jFormattedTextField_totalContadoReportado.setValue(totalcontado.add((Billetes1000.multiply(mil)).subtract(billetesold.multiply(mil))));
                    return;
                }
                BigDecimal total = this.StringtoBigDecimal(this.jFormattedTextField_totalContadoReportado.getText());
                this.jFormattedTextField_totalContadoReportado.setValue(total.add(Billetes1000.multiply(mil)));

            } 
            
        }
    }
    
    private void jFormattedTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField2.requestFocusInWindow();
            this.jFormattedTextField2.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField1KeyTyped

    private void jFormattedTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField2KeyTyped
         int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField3.requestFocusInWindow();
            this.jFormattedTextField3.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField2KeyTyped

    private void jFormattedTextField2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField2PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "2000");
    }//GEN-LAST:event_jFormattedTextField2PropertyChange

    private void jFormattedTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField3KeyTyped
         int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField4.requestFocusInWindow();
            this.jFormattedTextField4.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField3KeyTyped

    private void jFormattedTextField3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField3PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "5000");
    }//GEN-LAST:event_jFormattedTextField3PropertyChange

    private void jFormattedTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField4KeyTyped
         int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField5.requestFocusInWindow();
            this.jFormattedTextField5.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField4KeyTyped

    private void jFormattedTextField4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField4PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "10000");
    }//GEN-LAST:event_jFormattedTextField4PropertyChange

    private void jFormattedTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField5KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField6.requestFocusInWindow();
            this.jFormattedTextField6.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField5KeyTyped

    private void jFormattedTextField5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField5PropertyChange
        this.agregaListenerMonedasyBilletes(evt,"20000");
    }//GEN-LAST:event_jFormattedTextField5PropertyChange

    private void jFormattedTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField6KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField7.requestFocusInWindow();
            this.jFormattedTextField7.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField6KeyTyped

    private void jFormattedTextField6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField6PropertyChange
        this.agregaListenerMonedasyBilletes(evt,"50000");
    }//GEN-LAST:event_jFormattedTextField6PropertyChange

    private void jFormattedTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField7KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField8.requestFocusInWindow();
            this.jFormattedTextField8.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField7KeyTyped

    private void jFormattedTextField7PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField7PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "5");
    }//GEN-LAST:event_jFormattedTextField7PropertyChange

    private void jFormattedTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField8KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField9.requestFocusInWindow();
            this.jFormattedTextField9.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField8KeyTyped

    private void jFormattedTextField8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField8PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "10");
    }//GEN-LAST:event_jFormattedTextField8PropertyChange

    private void jFormattedTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField9KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField10.requestFocusInWindow();
            this.jFormattedTextField10.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField9KeyTyped

    private void jFormattedTextField9PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField9PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "25");
    }//GEN-LAST:event_jFormattedTextField9PropertyChange

    private void jFormattedTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField10KeyTyped
         int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField11.requestFocusInWindow();
            this.jFormattedTextField11.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField10KeyTyped

    private void jFormattedTextField10PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField10PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "50");
    }//GEN-LAST:event_jFormattedTextField10PropertyChange

    private void jFormattedTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField11KeyTyped
          int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField12.requestFocusInWindow();
            this.jFormattedTextField12.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField11KeyTyped

    private void jFormattedTextField11PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField11PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "100");
    }//GEN-LAST:event_jFormattedTextField11PropertyChange

    private void jFormattedTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField12KeyTyped
        int tecla= evt.getKeyChar();
       
        if(tecla==KeyEvent.VK_ENTER){
            this.jFormattedTextField_totalTarjetaReportado.requestFocusInWindow();
            this.jFormattedTextField_totalTarjetaReportado.selectAll();
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(
                evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField12KeyTyped

    private void jFormattedTextField12PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField12PropertyChange
        this.agregaListenerMonedasyBilletes(evt, "500");
    }//GEN-LAST:event_jFormattedTextField12PropertyChange

    private void jFormattedTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField1MouseClicked
        this.jFormattedTextField1.selectAll();
    }//GEN-LAST:event_jFormattedTextField1MouseClicked

    private void jFormattedTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField2MouseClicked
        this.jFormattedTextField2.selectAll();
    }//GEN-LAST:event_jFormattedTextField2MouseClicked

    private void jFormattedTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField3MouseClicked
        this.jFormattedTextField3.selectAll();
    }//GEN-LAST:event_jFormattedTextField3MouseClicked

    private void jFormattedTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField4MouseClicked
        this.jFormattedTextField4.selectAll();
    }//GEN-LAST:event_jFormattedTextField4MouseClicked

    private void jFormattedTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField5MouseClicked
        this.jFormattedTextField5.selectAll();
    }//GEN-LAST:event_jFormattedTextField5MouseClicked

    private void jFormattedTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField6MouseClicked
        this.jFormattedTextField6.selectAll();
    }//GEN-LAST:event_jFormattedTextField6MouseClicked

    private void jFormattedTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField7MouseClicked
        this.jFormattedTextField7.selectAll();
    }//GEN-LAST:event_jFormattedTextField7MouseClicked

    private void jFormattedTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField8MouseClicked
        this.jFormattedTextField8.selectAll();
    }//GEN-LAST:event_jFormattedTextField8MouseClicked

    private void jFormattedTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField9MouseClicked
        this.jFormattedTextField9.selectAll();
    }//GEN-LAST:event_jFormattedTextField9MouseClicked

    private void jFormattedTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField10MouseClicked
        this.jFormattedTextField10.selectAll();
    }//GEN-LAST:event_jFormattedTextField10MouseClicked

    private void jFormattedTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField11MouseClicked
        this.jFormattedTextField11.selectAll();
    }//GEN-LAST:event_jFormattedTextField11MouseClicked

    private void jFormattedTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField12MouseClicked
        this.jFormattedTextField12.selectAll();
    }//GEN-LAST:event_jFormattedTextField12MouseClicked

    private void jFormattedTextField_gastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField_gastoMouseClicked
        this.jFormattedTextField_gasto.selectAll();
    }//GEN-LAST:event_jFormattedTextField_gastoMouseClicked

    private void jFormattedTextField_totalTarjetaReportadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField_totalTarjetaReportadoMouseClicked
        this.jFormattedTextField_totalTarjetaReportado.selectAll();
    }//GEN-LAST:event_jFormattedTextField_totalTarjetaReportadoMouseClicked

    private void jFormattedTextField_gastoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_gastoKeyTyped
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            this.jButton3.requestFocusInWindow();
        }
    }//GEN-LAST:event_jFormattedTextField_gastoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    javax.swing.JFormattedTextField jFormattedTextField1;
    javax.swing.JFormattedTextField jFormattedTextField10;
    javax.swing.JFormattedTextField jFormattedTextField11;
    javax.swing.JFormattedTextField jFormattedTextField12;
    javax.swing.JFormattedTextField jFormattedTextField2;
    javax.swing.JFormattedTextField jFormattedTextField3;
    javax.swing.JFormattedTextField jFormattedTextField4;
    javax.swing.JFormattedTextField jFormattedTextField5;
    javax.swing.JFormattedTextField jFormattedTextField6;
    javax.swing.JFormattedTextField jFormattedTextField7;
    javax.swing.JFormattedTextField jFormattedTextField8;
    javax.swing.JFormattedTextField jFormattedTextField9;
    javax.swing.JFormattedTextField jFormattedTextField_gasto;
    javax.swing.JFormattedTextField jFormattedTextField_totalContadoReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalTarjetaReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaReportado;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel15;
    javax.swing.JLabel jLabel16;
    javax.swing.JLabel jLabel17;
    javax.swing.JLabel jLabel18;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel3;
    javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

        
     /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     * @param numero
     * @return 
     */
    private BigDecimal StringtoBigDecimal(String numero){
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;
    
    }
}
