/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

/**
 *
 * @author Joseph
 */
public class JF_Inventario extends javax.swing.JFrame {

    /**
     * Creates new form JF_Inventario
     */
    public JF_Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttInventario = new javax.swing.JLabel();
        bttEntradas = new javax.swing.JLabel();
        bttSalidas = new javax.swing.JLabel();
        bttBodega = new javax.swing.JLabel();
        bttMovimientos = new javax.swing.JLabel();
        bk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/inventarioBttDct.png"))); // NOI18N
        getContentPane().add(bttInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 12, -1, -1));

        bttEntradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/entradasBttDct.png"))); // NOI18N
        getContentPane().add(bttEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 12, -1, -1));

        bttSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/salidasBttDct.png"))); // NOI18N
        getContentPane().add(bttSalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 12, -1, -1));

        bttBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/bodegaBttDct.png"))); // NOI18N
        getContentPane().add(bttBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 12, -1, -1));

        bttMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/movimientosBttDct.png"))); // NOI18N
        getContentPane().add(bttMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 12, -1, -1));

        bk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/panel2.png"))); // NOI18N
        getContentPane().add(bk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bk;
    private javax.swing.JLabel bttBodega;
    private javax.swing.JLabel bttEntradas;
    private javax.swing.JLabel bttInventario;
    private javax.swing.JLabel bttMovimientos;
    private javax.swing.JLabel bttSalidas;
    // End of variables declaration//GEN-END:variables
}
