/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

/**
 *
 * @author Joseph
 */
public class JF_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form JF_Usuario
     */
    public JF_Usuario() {
        initComponents();
        setLocation(StartWindow.getPosX(), StartWindow.getPosY());
        Pan_Clientes clientes = new Pan_Clientes();
        clientes.setLocation(0, 0);
        clientes.setSize(800, 471);
        jLayeredPane1.add(clientes, 0);
        clientes.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        bttAtras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLayeredPane1.setBackground(new java.awt.Color(153, 153, 153));
        jLayeredPane1.setOpaque(true);

        bttAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/atras.png"))); // NOI18N
        bttAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttAtrasMouseClicked(evt);
            }
        });
        jLayeredPane1.add(bttAtras);
        bttAtras.setBounds(726, 471, 79, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel2/panel2.png"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 0, 838, 500);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttAtrasMouseClicked
        StartWindow.getInstance().enableMe();
        this.dispose();
    }//GEN-LAST:event_bttAtrasMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        StartWindow.getInstance().enableMe();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bttAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
