/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import db_managment.Direct_Control_BD;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Oscar Montes
 */
public class JPanel_Facturacion extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Facturacion
     */
    public JPanel_Facturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Facturas = new javax.swing.JPanel();
        jButton_Crear = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Ver = new javax.swing.JButton();
        jButton_Imprimir = new javax.swing.JButton();
        jButton_CierreCaja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Facturacion = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(874, 418));

        jPanel_Facturas.setPreferredSize(new java.awt.Dimension(874, 600));

        jButton_Crear.setText("Crear");
        jButton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearActionPerformed(evt);
            }
        });

        jButton_Modificar.setText("Modificar");

        jButton_Eliminar.setText("Eliminar");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_Ver.setText("Ver");

        jButton_Imprimir.setText("Imprimir");

        jButton_CierreCaja.setText("Cierre Caja");

        jTable_Facturacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_Facturacion);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_FacturasLayout = new javax.swing.GroupLayout(jPanel_Facturas);
        jPanel_Facturas.setLayout(jPanel_FacturasLayout);
        jPanel_FacturasLayout.setHorizontalGroup(
            jPanel_FacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_FacturasLayout.createSequentialGroup()
                .addGroup(jPanel_FacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_FacturasLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_FacturasLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton_Crear)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Modificar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Ver)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Imprimir)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_CierreCaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        jPanel_FacturasLayout.setVerticalGroup(
            jPanel_FacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_FacturasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_FacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Crear)
                    .addComponent(jButton_Modificar)
                    .addComponent(jButton_Eliminar)
                    .addComponent(jButton_Ver)
                    .addComponent(jButton_Imprimir)
                    .addComponent(jButton_CierreCaja)
                    .addComponent(jButton1))
                .addGap(58, 58, 58))
        );

        jTabbedPane1.addTab("Facturacion", jPanel_Facturas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Apartados", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
    }//GEN-END:initComponents

    private void jButton_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearActionPerformed
        VentanaDeInicio mVentana= VentanaDeInicio.getInstance();
        JPanel_CrearFactura panelCreaFact= new JPanel_CrearFactura();
        mVentana.add(panelCreaFact);
        panelCreaFact.setSize(this.getSize());
        panelCreaFact.setLocation(this.getLocation());
        mVentana.remove(this);
        panelCreaFact.setVisible(true);
        mVentana.revalidate();
        mVentana.repaint();
        mVentana.setTitle("Factura");
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        String factura = " Factura " + Integer.toString(AdminBD.ObtenerUltimoidFact() + 1);
        panelCreaFact.jLabel_Fact.setText(factura);
        panelCreaFact.personalizarTablaFactura();
       
        
        
        

    }//GEN-LAST:event_jButton_CrearActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaDeInicio mVentana= VentanaDeInicio.getInstance();
        mVentana.remove(this);
        mVentana.revalidate();
        mVentana.repaint();
        mVentana.setTitle("Joe");
        mVentana.add(mVentana.jPanel_VentanaPrincipal);
        mVentana.jPanel_VentanaPrincipal.setVisible(true);
        
       
    }//GEN-LAST:event_jButton1ActionPerformed
  /**
     * Actualiza la tabla que se ve en facturacion (Obtiene el total vendido
     * por cada factura y solo muestra las ultimas 100 facturas)**/
    public void completarTablaFacturacion() {
        
        //Realiza la consulta para obtener las facturas
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verFacturas();
        String[] columnNames = AdminBD.getColumnNames();
        Object[][] data = AdminBD.getData();
        //Crea la tabla generica para Facturas
        this.jTable_Facturacion.setModel(new Modelo_Facturacion(columnNames,data));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer
                ();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER );
        this.jTable_Facturacion.getColumnModel().getColumn(0).setCellRenderer
                (centerRenderer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton_CierreCaja;
    javax.swing.JButton jButton_Crear;
    javax.swing.JButton jButton_Eliminar;
    javax.swing.JButton jButton_Imprimir;
    javax.swing.JButton jButton_Modificar;
    javax.swing.JButton jButton_Ver;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel_Facturas;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTabbedPane jTabbedPane1;
    javax.swing.JTable jTable_Facturacion;
    // End of variables declaration//GEN-END:variables
}
