/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;


import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author edward
 */
public class JPanel_Inventario extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Inventario
     */
    
    private static JPanel_Inventario mPanelInventario=null;
    boolean ctrlPressed = false;
    boolean cPressed = false;
        
    public JPanel_Inventario() {
        initComponents();
        personalizarTablaInventario();
         
    }
    
    public static JPanel_Inventario getInstance(){
        if(mPanelInventario==null)
        {
            mPanelInventario=new JPanel_Inventario();
        }
        
        return mPanelInventario;
        
        
    }
    
       
    public void personalizarTablaInventario(){
      Direct_Control_BD AdministradorBD= Direct_Control_BD.getInstance();
        AdministradorBD.verInventario();
        String[] columnNames = AdministradorBD.getColumnNames();
        Object[][] data = AdministradorBD.getData();
        //Crea la tabla generica para Facturas
        
        this.jTable_Inventario.setModel(new Modelo_Inventario(columnNames,data));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer
                ();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER );
        this.jTable_Inventario.getColumnModel().getColumn(0).setCellRenderer
                (centerRenderer);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jDialog_CrearProducto = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextField_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Cantidad = new javax.swing.JTextField();
        jButton_CrearProducto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_CategoriaCrearProducto = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_DescripcionCrearProducto = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jTextField_CostoCrearProducto = new javax.swing.JTextField();
        jDialog_EliminarProducto = new javax.swing.JDialog();
        jButton_EliminarProducto = new javax.swing.JButton();
        jTextField_IdProducto = new javax.swing.JTextField();
        jDialog_ModificarProducto = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTextField_CodigoProducto = new javax.swing.JTextField();
        jLabel_Codigo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_nombre1 = new javax.swing.JTextField();
        jLabel_Precio = new javax.swing.JLabel();
        jTextField_Precio1 = new javax.swing.JTextField();
        jTextField_Costo = new javax.swing.JTextField();
        jButton_CrearProducto1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Costo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Categorias = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_CrearCategoria = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField_Descripcion = new javax.swing.JTextArea();
        jDialog_ConfirmacionModificacionProducto = new javax.swing.JDialog();
        jTextField_IdProductoModificar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDialog_CrearCategoria = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField_NombreCategoria = new javax.swing.JTextField();
        jDialog_VerProducto = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTextField_CodigoVerProducto = new javax.swing.JTextField();
        jLabel_Codigo2 = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jTextField_nombreVerProducto = new javax.swing.JTextField();
        jLabel_Precio2 = new javax.swing.JLabel();
        jTextField_PrecioVerProducto = new javax.swing.JTextField();
        jTextField_CostoVerProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel_Costo2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_DescripcionVerProducto = new javax.swing.JTextField();
        jTextField_CategoriaVerProducto = new javax.swing.JTextField();
        jDialog_ConfirmacionVerProducto = new javax.swing.JDialog();
        jTextField_IdProductoModificar1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_InventarioGeneral = new javax.swing.JPanel();
        jButtonRegresarInventario = new javax.swing.JButton();
        jButton_ModificarProducto = new javax.swing.JButton();
        jButton_CrearProductoInventario = new javax.swing.JButton();
        jButton_EliminarProductoInventario = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Inventario = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel_EntradaMercaderia = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_EntradasMercaderia = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton_CrearEntrada = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_codigoKeyTyped(evt);
            }
        });

        jLabel1.setText("Codigo del Producto");

        jLabel2.setText("Nombre del Producto");

        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyTyped(evt);
            }
        });

        jLabel3.setText("Precio del Producto");

        jTextField_Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PrecioKeyTyped(evt);
            }
        });

        jLabel4.setText("Cantidad del Producto");

        jTextField_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CantidadKeyTyped(evt);
            }
        });

        jButton_CrearProducto.setText("Aceptar");
        jButton_CrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearProductoActionPerformed(evt);
            }
        });

        jLabel10.setText("Categoria");

        jComboBox_CategoriaCrearProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_CategoriaCrearProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox_CategoriaCrearProductoFocusGained(evt);
            }
        });
        jComboBox_CategoriaCrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox_CategoriaCrearProductoKeyTyped(evt);
            }
        });

        jLabel11.setText("Descripcion");

        jTextArea_DescripcionCrearProducto.setColumns(20);
        jTextArea_DescripcionCrearProducto.setRows(5);
        jTextArea_DescripcionCrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_DescripcionCrearProductoKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea_DescripcionCrearProducto);

        jLabel12.setText("Costo");

        jTextField_CostoCrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CostoCrearProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CostoCrearProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_CategoriaCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Precio)
                                    .addComponent(jTextField_Cantidad)
                                    .addComponent(jTextField_codigo)
                                    .addComponent(jTextField_nombre))
                                .addGap(75, 75, 75))
                            .addComponent(jTextField_CostoCrearProducto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_CrearProducto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox_CategoriaCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_CostoCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jButton_CrearProducto)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog_CrearProductoLayout = new javax.swing.GroupLayout(jDialog_CrearProducto.getContentPane());
        jDialog_CrearProducto.getContentPane().setLayout(jDialog_CrearProductoLayout);
        jDialog_CrearProductoLayout.setHorizontalGroup(
            jDialog_CrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_CrearProductoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog_CrearProductoLayout.setVerticalGroup(
            jDialog_CrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CrearProductoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton_EliminarProducto.setText("Eliminar");
        jButton_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarProductoActionPerformed(evt);
            }
        });

        jTextField_IdProducto.setText("idProducto");
        jTextField_IdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_EliminarProductoLayout = new javax.swing.GroupLayout(jDialog_EliminarProducto.getContentPane());
        jDialog_EliminarProducto.getContentPane().setLayout(jDialog_EliminarProductoLayout);
        jDialog_EliminarProductoLayout.setHorizontalGroup(
            jDialog_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_EliminarProductoLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jDialog_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_EliminarProductoLayout.createSequentialGroup()
                        .addComponent(jButton_EliminarProducto)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_EliminarProductoLayout.createSequentialGroup()
                        .addComponent(jTextField_IdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        jDialog_EliminarProductoLayout.setVerticalGroup(
            jDialog_EliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_EliminarProductoLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jTextField_IdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton_EliminarProducto)
                .addGap(23, 23, 23))
        );

        jDialog_ModificarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDialog_ModificarProductoKeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jTextField_CodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CodigoProductoKeyTyped(evt);
            }
        });

        jLabel_Codigo.setText("Codigo");

        jLabel_Nombre.setText("Nombre");

        jTextField_nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombre1KeyTyped(evt);
            }
        });

        jLabel_Precio.setText("Precio");

        jTextField_Precio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Precio1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Precio1KeyTyped(evt);
            }
        });

        jTextField_Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CostoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CostoKeyTyped(evt);
            }
        });

        jButton_CrearProducto1.setText("Aceptar");
        jButton_CrearProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearProducto1ActionPerformed(evt);
            }
        });

        jLabel_Costo.setText("Costo");

        jLabel5.setText("Categoria");

        jComboBox_Categorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Categorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox_CategoriasKeyTyped(evt);
            }
        });

        jLabel7.setText("Descripcion");

        jButton_CrearCategoria.setText("Nueva");
        jButton_CrearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearCategoriaActionPerformed(evt);
            }
        });
        jButton_CrearCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton_CrearCategoriaFocusGained(evt);
            }
        });

        jTextField_Descripcion.setColumns(20);
        jTextField_Descripcion.setRows(5);
        jTextField_Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_DescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextField_Descripcion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Nombre)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Costo))
                                .addComponent(jLabel_Codigo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox_Categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_CrearCategoria)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Precio1)
                                    .addComponent(jTextField_Costo)
                                    .addComponent(jTextField_CodigoProducto)
                                    .addComponent(jTextField_nombre1))
                                .addGap(75, 75, 75))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(jLabel6)))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CrearProducto1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Nombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Precio)
                    .addComponent(jTextField_Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Costo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_Categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CrearCategoria))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_CrearProducto1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_ModificarProductoLayout = new javax.swing.GroupLayout(jDialog_ModificarProducto.getContentPane());
        jDialog_ModificarProducto.getContentPane().setLayout(jDialog_ModificarProductoLayout);
        jDialog_ModificarProductoLayout.setHorizontalGroup(
            jDialog_ModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ModificarProductoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog_ModificarProductoLayout.setVerticalGroup(
            jDialog_ModificarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ModificarProductoLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextField_IdProductoModificar.setText("idProducto");
        jTextField_IdProductoModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdProductoModificarKeyPressed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_ConfirmacionModificacionProductoLayout = new javax.swing.GroupLayout(jDialog_ConfirmacionModificacionProducto.getContentPane());
        jDialog_ConfirmacionModificacionProducto.getContentPane().setLayout(jDialog_ConfirmacionModificacionProductoLayout);
        jDialog_ConfirmacionModificacionProductoLayout.setHorizontalGroup(
            jDialog_ConfirmacionModificacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ConfirmacionModificacionProductoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_ConfirmacionModificacionProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_IdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jDialog_ConfirmacionModificacionProductoLayout.setVerticalGroup(
            jDialog_ConfirmacionModificacionProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ConfirmacionModificacionProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_IdProductoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel8.setText("Nombre");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_CrearCategoriaLayout = new javax.swing.GroupLayout(jDialog_CrearCategoria.getContentPane());
        jDialog_CrearCategoria.getContentPane().setLayout(jDialog_CrearCategoriaLayout);
        jDialog_CrearCategoriaLayout.setHorizontalGroup(
            jDialog_CrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CrearCategoriaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jDialog_CrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jTextField_NombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDialog_CrearCategoriaLayout.setVerticalGroup(
            jDialog_CrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CrearCategoriaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jDialog_CrearCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_NombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_Codigo2.setText("Codigo");

        jLabel_Nombre2.setText("Nombre");

        jLabel_Precio2.setText("Precio");

        jLabel_Costo2.setText("Costo");

        jLabel15.setText("Categoria");

        jLabel17.setText("Descripcion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Nombre2)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Precio2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Costo2))
                                .addComponent(jLabel_Codigo2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_PrecioVerProducto)
                            .addComponent(jTextField_CostoVerProducto)
                            .addComponent(jTextField_CodigoVerProducto)
                            .addComponent(jTextField_nombreVerProducto)
                            .addComponent(jTextField_CategoriaVerProducto))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jTextField_DescripcionVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CodigoVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Codigo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nombreVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Nombre2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Precio2)
                    .addComponent(jTextField_PrecioVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CostoVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Costo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_CategoriaVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_DescripcionVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_VerProductoLayout = new javax.swing.GroupLayout(jDialog_VerProducto.getContentPane());
        jDialog_VerProducto.getContentPane().setLayout(jDialog_VerProductoLayout);
        jDialog_VerProductoLayout.setHorizontalGroup(
            jDialog_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_VerProductoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jDialog_VerProductoLayout.setVerticalGroup(
            jDialog_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField_IdProductoModificar1.setText("idProducto");
        jTextField_IdProductoModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdProductoModificar1ActionPerformed(evt);
            }
        });
        jTextField_IdProductoModificar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdProductoModificar1KeyPressed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_ConfirmacionVerProductoLayout = new javax.swing.GroupLayout(jDialog_ConfirmacionVerProducto.getContentPane());
        jDialog_ConfirmacionVerProducto.getContentPane().setLayout(jDialog_ConfirmacionVerProductoLayout);
        jDialog_ConfirmacionVerProductoLayout.setHorizontalGroup(
            jDialog_ConfirmacionVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ConfirmacionVerProductoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_ConfirmacionVerProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_IdProductoModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jDialog_ConfirmacionVerProductoLayout.setVerticalGroup(
            jDialog_ConfirmacionVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ConfirmacionVerProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_IdProductoModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel_InventarioGeneral.setMinimumSize(new java.awt.Dimension(400, 400));

        jButtonRegresarInventario.setText("Regresar");
        jButtonRegresarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarInventarioActionPerformed(evt);
            }
        });

        jButton_ModificarProducto.setText("Modificar");
        jButton_ModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarProductoActionPerformed(evt);
            }
        });

        jButton_CrearProductoInventario.setText("Crear Producto");
        jButton_CrearProductoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearProductoInventarioActionPerformed(evt);
            }
        });

        jButton_EliminarProductoInventario.setText("Eliminar");
        jButton_EliminarProductoInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarProductoInventarioActionPerformed(evt);
            }
        });

        jTable_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTable_Inventario);

        jButton4.setText("Ver Producto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_InventarioGeneralLayout = new javax.swing.GroupLayout(jPanel_InventarioGeneral);
        jPanel_InventarioGeneral.setLayout(jPanel_InventarioGeneralLayout);
        jPanel_InventarioGeneralLayout.setHorizontalGroup(
            jPanel_InventarioGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InventarioGeneralLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_CrearProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_EliminarProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_ModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegresarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel_InventarioGeneralLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_InventarioGeneralLayout.setVerticalGroup(
            jPanel_InventarioGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InventarioGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_InventarioGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CrearProductoInventario)
                    .addComponent(jButton_EliminarProductoInventario)
                    .addComponent(jButton_ModificarProducto)
                    .addComponent(jButtonRegresarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Inventario", jPanel_InventarioGeneral);

        jTable_EntradasMercaderia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_EntradasMercaderia);

        jButton5.setText("Ver Entrada");

        jButton_CrearEntrada.setText("Crear Entrada");
        jButton_CrearEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EntradaMercaderiaLayout = new javax.swing.GroupLayout(jPanel_EntradaMercaderia);
        jPanel_EntradaMercaderia.setLayout(jPanel_EntradaMercaderiaLayout);
        jPanel_EntradaMercaderiaLayout.setHorizontalGroup(
            jPanel_EntradaMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntradaMercaderiaLayout.createSequentialGroup()
                .addGroup(jPanel_EntradaMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_EntradaMercaderiaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_EntradaMercaderiaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton_CrearEntrada)
                        .addGap(27, 27, 27)
                        .addComponent(jButton5)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel_EntradaMercaderiaLayout.setVerticalGroup(
            jPanel_EntradaMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EntradaMercaderiaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel_EntradaMercaderiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton_CrearEntrada))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entrada de Mercaderia", jPanel_EntradaMercaderia);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Salida de Mercaderia", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bodega", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Movimientos", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }//GEN-END:initComponents
//String idProducto, String nombre, int precio,
            //int costo, String fechaCreacion, String estado, String Descripcion,
            //int idCategoria
    private void jButton_CrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearProductoActionPerformed
        VentanaDeInicio miVentana= VentanaDeInicio.getInstance();
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        BigDecimal bd= new BigDecimal("0.0");
        String codigo=this.jTextField_codigo.getText();
      try
      {
          try{
            bd = new BigDecimal(this.jTextField_Precio.getText().toString());
          }
          catch (NumberFormatException exc) 
         { 
             JOptionPane.showOptionDialog(this, "El precio no es valido", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar");
         }
          
      int idCategoria = AdminBD.consultarIdCategoriaXNombre(this.jComboBox_CategoriaCrearProducto.getSelectedItem().toString());
      String Descripcion=this.jTextArea_DescripcionCrearProducto.getText();
      String Nombre=this.jTextField_nombre.getText();
      int Costo= Integer.parseInt(this.jTextField_CostoCrearProducto.getText());
      AdminBD.crearProducto(codigo,Nombre,bd,Costo
                ,dateFormat.format(date),"A",Descripcion
                ,idCategoria);
        AdminBD.insertarEnInventario(this.jTextField_codigo.getText
            (),1,Integer.parseInt(this.jTextField_Cantidad.getText()));
        this.jTextField_Cantidad.setText("");
        this.jTextField_Precio.setText("");
        this.jTextField_codigo.setText("");
        this.jTextField_nombre.setText("");
        this.jDialog_CrearProducto.dispose();
         personalizarTablaInventario();
         
      } 
         catch (NumberFormatException exc) 
         { 
             JOptionPane.showOptionDialog(this, "Faltan datos necesarios", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar");
         }
      
      
        /*
        MyTableModel_FACT model = (MyTableModel_FACT) jTable_Inventario.getModel();
        model.setValueAt(codigo,jTable_Inventario.getSelectedRow(),0);
        jTable_Inventario.revalidate();
        jTable_Inventario.repaint();
        jTable_Inventario.changeSelection( jTable_Inventario.getSelectedRow()+1, jTable_Inventario.getSelectedColumn(), false, false );
        jTable_Inventario.requestFocus();*/
    }//GEN-LAST:event_jButton_CrearProductoActionPerformed

    private void jButton_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarProductoActionPerformed
       Direct_Control_BD mBD= Direct_Control_BD.getInstance();
       
       mBD.consultarProducto(this.jTextField_IdProducto.getText());
       
       Object[][] data = mBD.getData();
       if(data.length==0)
       {
           JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar"); 
       }
       else{
  
       mBD.eliminarProducto(this.jTextField_IdProducto.getText());
       this.jTextField_IdProducto.setText("          ");
       this.jDialog_EliminarProducto.dispose();
       personalizarTablaInventario();
       }
       
       
    }//GEN-LAST:event_jButton_EliminarProductoActionPerformed

    private void jTextField_IdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdProductoActionPerformed

   // String idProducto, String nombre,
     //       int precio, int idCategoria, int costo, String Descripcion
                    
    private void jButton_CrearProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearProducto1ActionPerformed
        
       //Nombre=?,Precio=?, idCategoriaProd=?, Costo=?, Descripcion=?
       try{
       Direct_Control_BD mBD= Direct_Control_BD.getInstance();
       BigDecimal Precio= new BigDecimal( this.jTextField_Precio1.getText());
        int IdCategoria = mBD.consultarIdCategoriaXNombre(this.jComboBox_Categorias.getSelectedItem().toString());
         mBD.modificarProducto(this.jTextField_CodigoProducto.getText(),
                 this.jTextField_nombre1.getText(),Precio
                ,
               IdCategoria
               ,Integer.parseInt(this.jTextField_Costo.getText()),
               this.jTextField_Descripcion.getText());
         
         this.jDialog_ModificarProducto.dispose();
         personalizarTablaInventario();
       }
       catch (NumberFormatException exc) 
         { 
             JOptionPane.showOptionDialog(this, "El precio no es valido", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar");
         }
    }//GEN-LAST:event_jButton_CrearProducto1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jDialog_ConfirmacionModificacionProducto.dispose();

        Direct_Control_BD mBD = Direct_Control_BD.getInstance();
        mBD.consultarProducto(this.jTextField_IdProductoModificar.getText());
        String[] columnNames = mBD.getColumnNames();
        Object[][] data = mBD.getData();
       //Nombre,Precio,Costo,idCategoriaProd,Descripcion

        if (data.length == 0) {
            JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto",
                    JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "}, "Cancelar");
        } else {
            this.jDialog_ModificarProducto.setSize(430, 400);
            JPanel_Inventario mPanel = JPanel_Inventario.getInstance();
            this.jDialog_ModificarProducto.setLocation(mPanel.getLocation());
            this.jDialog_ModificarProducto.setVisible(true);
            this.jTextField_nombre1.setText(data[0][0].toString());
            this.jTextField_Precio1.setText(data[0][1].toString());
            this.jTextField_Costo.setText(data[0][2].toString());
            String NombreCategoria = mBD.consultarNombreCategoriaXid(Integer.parseInt(data[0][3].toString()));
            if (data[0][4] != null) {
                this.jTextField_Descripcion.setText(data[0][4].toString());
            }
            else{
            this.jTextField_Descripcion.setText("No tiene descripcion");}
            this.jTextField_CodigoProducto.setText(data[0][5].toString());
            this.jTextField_CodigoProducto.disable();

            mBD.consultarCategorias();

            columnNames = mBD.getColumnNames();
            data = mBD.getData();

            this.jComboBox_Categorias.removeAllItems();
            for (int i = 0; i < data.length; i++) {
                this.jComboBox_Categorias.addItem(data[i][1]);
            }

            this.jComboBox_Categorias.setSelectedItem(NombreCategoria);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton_CrearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearCategoriaActionPerformed
       this.jDialog_CrearCategoria.setSize(220,120);
       this.jDialog_CrearCategoria.setTitle("Crear Categoria");
       this.jDialog_CrearCategoria.setVisible(true);
       
       
       
    }//GEN-LAST:event_jButton_CrearCategoriaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Direct_Control_BD mBD= Direct_Control_BD.getInstance();
        mBD.insertarCategoria(this.jTextField_NombreCategoria.getText());
        this.jDialog_CrearCategoria.dispose();
        
      
       mBD.consultarCategorias();
       
       String[] columnNames = mBD.getColumnNames();
       Object[][] data = mBD.getData();
       
      
       
       this.jComboBox_Categorias.removeAllItems();
       for(int i=0; i<data.length; i++){
             this.jComboBox_Categorias.addItem(data[i][1]);
       }
       this.jComboBox_Categorias.setSelectedItem(this.jTextField_NombreCategoria.getText());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_IdProductoModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdProductoModificar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        this.jDialog_ConfirmacionVerProducto.dispose();
        
       
       Direct_Control_BD mBD= Direct_Control_BD.getInstance();
       mBD.consultarProducto(this.jTextField_IdProductoModificar1.getText());
       String[] columnNames = mBD.getColumnNames();
       Object[][] data = mBD.getData();
       
       if(data.length==0){
           JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar"); 
       }
       else{
           
       this.jDialog_VerProducto.setSize(430,400);
       JPanel_Inventario mPanel= JPanel_Inventario.getInstance();
       this.jDialog_VerProducto.setLocation(mPanel.getLocation());
       this.jDialog_VerProducto.setVisible(true); 
       
       this.jTextField_nombreVerProducto.setText(data[0][0].toString());
       this.jTextField_nombreVerProducto.disable();
       this.jTextField_PrecioVerProducto.setText(data[0][1].toString());
       this.jTextField_PrecioVerProducto.disable();
       this.jTextField_CostoVerProducto.setText(data[0][2].toString());
       this.jTextField_CostoVerProducto.disable();
       
       String NombreCategoria = mBD.consultarNombreCategoriaXid(Integer.parseInt(data[0][3].toString()));
        if (data[0][4] != null) {
                this.jTextField_DescripcionVerProducto.setText(data[0][4].toString());
            }
        else{this.jTextField_DescripcionVerProducto.setText("No tiene descripcion");}
       
       this.jTextField_DescripcionVerProducto.disable();
       this.jTextField_CodigoVerProducto.setText(data[0][5].toString());
       this.jTextField_CodigoVerProducto.disable();
       
       this.jTextField_CategoriaVerProducto.setText(NombreCategoria);
       this.jTextField_CategoriaVerProducto.disable();
       
       
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PrecioKeyTyped
        int tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
      int limite=13;
      if (jTextField_Precio.getText().length()== limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_Precio.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_PrecioKeyTyped

    private void jTextField_CostoCrearProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoCrearProductoKeyTyped
        int tecla= evt.getKeyChar();
        
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
        
        int limite=9;
      if (jTextField_CostoCrearProducto.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_CostoCrearProducto.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_CostoCrearProductoKeyTyped

    private void jTextField_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CantidadKeyTyped
        int tecla= evt.getKeyChar();
        
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
        
        int limite=9;
      if (jTextField_Cantidad.getText().length()== limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_Cantidad.transferFocus();
            
        
        }
       
        
    }//GEN-LAST:event_jTextField_CantidadKeyTyped

    private void jTextField_PrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PrecioKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_PrecioKeyPressed

    private void jTextField_CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CantidadKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_CantidadKeyPressed

    private void jTextField_CostoCrearProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoCrearProductoKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_CostoCrearProductoKeyPressed

    private void jTextField_Precio1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Precio1KeyPressed
       if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_Precio1KeyPressed

    private void jDialog_ModificarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDialog_ModificarProductoKeyPressed
        
    }//GEN-LAST:event_jDialog_ModificarProductoKeyPressed

    private void jTextField_CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoKeyTyped
        int tecla= evt.getKeyChar();
        
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
        int limite=9;
      if (jTextField_Costo.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_Costo.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_CostoKeyTyped

    private void jTextField_Precio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Precio1KeyTyped
        int tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
        int limite=9;
      if (jTextField_Precio1.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_Precio1.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_Precio1KeyTyped

    private void jTextField_CostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_CostoKeyPressed

    private void jTextField_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_codigoKeyTyped
       int limite=30;
           if (jTextField_codigo.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
     
               
           }
       if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_codigo.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_codigoKeyTyped

    private void jTextField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyTyped
        int limite=30;
           if (jTextField_nombre.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
               
           }
           if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_nombre.transferFocus();
            
        
        }
           
    }//GEN-LAST:event_jTextField_nombreKeyTyped

    private void jTextArea_DescripcionCrearProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_DescripcionCrearProductoKeyTyped
        int limite=30;
        if (jTextArea_DescripcionCrearProducto.getText().length()>=limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextArea_DescripcionCrearProducto.transferFocus();
            
        
        }
      
    }//GEN-LAST:event_jTextArea_DescripcionCrearProductoKeyTyped

    private void jTextField_CodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CodigoProductoKeyTyped
       int limite=30;
        
      if (jTextField_CodigoProducto.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_CodigoProducto.transferFocus();
            
        
        }
      
    }//GEN-LAST:event_jTextField_CodigoProductoKeyTyped

    private void jTextField_nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombre1KeyTyped
        int limite=30;
      if (jTextField_nombre1.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_nombre1.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_nombre1KeyTyped

    private void jTextField_DescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescripcionKeyTyped
        int limite=30;
      if (jTextField_Descripcion.getText().length()>= limite)
           {
     evt.consume();
     Toolkit.getDefaultToolkit().beep();
           }
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_Descripcion.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_DescripcionKeyTyped

    private void jTextField_DescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescripcionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DescripcionKeyPressed

    private void jComboBox_CategoriaCrearProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_CategoriaCrearProductoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_CategoriaCrearProductoFocusGained

    private void jComboBox_CategoriaCrearProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_CategoriaCrearProductoKeyTyped
       if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jComboBox_CategoriaCrearProducto.transferFocus();
            
        
        }
    }//GEN-LAST:event_jComboBox_CategoriaCrearProductoKeyTyped

    private void jComboBox_CategoriasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_CategoriasKeyTyped
        if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jComboBox_Categorias.transferFocus();
            
        
        }
    }//GEN-LAST:event_jComboBox_CategoriasKeyTyped

    private void jButton_CrearCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton_CrearCategoriaFocusGained
     
            this.jButton_CrearCategoria.transferFocus();
            
        
        
    }//GEN-LAST:event_jButton_CrearCategoriaFocusGained

    private void jTextField_IdProductoModificar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jTextField_IdProductoModificar1.transferFocus();
        }
    }//GEN-LAST:event_jTextField_IdProductoModificar1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton3.doClick();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField_IdProductoModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificarKeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jTextField_IdProductoModificar.transferFocus();
        }
    }//GEN-LAST:event_jTextField_IdProductoModificarKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton_CrearEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearEntradaActionPerformed
        VentanaDeInicio mVentana= VentanaDeInicio.getInstance();
        JPanel_CrearEntradaSalidaMercaderia panelCreaFact= new JPanel_CrearEntradaSalidaMercaderia();
        mVentana.add(panelCreaFact);
        panelCreaFact.setSize(this.getSize());
        panelCreaFact.setLocation(this.getLocation());
        mVentana.remove(this);
        panelCreaFact.setVisible(true);
        mVentana.revalidate();
        mVentana.repaint();
        mVentana.setTitle("Entrada de Mercaderia");
        //Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        //String factura = Integer.toString(AdminBD.ObtenerUltimoidFact() + 1);
        panelCreaFact.jLabel_NumerodeFact.setText("Num Doc");
        panelCreaFact.personalizarTablaMovimiento();
        panelCreaFact.agregarListenerRenders();

    }//GEN-LAST:event_jButton_CrearEntradaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Modelo_Inventario model = (Modelo_Inventario) this.jTable_Inventario.getModel();
        int row = this.jTable_Inventario.getSelectedRow();
        if(row>0){
            String idProducto = model.getValueAt(row, 0).toString();
            this.jDialog_ConfirmacionVerProducto.setSize(200, 100);
            JPanel_Inventario mPanel = JPanel_Inventario.getInstance();
            this.jDialog_ConfirmacionVerProducto.setLocation(mPanel.getLocation());
            this.jTextField_IdProductoModificar1.setText(idProducto);
            this.jDialog_ConfirmacionVerProducto.setVisible(true);}
        else{
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton_EliminarProductoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarProductoInventarioActionPerformed
        this.jDialog_EliminarProducto.setSize(200,200);
        JPanel_Inventario mPanel= JPanel_Inventario.getInstance();
        this.jDialog_EliminarProducto.setLocation(mPanel.getLocation());
        this.jDialog_EliminarProducto.setVisible(true);

    }//GEN-LAST:event_jButton_EliminarProductoInventarioActionPerformed

    private void jButton_CrearProductoInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearProductoInventarioActionPerformed
        this.jDialog_CrearProducto.setSize(510,500);
        this.jDialog_CrearProducto.setVisible(true);

        Direct_Control_BD mBD= Direct_Control_BD.getInstance();
        mBD.consultarCategorias();
        String[] columnNames = mBD.getColumnNames();
        Object[][] data = mBD.getData();

        columnNames = mBD.getColumnNames();
        data = mBD.getData();

        this.jComboBox_CategoriaCrearProducto.removeAllItems();
        for(int i=0; i<data.length; i++){
            this.jComboBox_CategoriaCrearProducto.addItem(data[i][1]);
        }

        this.jComboBox_CategoriaCrearProducto.setSelectedItem("Sin Categoria");

    }//GEN-LAST:event_jButton_CrearProductoInventarioActionPerformed

    private void jButton_ModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarProductoActionPerformed
        int row = this.jTable_Inventario.getSelectedRow();

        if (row >= 0) {
            Modelo_Inventario model = (Modelo_Inventario) this.jTable_Inventario.getModel();
            String idProducto = model.getValueAt(row, 0).toString();
            this.jDialog_ConfirmacionModificacionProducto.setSize(200, 100);
            JPanel_Inventario mPanel = JPanel_Inventario.getInstance();
            this.jDialog_ConfirmacionModificacionProducto.setLocation(mPanel.getLocation());
            this.jTextField_IdProductoModificar.setText(idProducto);
            this.jDialog_ConfirmacionModificacionProducto.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_ModificarProductoActionPerformed

    private void jButtonRegresarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarInventarioActionPerformed
        VentanaDeInicio mVentana= VentanaDeInicio.getInstance();
        mVentana.remove(this);
        mVentana.revalidate();
        mVentana.repaint();
        mVentana.setTitle("Joe ");
        mVentana.add(mVentana.jPanel_VentanaPrincipal);
        mVentana.jPanel_VentanaPrincipal.setVisible(true);
        mVentana.jPanel_VentanaPrincipal.setSize(this.getSize());
        mVentana.jPanel_VentanaPrincipal.setLocation(this.getLocation());

    }//GEN-LAST:event_jButtonRegresarInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonRegresarInventario;
    private javax.swing.JButton jButton_CrearCategoria;
    private javax.swing.JButton jButton_CrearEntrada;
    private javax.swing.JButton jButton_CrearProducto;
    private javax.swing.JButton jButton_CrearProducto1;
    private javax.swing.JButton jButton_CrearProductoInventario;
    private javax.swing.JButton jButton_EliminarProducto;
    private javax.swing.JButton jButton_EliminarProductoInventario;
    private javax.swing.JButton jButton_ModificarProducto;
    private javax.swing.JComboBox jComboBox_CategoriaCrearProducto;
    private javax.swing.JComboBox jComboBox_Categorias;
    private javax.swing.JDialog jDialog_ConfirmacionModificacionProducto;
    private javax.swing.JDialog jDialog_ConfirmacionVerProducto;
    private javax.swing.JDialog jDialog_CrearCategoria;
    private javax.swing.JDialog jDialog_CrearProducto;
    private javax.swing.JDialog jDialog_EliminarProducto;
    private javax.swing.JDialog jDialog_ModificarProducto;
    private javax.swing.JDialog jDialog_VerProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Codigo;
    private javax.swing.JLabel jLabel_Codigo2;
    private javax.swing.JLabel jLabel_Costo;
    private javax.swing.JLabel jLabel_Costo2;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Precio;
    private javax.swing.JLabel jLabel_Precio2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_EntradaMercaderia;
    private javax.swing.JPanel jPanel_InventarioGeneral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_EntradasMercaderia;
    private javax.swing.JTable jTable_Inventario;
    private javax.swing.JTextArea jTextArea_DescripcionCrearProducto;
    private javax.swing.JTextField jTextField_Cantidad;
    private javax.swing.JTextField jTextField_CategoriaVerProducto;
    private javax.swing.JTextField jTextField_CodigoProducto;
    private javax.swing.JTextField jTextField_CodigoVerProducto;
    private javax.swing.JTextField jTextField_Costo;
    private javax.swing.JTextField jTextField_CostoCrearProducto;
    private javax.swing.JTextField jTextField_CostoVerProducto;
    private javax.swing.JTextArea jTextField_Descripcion;
    private javax.swing.JTextField jTextField_DescripcionVerProducto;
    private javax.swing.JTextField jTextField_IdProducto;
    private javax.swing.JTextField jTextField_IdProductoModificar;
    private javax.swing.JTextField jTextField_IdProductoModificar1;
    private javax.swing.JTextField jTextField_NombreCategoria;
    private javax.swing.JTextField jTextField_Precio;
    private javax.swing.JTextField jTextField_Precio1;
    private javax.swing.JTextField jTextField_PrecioVerProducto;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_nombre1;
    private javax.swing.JTextField jTextField_nombreVerProducto;
    // End of variables declaration//GEN-END:variables
}
