/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import db_managment.Direct_Control_BD;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Oscar Montes
 */
public class JPanel_VerCierresCaja extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_VerCierresCaja
     */
    public JPanel_VerCierresCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Cierres = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable_Cierres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Cierres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CierresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Cierres);

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1)
                        .addGap(160, 160, 160)
                        .addComponent(jButton2)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaDeInicio miVentana = VentanaDeInicio.getInstance();
        JPanel_Facturacion panelFact = new JPanel_Facturacion();
        panelFact.setSize(this.getSize());
        panelFact.setLocation(this.getLocation());
        miVentana.remove(this);
        miVentana.add(panelFact);
        miVentana.setTitle("Facturacion");
        panelFact.setVisible(true);
        panelFact.completarTablaFacturacion();
        panelFact.completarTablaApartados();
        panelFact.completarTablaCreditos();
        panelFact.completarTablaDevoluciones();
        miVentana.revalidate();
        miVentana.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     * @param numero
     * @return 
     */
    private BigDecimal StringtoBigDecimal(String numero){
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;
    
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              
         this.verCierre();
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_CierresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CierresMouseClicked
        if (evt.getClickCount() == 2){
        this.verCierre();}
    }//GEN-LAST:event_jTable_CierresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTable jTable_Cierres;
    // End of variables declaration//GEN-END:variables
    public void completarTablaVerCierres() {
        //Realiza la consulta para obtener las facturas
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierres();
        String[] columnNames = AdminBD.getColumnNames();
        Object[][] data = AdminBD.getData();
        //Crea la tabla generica para Facturas
        this.jTable_Cierres.setModel(new Modelo_VerCierres(columnNames, data));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        this.jTable_Cierres.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    }

    private void verCierre() {
        int row = this.jTable_Cierres.getSelectedRow();
        if (row >= 0) {
            Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
            Modelo_VerCierres model = (Modelo_VerCierres) this.jTable_Cierres.getModel();
            int idCierre = Integer.parseInt(model.getValueAt(row, 0).toString());
            AdminBD.obtenerInfoCierre(idCierre);
            Object[][] InfoCierre = AdminBD.getData();
            BigDecimal totalcont = this.StringtoBigDecimal(InfoCierre[0][0].toString());
            BigDecimal totaltarj = this.StringtoBigDecimal(InfoCierre[0][1].toString());
            BigDecimal totalvent = this.StringtoBigDecimal(InfoCierre[0][2].toString());
            String fechaFinal = InfoCierre[0][3].toString();
            VentanaDeInicio mVentana = VentanaDeInicio.getInstance();
            JPanel_CerrarCaja panelCreaCerrarCaja = new JPanel_CerrarCaja();
            mVentana.add(panelCreaCerrarCaja);
            panelCreaCerrarCaja.setSize(this.getSize());
            panelCreaCerrarCaja.setLocation(this.getLocation());
            mVentana.remove(this);
            panelCreaCerrarCaja.setVisible(true);
            mVentana.revalidate();
            mVentana.repaint();
            mVentana.setTitle("Cierre De Caja");
            String fechaInicio = AdminBD.obtenerFechaInicioCierre(idCierre);
            String Cajero = AdminBD.obtenerCajeroCierre(idCierre);
            BigDecimal montoinicio = AdminBD.obtenerMontoInicio(idCierre);
            panelCreaCerrarCaja.jLabel_horaCierre.setText(fechaFinal);
            panelCreaCerrarCaja.personalizarTablaCierre(totalcont, totaltarj, totalvent.add(montoinicio), Cajero, fechaInicio, montoinicio);
            panelCreaCerrarCaja.jButton_GuardarCierre.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "No se selecciono ningun cierre",
                    "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }

}
