/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Montes
 */
public class JPanel_CrearFactura extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public JPanel_CrearFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jDialog_CrearProducto = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextField_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_CrearProducto = new javax.swing.JButton();
        jButton_CancelarCrearProducto = new javax.swing.JButton();
        jFormattedTextField_precioProducto = new javax.swing.JFormattedTextField();
        jFormattedTextField_cantidadProducto = new javax.swing.JFormattedTextField();
        jDialog_VerProducto = new javax.swing.JDialog();
        jLayeredPane_VerProducto = new javax.swing.JLayeredPane();
        jLabel_Producto = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Cantidad = new javax.swing.JLabel();
        jLabel_PrecioUnitario = new javax.swing.JLabel();
        jLabel_datoFact = new javax.swing.JLabel();
        jLabel_datoNomb = new javax.swing.JLabel();
        jLabel_datoCant = new javax.swing.JLabel();
        jLabel_datoPrecio = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel_Descripcion = new javax.swing.JLabel();
        jDialog_BuscarProductoPorCod = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton_BusqueProducto = new javax.swing.JButton();
        jButton_CancelaBusquedaProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_busqueProducto = new javax.swing.JTextField();
        jLabel_CodNoEncontrado = new javax.swing.JLabel();
        jButton_CreaProducto = new javax.swing.JButton();
        jButton_VerProducto = new javax.swing.JButton();
        jButton_EliminaFila = new javax.swing.JButton();
        jButton_Descuento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Factura = new javax.swing.JTable();
        jTextField_Total = new javax.swing.JTextField();
        jButton_RegresarFact = new javax.swing.JButton();
        jLabel_Fact = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_codigoKeyPressed(evt);
            }
        });

        jLabel1.setText("Codigo del Producto");

        jLabel2.setText("Nombre del Producto");

        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyPressed(evt);
            }
        });

        jLabel3.setText("Precio del Producto");

        jLabel4.setText("Cantidad del Producto");

        jButton_CrearProducto.setText("Aceptar");
        jButton_CrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearProductoActionPerformed(evt);
            }
        });
        jButton_CrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CrearProductoKeyPressed(evt);
            }
        });

        jButton_CancelarCrearProducto.setText("Cancelar");
        jButton_CancelarCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarCrearProductoActionPerformed(evt);
            }
        });

        jFormattedTextField_precioProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        jFormattedTextField_precioProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_precioProductoFocusGained(evt);
            }
        });
        jFormattedTextField_precioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_precioProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_precioProductoKeyTyped(evt);
            }
        });

        jFormattedTextField_cantidadProducto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_cantidadProducto.setText("0");
        jFormattedTextField_cantidadProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextField_cantidadProductoFocusGained(evt);
            }
        });
        jFormattedTextField_cantidadProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_cantidadProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_cantidadProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_CrearProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_CancelarCrearProducto)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextField_precioProducto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField_cantidadProducto))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField_precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField_cantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CrearProducto)
                    .addComponent(jButton_CancelarCrearProducto))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_CrearProductoLayout = new javax.swing.GroupLayout(jDialog_CrearProducto.getContentPane());
        jDialog_CrearProducto.getContentPane().setLayout(jDialog_CrearProductoLayout);
        jDialog_CrearProductoLayout.setHorizontalGroup(
            jDialog_CrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog_CrearProductoLayout.setVerticalGroup(
            jDialog_CrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialog_VerProducto.setMinimumSize(new java.awt.Dimension(483, 310));
        jDialog_VerProducto.setModal(true);

        jLayeredPane_VerProducto.setBackground(java.awt.Color.white);
        jLayeredPane_VerProducto.setMaximumSize(new java.awt.Dimension(473, 303));
        jLayeredPane_VerProducto.setMinimumSize(new java.awt.Dimension(473, 303));

        jLabel_Producto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel_Producto.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_Producto.setText("Producto");

        jLabel_Nombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_Nombre.setText("Nombre");

        jLabel_Cantidad.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_Cantidad.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_Cantidad.setText("Cantidad");

        jLabel_PrecioUnitario.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_PrecioUnitario.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_PrecioUnitario.setText("Precio Unitario");

        jLabel_datoFact.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_datoFact.setForeground(new java.awt.Color(0, 51, 51));

        jLabel_datoNomb.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_datoNomb.setForeground(new java.awt.Color(0, 51, 51));

        jLabel_datoCant.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_datoCant.setForeground(new java.awt.Color(0, 51, 51));

        jLabel_datoPrecio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_datoPrecio.setForeground(new java.awt.Color(0, 51, 51));

        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel_Descripcion.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel_Descripcion.setForeground(new java.awt.Color(0, 51, 51));
        jLabel_Descripcion.setText("Descripcion");

        javax.swing.GroupLayout jLayeredPane_VerProductoLayout = new javax.swing.GroupLayout(jLayeredPane_VerProducto);
        jLayeredPane_VerProducto.setLayout(jLayeredPane_VerProductoLayout);
        jLayeredPane_VerProductoLayout.setHorizontalGroup(
            jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_datoCant, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane_VerProductoLayout.createSequentialGroup()
                        .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_datoNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                .addGroup(jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel_Producto))
                    .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_datoFact, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                        .addComponent(jLabel_PrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_datoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_VerProductoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jLayeredPane_VerProductoLayout.setVerticalGroup(
            jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_VerProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                        .addComponent(jLabel_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane_VerProductoLayout.createSequentialGroup()
                                .addComponent(jLabel_datoFact, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel_datoNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jLayeredPane_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_datoCant, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_PrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_datoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jLayeredPane_VerProducto.setLayer(jLabel_Producto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_Nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_Cantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_PrecioUnitario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_datoFact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_datoNomb, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_datoCant, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_datoPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_VerProducto.setLayer(jLabel_Descripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDialog_VerProductoLayout = new javax.swing.GroupLayout(jDialog_VerProducto.getContentPane());
        jDialog_VerProducto.getContentPane().setLayout(jDialog_VerProductoLayout);
        jDialog_VerProductoLayout.setHorizontalGroup(
            jDialog_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane_VerProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog_VerProductoLayout.setVerticalGroup(
            jDialog_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane_VerProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButton_BusqueProducto.setText("Aceptar");
        jButton_BusqueProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BusqueProductoActionPerformed(evt);
            }
        });
        jButton_BusqueProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_BusqueProductoKeyPressed(evt);
            }
        });

        jButton_CancelaBusquedaProducto.setText("Cancelar");
        jButton_CancelaBusquedaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelaBusquedaProductoActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese el Cod");

        jTextField_busqueProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_busqueProductoActionPerformed(evt);
            }
        });
        jTextField_busqueProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_busqueProductoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_BusqueProducto)
                        .addGap(42, 42, 42)
                        .addComponent(jButton_CancelaBusquedaProducto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_CodNoEncontrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_busqueProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_busqueProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_CodNoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_BusqueProducto)
                    .addComponent(jButton_CancelaBusquedaProducto))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jDialog_BuscarProductoPorCodLayout = new javax.swing.GroupLayout(jDialog_BuscarProductoPorCod.getContentPane());
        jDialog_BuscarProductoPorCod.getContentPane().setLayout(jDialog_BuscarProductoPorCodLayout);
        jDialog_BuscarProductoPorCodLayout.setHorizontalGroup(
            jDialog_BuscarProductoPorCodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog_BuscarProductoPorCodLayout.setVerticalGroup(
            jDialog_BuscarProductoPorCodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton_CreaProducto.setText("Crear Producto");
        jButton_CreaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreaProductoActionPerformed(evt);
            }
        });

        jButton_VerProducto.setText("Ver Producto");
        jButton_VerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerProductoActionPerformed(evt);
            }
        });

        jButton_EliminaFila.setText("Eliminar Fila");
        jButton_EliminaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminaFilaActionPerformed(evt);
            }
        });

        jButton_Descuento.setText("Descuento");
        jButton_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DescuentoActionPerformed(evt);
            }
        });

        jTable_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Factura.setCellSelectionEnabled(true);
        jTable_Factura.setFillsViewportHeight(true);
        jTable_Factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable_FacturaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Factura);

        jTextField_Total.setForeground(new java.awt.Color(204, 0, 51));
        jTextField_Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Total.setText("0");
        jTextField_Total.setToolTipText("");
        jTextField_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TotalActionPerformed(evt);
            }
        });

        jButton_RegresarFact.setText("Regresar");
        jButton_RegresarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarFactActionPerformed(evt);
            }
        });

        jLabel_Fact.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel_Fact.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_CreaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_VerProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_EliminaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Descuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jButton_RegresarFact))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton_CreaProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_VerProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_EliminaFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Descuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_RegresarFact)))
                .addGap(28, 28, 28))
        );
    }//GEN-END:initComponents

    private void jButton_CreaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreaProductoActionPerformed
        //En caso de que quiera crear un producto mientras se este editando
        if (jTable_Factura.isEditing()) {
            jTable_Factura.getCellEditor().cancelCellEditing();
            this.jDialog_CrearProducto.setSize(500,300);
            this.jDialog_CrearProducto.setVisible(true);
            return;
        }
        //Llama a la ventana para crear el producto
        this.jDialog_CrearProducto.setSize(500,300);
        this.jDialog_CrearProducto.setVisible(true);
    }//GEN-LAST:event_jButton_CreaProductoActionPerformed
    private void verProducto(String idProducto){
            Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
            String articulo = AdminBD.verNombreProductoPorCodigo(idProducto);
            BigDecimal PrecioUnitario = AdminBD.verPrecio(idProducto);
            int cantidad= AdminBD.verCantidad(idProducto);
            jLabel_datoCant.setText(Integer.toString(cantidad));
            jLabel_datoFact.setText(jLabel_Fact.getText());
            jLabel_datoNomb.setText(articulo);
            jLabel_datoPrecio.setText(PrecioUnitario.toString());
            String detalle= AdminBD.verDetalle(idProducto);
            if (detalle==null) {
                jLabel_Descripcion.setText("Descripcion  " + "Este producto no tiene ningun detalle");
                jDialog_VerProducto.setVisible(true);
                return;
            }
            jLabel_Descripcion.setText("Descripcion  " + detalle);
            jDialog_VerProducto.setVisible(true);
       
        }
    
    
    private void jButton_VerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerProductoActionPerformed
        MyTableModel_FACT model = (MyTableModel_FACT) jTable_Factura.getModel();
        int row = jTable_Factura.getSelectedRow();
        String idProducto = model.getValueAt(row, 0).toString();//obtiene el id del 
        //producto seleccionado para VerProducto
        if (!"".equals(idProducto)) {//verifica que se quiere ver un producto
            this.verProducto(idProducto);
        }
        else{
            jDialog_BuscarProductoPorCod.setSize(295,243);
            jDialog_BuscarProductoPorCod.setVisible(true);
        }
    }//GEN-LAST:event_jButton_VerProductoActionPerformed

    private void jButton_EliminaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminaFilaActionPerformed
        MyTableModel_FACT model = (MyTableModel_FACT) jTable_Factura.getModel();
        int row = jTable_Factura.getSelectedRow();
        ///Si se esta escribiendo en la celda para el editor y luego elimina la
        // fila
        if (jTable_Factura.isEditing()) {
            jTable_Factura.getCellEditor().cancelCellEditing();
            model.removeRow(row);
            jTable_Factura.revalidate();
            jTable_Factura.repaint();
            jTable_Factura.requestFocus();
            return;
        }
        String subTotal = model.getValueAt(row, 4).toString();
        if (subTotal != "") {
            //Elimina un producto ya ingresado y actualiza el total
            int subtotal = Integer.parseInt(subTotal);
            model.removeRow(row);
            int total = Integer.parseInt(this.jTextField_Total.getText());
            this.jTextField_Total.setText(Integer.toString(total - subtotal));
            jTable_Factura.revalidate();
            jTable_Factura.repaint();
            jTable_Factura.requestFocus();
        } else { //Si es vacio elimina la fila normalmente
            model.removeRow(row);
            jTable_Factura.revalidate();
            jTable_Factura.repaint();
            jTable_Factura.requestFocus();

        }
    }//GEN-LAST:event_jButton_EliminaFilaActionPerformed

    private void jButton_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DescuentoActionPerformed

    private void jTable_FacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_FacturaKeyPressed
        if(evt.getKeyCode()==120){
            this.jButton_EliminaFila.doClick();
        }
    }//GEN-LAST:event_jTable_FacturaKeyPressed

    private void jTextField_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TotalActionPerformed

    private void jButton_RegresarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarFactActionPerformed
        VentanaDeInicio miVentana= VentanaDeInicio.getInstance();
        JPanel_Facturacion panelFact= new JPanel_Facturacion();
        panelFact.setSize(this.getSize());
        panelFact.setLocation(this.getLocation());
        miVentana.remove(this);
        miVentana.add(panelFact);
        miVentana.setTitle("Facturacion");
        panelFact.setVisible(true);
        panelFact.completarTablaFacturacion();
        miVentana.revalidate();
        miVentana.repaint();

    }//GEN-LAST:event_jButton_RegresarFactActionPerformed
    private void CrearProducto(){
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        String codigo = this.jTextField_codigo.getText();
        boolean existeProducto = AdminBD.verSiExisteCod(codigo);
        if (!existeProducto) {
            BigDecimal bd = new BigDecimal(this.jFormattedTextField_precioProducto.getValue().toString());
            System.out.println(bd.toString());
            AdminBD.crearProducto(codigo, this.jTextField_nombre.getText(),bd,0, dateFormat.format(date), "A", null, 1);
            AdminBD.insertarEnInventario(this.jTextField_codigo.getText(), 1, Integer.parseInt(this.jFormattedTextField_cantidadProducto.getValue().toString()));
            this.jFormattedTextField_cantidadProducto.setText("");
            this.jFormattedTextField_precioProducto.setText("");
            this.jTextField_codigo.setText("");
            this.jTextField_nombre.setText("");
            this.jDialog_CrearProducto.dispose();
            MyTableModel_FACT model = (MyTableModel_FACT) jTable_Factura.getModel();
            model.setValueAt(codigo, jTable_Factura.getSelectedRow(), 0);
            jTable_Factura.revalidate();
            jTable_Factura.repaint();
            jTable_Factura.changeSelection(jTable_Factura.getSelectedRow() + 1, jTable_Factura.getSelectedColumn(), false, false);
            jTable_Factura.requestFocus();
        }

        else {
            JOptionPane.showMessageDialog(
                          null,
                          "ESTE Cod ya existe en el inventario",
                          "Alert!", JOptionPane.ERROR_MESSAGE);
            this.jTextField_codigo.setText("");
            this.jButton_CrearProducto.transferFocus();
            this.jButton_CancelarCrearProducto.transferFocus();
        }
    }

    private void jButton_CrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearProductoActionPerformed
       this.CrearProducto();

    }//GEN-LAST:event_jButton_CrearProductoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTable_Factura.changeSelection( jTable_Factura.getSelectedRow(), jTable_Factura.getSelectedColumn(), false, false );
        jTable_Factura.requestFocus();
        this.jDialog_VerProducto.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_CancelarCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarCrearProductoActionPerformed
        this.jDialog_CrearProducto.dispose();
        this.jFormattedTextField_precioProducto.setText("0.00");
        //Para que el usuario se mantenga en la tabla
        jTable_Factura.changeSelection( jTable_Factura.getSelectedRow(), jTable_Factura.getSelectedColumn(), false, false );
        jTable_Factura.requestFocus();
    }//GEN-LAST:event_jButton_CancelarCrearProductoActionPerformed

    private void jTextField_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_codigoKeyPressed
        //Se presiono enter en el textfield de codigo por lo tanto tiene que
        // hacer que se haga focus el que sigue
        if(evt.getKeyCode()==10){
            this.jTextField_codigo.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_codigoKeyPressed

    private void jTextField_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyPressed
        if(evt.getKeyCode()==10){
            this.jTextField_nombre.transferFocus();
        }
    }//GEN-LAST:event_jTextField_nombreKeyPressed

    private void jButton_CrearProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CrearProductoKeyPressed
        if(evt.getKeyCode()==10){
            this.CrearProducto();
        }
    }//GEN-LAST:event_jButton_CrearProductoKeyPressed
    private void buscarProducto(){
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        String idProducto = this.jTextField_busqueProducto.getText();
        boolean existeProducto=AdminBD.verSiExisteCod(idProducto);
        
        if(existeProducto){
            this.jDialog_BuscarProductoPorCod.dispose();
            this.verProducto(idProducto);
            this.jTextField_busqueProducto.setText("");
            this.jLabel_CodNoEncontrado.setText("");
            return;
        
        }
        this.jLabel_CodNoEncontrado.setText("Cod. No Existe");
        this.jTextField_busqueProducto.setText("");
        this.jButton_BusqueProducto.transferFocus();
        this.jButton_CancelaBusquedaProducto.transferFocus();
        
        
    }                          
    
    private void jButton_BusqueProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BusqueProductoActionPerformed
        this.buscarProducto();
    }//GEN-LAST:event_jButton_BusqueProductoActionPerformed

    private void jButton_CancelaBusquedaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelaBusquedaProductoActionPerformed
        this.jDialog_BuscarProductoPorCod.dispose();
        this.jLabel_CodNoEncontrado.setText("");
        jTable_Factura.changeSelection( jTable_Factura.getSelectedRow(), jTable_Factura.getSelectedColumn(), false, false );
        jTable_Factura.requestFocus();
        
    }//GEN-LAST:event_jButton_CancelaBusquedaProductoActionPerformed

    private void jTextField_busqueProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_busqueProductoKeyPressed
        if(evt.getKeyCode()==10){
            this.jTextField_busqueProducto.transferFocus();
            
        
        }
    }//GEN-LAST:event_jTextField_busqueProductoKeyPressed

    private void jTextField_busqueProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_busqueProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_busqueProductoActionPerformed

    private void jButton_BusqueProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_BusqueProductoKeyPressed
        if(evt.getKeyCode()==10){
            this.buscarProducto();
        }
    }//GEN-LAST:event_jButton_BusqueProductoKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
         if(evt.getKeyCode()==10){
             jTable_Factura.changeSelection( jTable_Factura.getSelectedRow(), jTable_Factura.getSelectedColumn(), false, false );
             jTable_Factura.requestFocus();
             this.jDialog_VerProducto.dispose();
        }
       
    }//GEN-LAST:event_jButton2KeyPressed

    private void jFormattedTextField_precioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_precioProductoKeyTyped
        int tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
    
    }//GEN-LAST:event_jFormattedTextField_precioProductoKeyTyped

    private void jFormattedTextField_precioProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_precioProductoKeyPressed
         if(evt.getKeyCode()==10){
            this.jFormattedTextField_precioProducto.transferFocus();
            
        
        }
    }//GEN-LAST:event_jFormattedTextField_precioProductoKeyPressed

    private void jFormattedTextField_precioProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_precioProductoFocusGained
        this.jFormattedTextField_precioProducto.selectAll();
    }//GEN-LAST:event_jFormattedTextField_precioProductoFocusGained

    private void jFormattedTextField_cantidadProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField_cantidadProductoFocusGained
        this.jFormattedTextField_cantidadProducto.selectAll();
    }//GEN-LAST:event_jFormattedTextField_cantidadProductoFocusGained

    private void jFormattedTextField_cantidadProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_cantidadProductoKeyPressed
        if(evt.getKeyCode()==10){
            this.jFormattedTextField_cantidadProducto.transferFocus();
            
        
        }
    }//GEN-LAST:event_jFormattedTextField_cantidadProductoKeyPressed

    private void jFormattedTextField_cantidadProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_cantidadProductoKeyTyped
       int tecla= evt.getKeyChar();
       if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jFormattedTextField_cantidadProductoKeyTyped
public void personalizarTablaFactura() {
        /**DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        this.jTextField_Date.setText(dateFormat.format(date));**/
       Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        String[] columnNames = {"Cod. Articulo","Articulo","Cantidad","Precio.Unit",
            "Sub-Total"};
        List<Object[]> data = new ArrayList<Object[]>();
                 
        
        
        //Agrega el modelo a la factura
        MyTableModel_FACT model=new MyTableModel_FACT(columnNames,data);
        //Agrega 5 filas
        model.addRow(11);
        this.jTable_Factura.setModel(model);
        //Gana la atencion en el panel
        jTable_Factura.requestFocus();
        jTable_Factura.changeSelection(0,0,false, false);
        //AGREGA EL LISTENER QUE PERMITE HACER TODOS LOS EVENTOS DENTRO DE LA 
        //TABLA DE FACTURA //IMPORTANTE ESTOS EVENTOS ESTAN EN LA CLASE DE
        //MY TABLE MODEL LISTENER EN el metodo: tableChanged(TableModelEvent e)
         this.jTable_Factura.getModel().addTableModelListener(
                new MyTableModelListener_FACT(this.jTable_Factura,"",
                this.jTextField_Total,AdminBD));
        //Permite que la primera columna de Codigos se desplace segun lo que
        // haya en la base de datos
        AdminBD.verCodigos();
        String[] idproductos=this.obtenerFila(AdminBD.getData());
        this.jTable_Factura.getColumnModel().getColumn(0).
                setCellEditor(new SeleccionadorEditor(idproductos,jTable_Factura));
        //Permite que la segunda columna de Descripciones se desplace segun 
        //lo que haya en la base de datos
        /**BDmanagment.get_DescProductos();
        String[] desc_Productos=this.get_Fila(this.BDmanagment.getData());
        this.jTable_Factura.getColumnModel().getColumn(1).
                setCellEditor(new SeleccionadorEditor(desc_Productos,jTable_Factura));**/
        //Costumisando Precio y Cantidad (Solo van a permitir numeros)
        this.jTable_Factura.getColumnModel().getColumn(2).
                setCellEditor(new EditorDeCeldaNumeros());
        this.jTable_Factura.getColumnModel().getColumn(3).
                setCellEditor(new EditorDeCeldaNumeros());
        //Demasiado importante ******Permite que se pueda editar apenas se 
        //ingresan datos*****
        this.jTable_Factura.setSurrendersFocusOnKeystroke(true);
        
        
    }
    /**
     * De vuelve un String[] con toda la informacion de una fila de una tabla
     * @param data  
     * //Viene de un consulta UNICAMENTE de una fila
     * @return 
     */
    private String[] obtenerFila(Object[][] data) {
        //System.out.println("ESTO ES LO QUE QUIERO");
        int numFilas= data.length;
        String[] string= new String[numFilas];
        int numColumnas= data[0].length;
        for(int row =0 ; row < numFilas;row++) {
            for(int column =0; column<numColumnas;column++) {
                string[row]=data[row][column].toString();
                //System.out.print(data[row][column]+" ");
                
            }
            //System.out.println();
        }
        return string;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton_BusqueProducto;
    javax.swing.JButton jButton_CancelaBusquedaProducto;
    javax.swing.JButton jButton_CancelarCrearProducto;
    javax.swing.JButton jButton_CreaProducto;
    javax.swing.JButton jButton_CrearProducto;
    javax.swing.JButton jButton_Descuento;
    javax.swing.JButton jButton_EliminaFila;
    javax.swing.JButton jButton_RegresarFact;
    javax.swing.JButton jButton_VerProducto;
    javax.swing.JDialog jDialog_BuscarProductoPorCod;
    javax.swing.JDialog jDialog_CrearProducto;
    javax.swing.JDialog jDialog_VerProducto;
    javax.swing.JFormattedTextField jFormattedTextField_cantidadProducto;
    javax.swing.JFormattedTextField jFormattedTextField_precioProducto;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel_Cantidad;
    javax.swing.JLabel jLabel_CodNoEncontrado;
    javax.swing.JLabel jLabel_Descripcion;
    javax.swing.JLabel jLabel_Fact;
    javax.swing.JLabel jLabel_Nombre;
    javax.swing.JLabel jLabel_PrecioUnitario;
    javax.swing.JLabel jLabel_Producto;
    javax.swing.JLabel jLabel_datoCant;
    javax.swing.JLabel jLabel_datoFact;
    javax.swing.JLabel jLabel_datoNomb;
    javax.swing.JLabel jLabel_datoPrecio;
    javax.swing.JLayeredPane jLayeredPane_VerProducto;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable_Factura;
    javax.swing.JTextField jTextField_Total;
    javax.swing.JTextField jTextField_busqueProducto;
    javax.swing.JTextField jTextField_codigo;
    javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables
}
