/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Montes
 */
public class NewJDialog_PagoApartado extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog_PagoApartado
     */
    private String fecha;
    private BigDecimal montoDePago;
    DateFormat dateF = new SimpleDateFormat("yyyy-MM-dd");
    private static NewJDialog_PagoApartado PagoApartado;
    
    public NewJDialog_PagoApartado() {
        
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public void setTittle(String pTittle){
        lbTittle.setText(pTittle);
    }
    
    public static NewJDialog_PagoApartado getInstance() {
        if (PagoApartado == null) {
            PagoApartado = new NewJDialog_PagoApartado();
        }
        PagoApartado.jFormattedTextField_MontoApartado.setValue(BigDecimal.ZERO);
        return PagoApartado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField_MontoApartado = new javax.swing.JFormattedTextField();
        jButton_AceptarApartado = new javax.swing.JButton();
        jButton_CancelarApartado = new javax.swing.JButton();
        lbTittle = new javax.swing.JLabel();
        dateChooserCombo_FechaVencimiento = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 185));
        setModal(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha de Vencimiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Monto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 20));

        jFormattedTextField_MontoApartado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_MontoApartado.setText("0.00");
        jFormattedTextField_MontoApartado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_MontoApartadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField_MontoApartadoKeyTyped(evt);
            }
        });
        jPanel1.add(jFormattedTextField_MontoApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 100, 110, -1));

        jButton_AceptarApartado.setText("Aceptar");
        jButton_AceptarApartado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarApartadoActionPerformed(evt);
            }
        });
        jButton_AceptarApartado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_AceptarApartadoKeyPressed(evt);
            }
        });
        jPanel1.add(jButton_AceptarApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 138, -1, -1));

        jButton_CancelarApartado.setText("Cancelar");
        jButton_CancelarApartado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarApartadoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_CancelarApartado, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 138, -1, -1));

        lbTittle.setBackground(new java.awt.Color(0, 153, 255));
        lbTittle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTittle.setForeground(new java.awt.Color(255, 255, 255));
        lbTittle.setText("  Detalles del Apartado");
        lbTittle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbTittle.setOpaque(true);
        jPanel1.add(lbTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 34));

        dateChooserCombo_FechaVencimiento.setNothingAllowed(false);
        dateChooserCombo_FechaVencimiento.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        jPanel1.add(dateChooserCombo_FechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 62, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AceptarApartadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarApartadoActionPerformed
         try {
             
             if(this.jFormattedTextField_MontoApartado.getText().equals("")){
                 JOptionPane.showMessageDialog(
                          null,
                          "Debe de ingresar un pago porfavor",
                          "Alert!", JOptionPane.ERROR_MESSAGE);
                          return;
             }
            
             this.setFecha(dateF.format(dateChooserCombo_FechaVencimiento.
                            getSelectedDate().
                            getTime()));
           //  this.setFecha(this.jFormattedTextField_FechaVencimiento.getText());
             this.setMontoDePago(this.StringtoBigDecimal(this.jFormattedTextField_MontoApartado.getText()));
             

        } catch (Exception e) {
        }
        this.dispose();
                      
    }//GEN-LAST:event_jButton_AceptarApartadoActionPerformed

    private void jButton_CancelarApartadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarApartadoActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelarApartadoActionPerformed

    private void jFormattedTextField_MontoApartadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_MontoApartadoKeyTyped
        int tecla= evt.getKeyChar();
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jFormattedTextField_MontoApartadoKeyTyped

    private void jFormattedTextField_MontoApartadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_MontoApartadoKeyPressed
        if(evt.getKeyCode()==10){
            this.jFormattedTextField_MontoApartado.transferFocus();
              
        }
         if (evt.isControlDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextField_MontoApartadoKeyPressed

    private void jButton_AceptarApartadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_AceptarApartadoKeyPressed
         if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            this.jButton_AceptarApartado.doClick();
              
        }
        
    }//GEN-LAST:event_jButton_AceptarApartadoKeyPressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    datechooser.beans.DateChooserCombo dateChooserCombo_FechaVencimiento;
    javax.swing.JButton jButton_AceptarApartado;
    javax.swing.JButton jButton_CancelarApartado;
    javax.swing.JFormattedTextField jFormattedTextField_MontoApartado;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JPanel jPanel1;
    javax.swing.JLabel lbTittle;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fecha
     */
    public String getFecha() {
        return fecha;
    }

    /**
     * @param fecha the fecha to set
     */
    public void setFecha(String fecha) {
        setVisible(true);
        this.fecha = fecha;
    }

    /**
     * @return the montoDePago
     */
    public BigDecimal getMontoDePago() {
        return montoDePago;
    }

    /**
     * @param montoDePago the montoDePago to set
     */
    public void setMontoDePago(BigDecimal montoDePago) {
        setVisible(true);
        this.montoDePago = montoDePago;
    }
    
     /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     * @param numero
     * @return 
     */
    private BigDecimal StringtoBigDecimal(String numero){
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;
    
    }
}
