/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import ManejoDeArchivos.XMLConfiguracion;
import db_managment.Direct_Control_BD;
import java.math.BigDecimal;
import java.math.MathContext;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jzebra.PrintRaw;
import jzebra.PrintServiceMatcher;

/**
 *
 * @author Oscar Montes
 */
public class Pan_CerrarCaja extends javax.swing.JPanel {

    public static final int NEW_CALL = 0;
    public static final int WATCH_CALL = 1;
    
    private final int _callType;
    
    private boolean _savePress;
    private boolean _printPress;
    public static final String printer = "Generic / Text Only (Copy 5)";
    /**
     * Creates new form JPanel_CerrarCaja
     */
    public Pan_CerrarCaja(int pCallType) {
        initComponents();
        _callType = pCallType;
        _savePress = _printPress = false;
        if (pCallType == WATCH_CALL){
            saveBtt.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Cajero = new javax.swing.JLabel();
        jLabel_horaInicio = new javax.swing.JLabel();
        jLabel_horaCierre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField_totalContado = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField_totalVenta = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalTarjeta = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_VerCierre = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField_totalVentaConCaja = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bttPrint = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        saveBtt = new javax.swing.JLabel();
        jFormattedTextField_totalContadoReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalTarjetaReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalVentaReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalVentaCajaReportado = new javax.swing.JFormattedTextField();
        jLabel_detalle = new javax.swing.JLabel();
        jFormattedTextField_gastos = new javax.swing.JFormattedTextField();

        setMinimumSize(new java.awt.Dimension(800, 471));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 471));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hora Inicio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cajero");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hora Cierre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel_Cajero.setText("Nombre Cajero");
        add(jLabel_Cajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel_horaInicio.setText("Hora Inicio");
        add(jLabel_horaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 154, -1));

        jLabel_horaCierre.setText("Hora Cierre");
        add(jLabel_horaCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 154, -1));

        jLabel4.setText("Total tarjeta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 95, 20));

        jLabel5.setText("Total Contado");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, 17));

        jFormattedTextField_totalContado.setEditable(false);
        jFormattedTextField_totalContado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalContado.setText("0.00");
        add(jFormattedTextField_totalContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 151, -1));

        jLabel6.setText("Total Venta");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 128, 20));

        jFormattedTextField_totalVenta.setEditable(false);
        jFormattedTextField_totalVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVenta.setText("0.00");
        add(jFormattedTextField_totalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 151, -1));

        jFormattedTextField_totalTarjeta.setEditable(false);
        jFormattedTextField_totalTarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalTarjeta.setText("0.00");
        add(jFormattedTextField_totalTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 151, -1));

        jLabel14.setText("Total Gastos");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jTable_VerCierre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_VerCierre);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 769, 175));

        jLabel7.setText("Total Venta + Monto Caja");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 142, 20));

        jFormattedTextField_totalVentaConCaja.setEditable(false);
        jFormattedTextField_totalVentaConCaja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVentaConCaja.setText("0.00");
        add(jFormattedTextField_totalVentaConCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 151, -1));

        jLabel8.setText("Total Contado Reportado");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 20));

        jLabel9.setText("Total Tarjeta  Reportado");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        bttPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/printBtt.png"))); // NOI18N
        bttPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttPrintMouseExited(evt);
            }
        });
        add(bttPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jLabel10.setText("Total Venta Reportado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 20));

        jLabel11.setText("Total Venta + Monto Caja");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cerrar Caja");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        saveBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/saveBtt.png"))); // NOI18N
        saveBtt.setToolTipText("Aceptar y guardar cierre de caja");
        saveBtt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saveBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBttMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBttMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBttMouseExited(evt);
            }
        });
        add(saveBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, -1, -1));

        jFormattedTextField_totalContadoReportado.setEditable(false);
        jFormattedTextField_totalContadoReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalContadoReportado.setText("0.00");
        add(jFormattedTextField_totalContadoReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 136, -1));

        jFormattedTextField_totalTarjetaReportado.setEditable(false);
        jFormattedTextField_totalTarjetaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalTarjetaReportado.setText("0.00");
        jFormattedTextField_totalTarjetaReportado.setToolTipText("");
        add(jFormattedTextField_totalTarjetaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 136, -1));

        jFormattedTextField_totalVentaReportado.setEditable(false);
        jFormattedTextField_totalVentaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVentaReportado.setText("0.00");
        add(jFormattedTextField_totalVentaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 136, -1));

        jFormattedTextField_totalVentaCajaReportado.setEditable(false);
        jFormattedTextField_totalVentaCajaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVentaCajaReportado.setText("0.00");
        add(jFormattedTextField_totalVentaCajaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 136, -1));

        jLabel_detalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_detalle.setText("Todo esta perfecto");
        add(jLabel_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 472, -1));

        jFormattedTextField_gastos.setEditable(false);
        jFormattedTextField_gastos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_gastos.setText("0.00");
        add(jFormattedTextField_gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 136, -1));
    }//GEN-END:initComponents

    private void saveBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttMouseClicked
        if (!_savePress){
            _savePress = true;
            saveAction();
        }
        _savePress = false;
        
    }                                    
    
    private void saveAction(){
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        int idCierreVigente= AdminBD.obtenerultimoidCierre();
        String HoraCierre= this.jLabel_horaCierre.getText();
        BigDecimal totalTarjet = this.corregirDato(this.jFormattedTextField_totalTarjeta.getText());
        BigDecimal totalCont = this.corregirDato(this.jFormattedTextField_totalContado.getText());
        BigDecimal totalVendido = totalTarjet.add(totalCont);
        BigDecimal gastos= this.corregirDato(this.jFormattedTextField_gastos.getText());
        String observaciones= this.jLabel_detalle.getText();
        BigDecimal ReporteFinal= this.corregirDato(this.jFormattedTextField_totalVentaReportado.getText());
        BigDecimal totalTarjtReportado= this.corregirDato(this.jFormattedTextField_totalTarjetaReportado.getText());
        BigDecimal totalContReportado = this.corregirDato(this.jFormattedTextField_totalContadoReportado.getText());
        AdminBD.actualizarCierreDeCaja(HoraCierre, totalVendido, observaciones, ReporteFinal, totalCont, totalTarjet, totalContReportado, totalTarjtReportado, idCierreVigente,gastos);
        StartWindow.getInstance().enableMe();
        JF_Facturacion.getInstance().dispose();
    }//GEN-LAST:event_saveBttMouseClicked
    private void imprimirCierre(JTable table,String Cajero, String horaInicio, String horaCierre,
            String totalcontadoReportado, String totaltarjetaReportado, String totalVentaReportado,
            String totalVentaCajaReportado, String totalcontadoSistema,
            String totaltarjetaSistema, String totalVentaSistema, String totalVentaCajaSistema, String Detalle, String gasto) {
        try {
            String rawCmds = "FIRST NAME";
            PrintService ps = PrintServiceMatcher.findPrinter(printer);
            if (ps != null) {

                PrintRaw p = new PrintRaw(ps, rawCmds);
                p.clear();
                p.append("\u001B\u0040"); //reset printer 

                XMLConfiguracion xml = new XMLConfiguracion();
                String[] infoEmpresa = xml.leerInfoEmpresaXML();
                p.append("\u001B" + "\u0061" + "\u0001" + "\r");//*** Centrado
                p.append(infoEmpresa[0]+"\r\n");
                p.append(infoEmpresa[1]+"\r\n");
                p.append("Tel: "+infoEmpresa[4]+"\r\n");
                p.append("Ced Jur: "+infoEmpresa[3]+"\r\n");
                 if(!infoEmpresa[5].equals("")){
                    p.append(infoEmpresa[5]+"\r\n");
                }
                p.append("\u001B" + "\u0064" + "\u0001" + "\r");//*** 1lineas
                p.append(xml.ObtenerSlogan()+"\r\n");
                p.append("\u001B" + "\u0064" + "\u0001" + "\r");//*** 1lineas
                p.append("\u001B" + "\u0061" + "\u0000" + "\r");//Quita Centrado
                

                p.append("\u001B" + "\u0061" + "\u0000" + "\r");//Quita Centrado

                String fecha = " Cajero        :  " + Cajero + "";
                p.append("----------------------------------------\r\n");
                String fechamov = this.fill(fecha, 13, " ");
                p.append(fechamov + "\r\n");
                p.append(this.fill(" Hora Inicio   :  " + horaInicio + "", fechamov.length(), " ") + "\r\n");
                p.append(this.fill(" Hora Cierre   :  " + horaCierre + "", fechamov.length(), " ") + "\r\n");
                
                p.append("----------------------------------------\r\n");
                //Agrega 1 linea vacia
                p.append("\u001B" + "\u0064" + "\u0001" + "\r");
                p.append("NUM FACT     PAGO TARJETA   PAGO CONTADO\r\n");
                p.append("--------      -----------   ------------\r\n");

                /**
                 * ********************************************************
                 */
                int nRow = table.getRowCount();
                for (int i = 0; i < nRow; i++) {
                    String Concepto = table.getValueAt(i, 1).toString();
                    if (!Concepto.equals("")) {
                        String numFact = this.fill(table.getValueAt(i, 2).toString(),15," ");
                        String montoTarjeta = this.fill(table.getValueAt(i, 3).toString(),8," ");
                        String montoContado= this.fill(table.getValueAt(i, 4).toString(),11," ");
                        p.append(""+Concepto+"\r\n");
                        p.append(""+numFact+" "+montoTarjeta+"     "+""+montoContado+"\r\n");
                    }

                }
                p.append("----------------------------------------\r\n");
                p.append("\u001B" + "\u0061" + "\u0002" + "\r");//*** Derecha
                p.append("\u001B" + "\u0064" + "\u0003" + "\r");//*** 1lineas
                
                String totalcontadoS = this.fill("Total Contado Sistema", 24, " ");
                String totalcontadoSys = totalcontadoS+":"+" "+ this.fill(totalcontadoSistema,14," ");
                p.append(totalcontadoSys + "\r\n");
                String totaltarjetaS = this.fill("Total Tarjeta Sistema", 24, " ");
                String totaltarjetaSys = totaltarjetaS+":"+" "+ this.fill(totaltarjetaSistema,14," ");
                p.append(totaltarjetaSys + "\r\n");
                String totalventaS=this.fill("Total Venta Sistema", 24, " ");
                String totalventaSys = totalventaS+":"+" "+ this.fill(totalVentaSistema,14," ");
                p.append(totalventaSys + "\r\n");
                String totalventaCS=this.fill("Total Venta Sistm + Caja", 24, " ");
                String totalventaCSys = totalventaCS+":"+" "+ this.fill( totalVentaCajaSistema,14," ");
                p.append(totalventaCSys + "\r\n");
                
                p.append("\u001B" + "\u0064" + "\u0001" + "\r");//*** 1lineas
                
                String totalcontador = this.fill("Total Contado Reportado", 24, " ");
                String totalcontadoRep = totalcontador+":"+" "+ this.fill(totalcontadoReportado,14," ");
                p.append(totalcontadoRep + "\r\n");
                String totaltarjetar = this.fill("Total Tarjeta Reportado",24, " ");
                String totaltarjetaRep = totaltarjetar+":"+" "+ this.fill(totaltarjetaReportado,14," ");
                p.append(totaltarjetaRep + "\r\n");
                String totalventar=this.fill("Total Venta Reportado", 24, " ");
                String totalventaRep = totalventar+":"+" "+ this.fill(totalVentaReportado,14," ");
                p.append(totalventaRep + "\r\n");
                String totalgasto=this.fill("Total Gastos", 24, " ");
                String totalgastoRep = totalgasto+":"+" "+ this.fill(gasto,14," ");
                p.append(totalgastoRep + "\r\n");
                String totalventaCr=this.fill("Total Venta Repor + Caja", 24, " ");
                String totalventaCRep = totalventaCr+":"+" "+ this.fill(totalVentaCajaReportado,14," ");
                p.append(totalventaCRep + "\r\n");
                p.append("\u001B" + "\u0064" + "\u0001" + "\r");//*** 1lineas
                p.append("\u001B" + "\u0061" + "\u0001" + "\r");//*** Centrado
                p.append(""+Detalle+""+"\r\n");
                p.append("\u001B" + "\u0061" + "\u0000" + "\r");//Quita Centrado
               
                
                
                p.append("----------------------------------------\r\n");

                p.append("\u001B\u0040");//reset printer
                p.append("\u001B" + "\u0064" + "\u0008" + "\r");//*** 10lineas**/
                p.append("\u001D" + "\u0056" + "\u0001" + "\r");//*** CutPaper

                p.print();

            } else {
                System.err.println("No encontro ninguna impresora");
                return;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return;
        }
    }

    public String fill(int length, String with) {
        StringBuilder sb = new StringBuilder(length);
        while (sb.length() < length) {
            sb.append(with);
        }
        return sb.toString();
    }

    public String fill(String value, int length, String with) {

        StringBuilder result = new StringBuilder(length);
        result.append(value);
        result.append(fill(Math.max(0, length - value.length()), with));

        return result.toString();

    }

    private void saveBttMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttMouseEntered
        saveBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/saveBttOvr.png")));
    }//GEN-LAST:event_saveBttMouseEntered

    private void saveBttMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttMouseExited
        saveBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/saveBtt.png")));
    }//GEN-LAST:event_saveBttMouseExited

    private void bttPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttPrintMouseClicked
        if (!_printPress){
            _printPress = true;
            
            if (_callType == NEW_CALL){
                saveAction();
            }
            String HoraInicio= this.jLabel_horaInicio.getText();
            String HoraCierre= this.jLabel_horaCierre.getText();

            this.imprimirCierre(jTable_VerCierre,this.jLabel_Cajero.getText(),
                    HoraInicio, HoraCierre,
                    this.jFormattedTextField_totalContadoReportado.getText(),
                    this.jFormattedTextField_totalTarjetaReportado.getText(),
                    this.jFormattedTextField_totalVentaReportado.getText(),
                    jFormattedTextField_totalVentaCajaReportado.getText(),
                    this.jFormattedTextField_totalContado.getText(),
                    this.jFormattedTextField_totalTarjeta.getText(),
                    this.jFormattedTextField_totalVenta.getText(),
                    this.jFormattedTextField_totalVentaConCaja.getText(),
                    this.jLabel_detalle.getText(),
                    this.jFormattedTextField_gastos.getText());

        }
        _printPress = false;
            
    }//GEN-LAST:event_bttPrintMouseClicked

    private void bttPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttPrintMouseEntered
        bttPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/printBttOvr.png")));
    }//GEN-LAST:event_bttPrintMouseEntered

    private void bttPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttPrintMouseExited
        bttPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/printBtt.png")));
    }//GEN-LAST:event_bttPrintMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel bttPrint;
    javax.swing.JFormattedTextField jFormattedTextField_gastos;
    javax.swing.JFormattedTextField jFormattedTextField_totalContado;
    javax.swing.JFormattedTextField jFormattedTextField_totalContadoReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalTarjeta;
    javax.swing.JFormattedTextField jFormattedTextField_totalTarjetaReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalVenta;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaCajaReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaConCaja;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaReportado;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JLabel jLabel_Cajero;
    javax.swing.JLabel jLabel_detalle;
    javax.swing.JLabel jLabel_horaCierre;
    javax.swing.JLabel jLabel_horaInicio;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable_VerCierre;
    javax.swing.JLabel saveBtt;
    // End of variables declaration//GEN-END:variables

    void personalizarTablaCierre(BigDecimal totalcontadoreportado,BigDecimal totaltarjetareportado,BigDecimal totalventareportado,String Cajero,
        String fechaInicio,BigDecimal montoinicio, BigDecimal gastos) {
        this.jLabel_Cajero.setText(Cajero);
        this.jLabel_horaInicio.setText(fechaInicio);        
        String[] columnNames = {"Fecha","Concepto",
            "Num Fact","Pago Tarjeta","Pago Contado"};
        List<Object[]> data = new ArrayList<Object[]>();      
        //Agrega el modelo a la factura
        Modelo_CierreCaja model=new Modelo_CierreCaja(columnNames,data);
        this.jTable_VerCierre.setModel(model);
        this.cargarListenerRenders();
        this.cargarFacturasCierre(model);
        this.cargarApartadoCreditosCierre(model);
        this.cargarDevolucionesCierre(model);
        BigDecimal totalTarjet = this.corregirDato(this.jFormattedTextField_totalTarjeta.getText());
        BigDecimal totalCont = this.corregirDato(this.jFormattedTextField_totalContado.getText());
        BigDecimal totalventaconcaja=totalTarjet.add(totalCont).add(montoinicio);
        this.jFormattedTextField_totalVenta.setValue(totalTarjet.add(totalCont));
        this.jFormattedTextField_totalVentaConCaja.setValue(totalventaconcaja);
        this.jFormattedTextField_totalContadoReportado.setValue(totalcontadoreportado);
        this.jFormattedTextField_totalTarjetaReportado.setValue(totaltarjetareportado);
        this.jFormattedTextField_totalVentaReportado.setValue(totalventareportado.subtract(montoinicio));
        this.jFormattedTextField_totalVentaCajaReportado.setValue(totalventareportado);
        this.jFormattedTextField_gastos.setValue(gastos);
        if(totalventareportado.add(gastos).compareTo(totalventaconcaja)<0){
            this.jLabel_detalle.setText("Existe un faltante de: "+""+ totalventaconcaja.subtract(totalventareportado.add(gastos)));
        }
        if(totalventareportado.add(gastos).compareTo(totalventaconcaja)>0){
            this.jLabel_detalle.setText("Existe un sobrante de: "+""+ totalventaconcaja.subtract(totalventareportado.add(gastos)).abs());
        }
        /// Ordena la tabla con base a la fecha de la ultima compra
        RowSorter<Modelo_CierreCaja> sorter= new TableRowSorter<Modelo_CierreCaja>(model);
        this.jTable_VerCierre.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKeys);
        model.addRow(20);
    
        
        //this.jTable_VerCierre.setAutoCreateRowSorter(true);
        
    }
    /**
     * Este metodo permite corregir el dato que tiene el signo de C y ademas que
     * puede tener comas ya que el tipo Decimal en la base solo puede tener
     * puntos y no comas.
     *
     * @param Dato
     * @return
     */
    private BigDecimal corregirDato(String Dato) {
        String datoAcorregir = Dato.replace("C", "");
        DecimalFormat decimalformat = (DecimalFormat) NumberFormat.getInstance();
        decimalformat.setParseBigDecimal(true);
        BigDecimal DatoCorregido = null;
        try {
            DatoCorregido = (BigDecimal) decimalformat.parseObject(datoAcorregir);
        } catch (ParseException ex) {
            Logger.getLogger(MyTableModelListener_FACT.class.getName()).log(Level.SEVERE, null, ex);
        }
        return DatoCorregido;

    }
    private void cargarFacturasCierre(Modelo_CierreCaja model) {
       
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierreFacturasContado(this.jLabel_horaInicio.getText(),this.jLabel_horaCierre.getText());
        Object[][] InfoFactsContadoCierre = AdminBD.getData();
        int numFilas = InfoFactsContadoCierre.length;
        for (int row = 0; row < numFilas; row++) {
            model.addRow(1);
            Object[] infofactscontado= InfoFactsContadoCierre[row];
            String Fecha= infofactscontado[0].toString();
            String Concepto= infofactscontado[1].toString();
            int NumFact = Integer.parseInt(infofactscontado[2].toString());
            BigDecimal montoTarjeta=this.StringtoBigDecimal(infofactscontado[3].toString());
            BigDecimal montoContado= this.StringtoBigDecimal(infofactscontado[4].toString());
            model.setValueAt(Fecha, row, 0);
            model.setValueAt(Concepto, row, 1);
            model.setValueAt(NumFact, row, 2);
            model.setValueAt(montoTarjeta, row, 3);
            model.setValueAt(montoContado, row, 4);
            
            
            }
    
    }
    private void cargarApartadoCreditosCierre(Modelo_CierreCaja model) {
       
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierreApartadosCreditos(this.jLabel_horaInicio.getText(),this.jLabel_horaCierre.getText());
        Object[][] InfoApartadoCreditosCierre = AdminBD.getData();
        int numFilasTablas = model.getRowCount();
        int numFilas= InfoApartadoCreditosCierre.length;
        for (int row = 0; row < numFilas; row++) {
            model.addRow(1);
            Object[] infoapscreditos= InfoApartadoCreditosCierre[row];
            String Fecha= infoapscreditos[0].toString();
            String Concepto= infoapscreditos[1].toString();
            int NumFact = Integer.parseInt(infoapscreditos[2].toString());
            BigDecimal montoTarjeta=this.StringtoBigDecimal(infoapscreditos[3].toString());
            BigDecimal montoContado= this.StringtoBigDecimal(infoapscreditos[4].toString());
            model.setValueAt(Fecha, numFilasTablas+row, 0);
            model.setValueAt(Concepto, numFilasTablas+row, 1);
            model.setValueAt(NumFact, numFilasTablas+row, 2);
            model.setValueAt(montoTarjeta, numFilasTablas+row, 3);
            model.setValueAt(montoContado, numFilasTablas+row, 4);
            
            
            }
    
    }
     private void cargarDevolucionesCierre(Modelo_CierreCaja model) {
       
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierreDevoluciones(this.jLabel_horaInicio.getText(),this.jLabel_horaCierre.getText());
        Object[][] InfoDevCierre = AdminBD.getData();
        int numFilasTablas = model.getRowCount();
        int numFilas= InfoDevCierre.length;
        for (int row = 0; row < numFilas; row++) {
            model.addRow(1);
            Object[] infodev= InfoDevCierre[row];
            String Fecha= infodev[0].toString();
            String Concepto= infodev[1].toString();
            int NumFact = Integer.parseInt(infodev[2].toString());
            BigDecimal montoTarjeta=this.StringtoBigDecimal(infodev[3].toString());
            BigDecimal montoContado= this.StringtoBigDecimal(infodev[4].toString());
            model.setValueAt(Fecha, numFilasTablas+row, 0);
            model.setValueAt(Concepto, numFilasTablas+row, 1);
            model.setValueAt(NumFact, numFilasTablas+row, 2);
            model.setValueAt(montoTarjeta, numFilasTablas+row, 3);
            model.setValueAt(montoContado.negate(), numFilasTablas+row, 4);
            
            
            }
    
    }
    private void cargarListenerRenders() {
        //AGREGA EL LISTENER QUE PERMITE HACER TODOS LOS EVENTOS DENTRO DE LA 
        //TABLA DE VER CIERRE //IMPORTANTE ESTOS EVENTOS ESTAN EN LA CLASE DE
        //MY ListenerCierreDeCaja EN el metodo: tableChanged(TableModelEvent e)
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        this.jTable_VerCierre.getModel().addTableModelListener(new ListenerCierreCaja(this.jTable_VerCierre,this.jFormattedTextField_totalTarjeta,AdminBD,this.jFormattedTextField_totalContado));
           //Costumisando Precio y Cantidad (Solo van a permitir numeros)
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        this.jTable_VerCierre.getColumnModel().getColumn(2).
                setCellRenderer(rightRenderer);
        this.jTable_VerCierre.getColumnModel().getColumn(4).
                setCellRenderer(new CurrencyRender());
        this.jTable_VerCierre.getColumnModel().getColumn(3).
                setCellRenderer(new CurrencyRender());
        
    
    }

 /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     * @param numero
     * @return 
     */
    private BigDecimal StringtoBigDecimal(String numero){
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;
    
    }

    private void regresarVentanaPrincipal() {
        VentanaDeInicio mVentana= VentanaDeInicio.getInstance();
        mVentana.remove(this);
        mVentana.revalidate();
        mVentana.repaint();
        mVentana.setTitle("Joe");
        mVentana.add(mVentana.jPanel_VentanaPrincipal);
        mVentana.jPanel_VentanaPrincipal.setVisible(true);    
    }
    
}

