/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joe;

import ManejoDeArchivos.XMLConfiguracion;
import db_managment.Direct_Control_BD;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jason
 */
public class Pan_ConfUsser extends javax.swing.JPanel {

    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Object[][] data;
    Direct_Control_BD AdminBD;
    DateFormat dateF = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form NewJPanel_Configuracion
     */
    public Pan_ConfUsser() {
        initComponents();
        AdminBD = Direct_Control_BD.getInstance();
        addPanelsToDialog();
        hideAllPanels();
        actualizarTabla();
    }

    private void addPanelsToDialog(){
        jDialog_AdmiVend.add(jPanel_CrearAdmVend);
        jDialog_AdmiVend.add(jPanel_ModifAdmVend);
        jDialog_AdmiVend.add(jPanel_VerAdmVend);
    }
    
    private void hideAllPanels(){
        jPanel_CrearAdmVend.setVisible(false);
        jPanel_ModifAdmVend.setVisible(false);
        jPanel_VerAdmVend.setVisible(false);
        
        jPanel_CrearAdmVend.setEnabled(false);
        jPanel_ModifAdmVend.setEnabled(false);
        jPanel_VerAdmVend.setEnabled(false);
    }
    
    private void showPanelOnDialog(javax.swing.JPanel pPanel){
        hideAllPanels();
        jDialog_AdmiVend.setSize(pPanel.getSize());
        jDialog_AdmiVend.setLocationRelativeTo(null);
        
        pPanel.setVisible(true);
        pPanel.setEnabled(true);
        jDialog_AdmiVend.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_AdmiVend = new javax.swing.JDialog();
        buttonGroup = new javax.swing.ButtonGroup();
        jPanel_CrearAdmVend = new javax.swing.JPanel();
        jLabel_nombreCliente10 = new javax.swing.JLabel();
        jLabel_telefonoCliente7 = new javax.swing.JLabel();
        jLabel_direccionCliente7 = new javax.swing.JLabel();
        jLabel_FechaCumpleanos7 = new javax.swing.JLabel();
        jFormattedTextField_nombreAdm = new javax.swing.JFormattedTextField();
        jFormattedTextField_telefonoAdm = new javax.swing.JFormattedTextField();
        jFormattedTextField_direccionAdm = new javax.swing.JFormattedTextField();
        jButton_CrearAdministrador = new javax.swing.JButton();
        jButton_CancelarCrearCliente4 = new javax.swing.JButton();
        jLabel_nombreCliente11 = new javax.swing.JLabel();
        jPasswordField_Adm = new javax.swing.JPasswordField();
        dateChooserCombo_CumpCrearVendAdm = new datechooser.beans.DateChooserCombo();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_Vendedor = new javax.swing.JRadioButton();
        jRadioButton_Administrador = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_VerAdmVend = new javax.swing.JPanel();
        jLabel_nombreCliente12 = new javax.swing.JLabel();
        jLabel_telefonoCliente8 = new javax.swing.JLabel();
        jLabel_direccionCliente8 = new javax.swing.JLabel();
        jLabel_FechaCumpleanos8 = new javax.swing.JLabel();
        jButton_CrearCliente5 = new javax.swing.JButton();
        jButton_CancelarCrearCliente5 = new javax.swing.JButton();
        jLabel_DirreVerAdmVend = new javax.swing.JLabel();
        jLabel_FechaCVerAdmVend = new javax.swing.JLabel();
        jLabel_TeleVerAdmVend = new javax.swing.JLabel();
        jLabel_NombreVerAdmVend = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_ModifAdmVend = new javax.swing.JPanel();
        jLabel_nombreCliente13 = new javax.swing.JLabel();
        jLabel_telefonoCliente9 = new javax.swing.JLabel();
        jLabel_direccionCliente9 = new javax.swing.JLabel();
        jLabel_FechaCumpleanos10 = new javax.swing.JLabel();
        jFormattedTextField_Modifnombre = new javax.swing.JFormattedTextField();
        jFormattedTextField_Modiftelefono = new javax.swing.JFormattedTextField();
        jFormattedTextField_Modifdireccion = new javax.swing.JFormattedTextField();
        jButton_ModifAdmVend = new javax.swing.JButton();
        jButton_CancelarModifAdmVend = new javax.swing.JButton();
        jLabel_nombreCliente14 = new javax.swing.JLabel();
        jPasswordField_Modif = new javax.swing.JTextField();
        dateChooserCombo_CumpModfVendAdm = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Generica_AdmVend = new javax.swing.JTable();
        TextField_BuscadorVend = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jDialog_AdmiVend.setModal(true);
        jDialog_AdmiVend.setUndecorated(true);
        jDialog_AdmiVend.setResizable(false);
        jDialog_AdmiVend.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialog_AdmiVendWindowClosed(evt);
            }
        });
        jDialog_AdmiVend.getContentPane().setLayout(null);

        jPanel_CrearAdmVend.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_CrearAdmVend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_CrearAdmVend.setMaximumSize(new java.awt.Dimension(345, 270));
        jPanel_CrearAdmVend.setMinimumSize(new java.awt.Dimension(345, 270));
        jPanel_CrearAdmVend.setPreferredSize(new java.awt.Dimension(345, 270));
        jPanel_CrearAdmVend.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel_CrearAdmVendComponentShown(evt);
            }
        });
        jPanel_CrearAdmVend.setLayout(null);
        jPanel_CrearAdmVend.setSize(345, 270);

        jLabel_nombreCliente10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombreCliente10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente10.setText("Nombre ");
        jPanel_CrearAdmVend.add(jLabel_nombreCliente10);
        jLabel_nombreCliente10.setBounds(10, 40, 47, 23);

        jLabel_telefonoCliente7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_telefonoCliente7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefonoCliente7.setText("Telefono");
        jPanel_CrearAdmVend.add(jLabel_telefonoCliente7);
        jLabel_telefonoCliente7.setBounds(10, 100, 105, 23);

        jLabel_direccionCliente7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_direccionCliente7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccionCliente7.setText("Direccion");
        jPanel_CrearAdmVend.add(jLabel_direccionCliente7);
        jLabel_direccionCliente7.setBounds(10, 130, 105, 23);

        jLabel_FechaCumpleanos7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_FechaCumpleanos7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCumpleanos7.setText("Fecha de Cumpleanos");
        jPanel_CrearAdmVend.add(jLabel_FechaCumpleanos7);
        jLabel_FechaCumpleanos7.setBounds(10, 160, 130, 23);

        jFormattedTextField_nombreAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_nombreAdmKeyPressed(evt);
            }
        });
        jPanel_CrearAdmVend.add(jFormattedTextField_nombreAdm);
        jFormattedTextField_nombreAdm.setBounds(160, 40, 168, 25);

        jFormattedTextField_telefonoAdm.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_telefonoAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_telefonoAdmKeyPressed(evt);
            }
        });
        jPanel_CrearAdmVend.add(jFormattedTextField_telefonoAdm);
        jFormattedTextField_telefonoAdm.setBounds(160, 100, 168, 25);

        jFormattedTextField_direccionAdm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_direccionAdmKeyPressed(evt);
            }
        });
        jPanel_CrearAdmVend.add(jFormattedTextField_direccionAdm);
        jFormattedTextField_direccionAdm.setBounds(160, 130, 168, 25);

        jButton_CrearAdministrador.setText("Aceptar");
        jButton_CrearAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearAdministradorActionPerformed(evt);
            }
        });
        jButton_CrearAdministrador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CrearAdministradorKeyPressed(evt);
            }
        });
        jPanel_CrearAdmVend.add(jButton_CrearAdministrador);
        jButton_CrearAdministrador.setBounds(150, 230, 71, 23);

        jButton_CancelarCrearCliente4.setText("Cancelar");
        jButton_CancelarCrearCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarCrearCliente4ActionPerformed(evt);
            }
        });
        jPanel_CrearAdmVend.add(jButton_CancelarCrearCliente4);
        jButton_CancelarCrearCliente4.setBounds(250, 230, 75, 23);

        jLabel_nombreCliente11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombreCliente11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente11.setText("Contrasena");
        jPanel_CrearAdmVend.add(jLabel_nombreCliente11);
        jLabel_nombreCliente11.setBounds(10, 70, 61, 23);

        jPasswordField_Adm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_AdmKeyPressed(evt);
            }
        });
        jPanel_CrearAdmVend.add(jPasswordField_Adm);
        jPasswordField_Adm.setBounds(160, 70, 168, 25);

        dateChooserCombo_CumpCrearVendAdm.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo_CumpCrearVendAdm.setCalendarBackground(new java.awt.Color(0, 51, 51));
    dateChooserCombo_CumpCrearVendAdm.setNothingAllowed(false);
    dateChooserCombo_CumpCrearVendAdm.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
    jPanel_CrearAdmVend.add(dateChooserCombo_CumpCrearVendAdm);
    dateChooserCombo_CumpCrearVendAdm.setBounds(160, 160, 168, 25);

    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setText("Tipo de Usuario:");
    jPanel_CrearAdmVend.add(jLabel9);
    jLabel9.setBounds(10, 190, 100, 23);

    buttonGroup.add(jRadioButton_Vendedor);
    jRadioButton_Vendedor.setForeground(new java.awt.Color(255, 255, 255));
    jRadioButton_Vendedor.setSelected(true);
    jRadioButton_Vendedor.setText("Vendedor");
    jRadioButton_Vendedor.setOpaque(false);
    jPanel_CrearAdmVend.add(jRadioButton_Vendedor);
    jRadioButton_Vendedor.setBounds(160, 190, 71, 23);

    buttonGroup.add(jRadioButton_Administrador);
    jRadioButton_Administrador.setForeground(new java.awt.Color(255, 255, 255));
    jRadioButton_Administrador.setText("Administrador");
    jRadioButton_Administrador.setOpaque(false);
    jPanel_CrearAdmVend.add(jRadioButton_Administrador);
    jRadioButton_Administrador.setBounds(240, 190, 91, 23);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setText("Crear usuario");
    jPanel_CrearAdmVend.add(jLabel1);
    jLabel1.setBounds(10, 10, 123, 22);

    jPanel_VerAdmVend.setBackground(new java.awt.Color(153, 153, 153));
    jPanel_VerAdmVend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel_VerAdmVend.setMaximumSize(new java.awt.Dimension(435, 290));
    jPanel_VerAdmVend.setMinimumSize(new java.awt.Dimension(435, 290));
    jPanel_VerAdmVend.setPreferredSize(new java.awt.Dimension(435, 290));
    jPanel_VerAdmVend.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            jPanel_VerAdmVendComponentShown(evt);
        }
    });
    jPanel_VerAdmVend.setLayout(null);
    jPanel_VerAdmVend.setSize(435, 290);

    jLabel_nombreCliente12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_nombreCliente12.setText("Nombre ");
    jPanel_VerAdmVend.add(jLabel_nombreCliente12);
    jLabel_nombreCliente12.setBounds(20, 60, 70, 23);

    jLabel_telefonoCliente8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_telefonoCliente8.setText("Telefono");
    jPanel_VerAdmVend.add(jLabel_telefonoCliente8);
    jLabel_telefonoCliente8.setBounds(20, 110, 105, 23);

    jLabel_direccionCliente8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_direccionCliente8.setText("Direccion");
    jPanel_VerAdmVend.add(jLabel_direccionCliente8);
    jLabel_direccionCliente8.setBounds(20, 160, 105, 23);

    jLabel_FechaCumpleanos8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_FechaCumpleanos8.setText("Fecha de Cumpleaños");
    jPanel_VerAdmVend.add(jLabel_FechaCumpleanos8);
    jLabel_FechaCumpleanos8.setBounds(20, 210, 120, 23);

    jButton_CrearCliente5.setText("Aceptar");
    jButton_CrearCliente5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_CrearCliente5ActionPerformed(evt);
        }
    });
    jButton_CrearCliente5.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jButton_CrearCliente5KeyPressed(evt);
        }
    });
    jPanel_VerAdmVend.add(jButton_CrearCliente5);
    jButton_CrearCliente5.setBounds(260, 250, 71, 23);

    jButton_CancelarCrearCliente5.setText("Cancelar");
    jButton_CancelarCrearCliente5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_CancelarCrearCliente5ActionPerformed(evt);
        }
    });
    jPanel_VerAdmVend.add(jButton_CancelarCrearCliente5);
    jButton_CancelarCrearCliente5.setBounds(340, 250, 75, 23);

    jLabel_DirreVerAdmVend.setBackground(new java.awt.Color(0, 51, 51));
    jLabel_DirreVerAdmVend.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_DirreVerAdmVend.setText("...");
    jPanel_VerAdmVend.add(jLabel_DirreVerAdmVend);
    jLabel_DirreVerAdmVend.setBounds(140, 160, 280, 23);

    jLabel_FechaCVerAdmVend.setBackground(new java.awt.Color(0, 51, 51));
    jLabel_FechaCVerAdmVend.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_FechaCVerAdmVend.setText("...");
    jPanel_VerAdmVend.add(jLabel_FechaCVerAdmVend);
    jLabel_FechaCVerAdmVend.setBounds(140, 210, 280, 23);

    jLabel_TeleVerAdmVend.setBackground(new java.awt.Color(0, 51, 51));
    jLabel_TeleVerAdmVend.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_TeleVerAdmVend.setText("...");
    jPanel_VerAdmVend.add(jLabel_TeleVerAdmVend);
    jLabel_TeleVerAdmVend.setBounds(140, 110, 280, 23);

    jLabel_NombreVerAdmVend.setBackground(new java.awt.Color(0, 51, 51));
    jLabel_NombreVerAdmVend.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_NombreVerAdmVend.setText("...");
    jPanel_VerAdmVend.add(jLabel_NombreVerAdmVend);
    jLabel_NombreVerAdmVend.setBounds(140, 60, 280, 23);

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("Ver usuario");
    jLabel2.setToolTipText("");
    jPanel_VerAdmVend.add(jLabel2);
    jLabel2.setBounds(10, 10, 104, 22);

    jPanel_ModifAdmVend.setBackground(new java.awt.Color(153, 153, 153));
    jPanel_ModifAdmVend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel_ModifAdmVend.setMaximumSize(new java.awt.Dimension(335, 240));
    jPanel_ModifAdmVend.setMinimumSize(new java.awt.Dimension(335, 240));
    jPanel_ModifAdmVend.setPreferredSize(new java.awt.Dimension(335, 240));
    jPanel_ModifAdmVend.addComponentListener(new java.awt.event.ComponentAdapter() {
        public void componentShown(java.awt.event.ComponentEvent evt) {
            jPanel_ModifAdmVendComponentShown(evt);
        }
    });
    jPanel_ModifAdmVend.setLayout(null);
    jPanel_ModifAdmVend.setSize(335, 240);

    jLabel_nombreCliente13.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_nombreCliente13.setText("Nombre");
    jPanel_ModifAdmVend.add(jLabel_nombreCliente13);
    jLabel_nombreCliente13.setBounds(20, 40, 50, 23);

    jLabel_telefonoCliente9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_telefonoCliente9.setText("Telefono");
    jPanel_ModifAdmVend.add(jLabel_telefonoCliente9);
    jLabel_telefonoCliente9.setBounds(20, 100, 105, 23);

    jLabel_direccionCliente9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_direccionCliente9.setText("Direccion");
    jPanel_ModifAdmVend.add(jLabel_direccionCliente9);
    jLabel_direccionCliente9.setBounds(20, 130, 105, 23);

    jLabel_FechaCumpleanos10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_FechaCumpleanos10.setText("Fecha de Cumpleanos");
    jPanel_ModifAdmVend.add(jLabel_FechaCumpleanos10);
    jLabel_FechaCumpleanos10.setBounds(20, 160, 120, 23);

    jFormattedTextField_Modifnombre.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jFormattedTextField_ModifnombreKeyPressed(evt);
        }
    });
    jPanel_ModifAdmVend.add(jFormattedTextField_Modifnombre);
    jFormattedTextField_Modifnombre.setBounds(140, 40, 168, 25);

    jFormattedTextField_Modiftelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    jFormattedTextField_Modiftelefono.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jFormattedTextField_ModiftelefonoKeyPressed(evt);
        }
    });
    jPanel_ModifAdmVend.add(jFormattedTextField_Modiftelefono);
    jFormattedTextField_Modiftelefono.setBounds(140, 100, 168, 25);

    jFormattedTextField_Modifdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jFormattedTextField_ModifdireccionKeyPressed(evt);
        }
    });
    jPanel_ModifAdmVend.add(jFormattedTextField_Modifdireccion);
    jFormattedTextField_Modifdireccion.setBounds(140, 130, 168, 25);

    jButton_ModifAdmVend.setText("Aceptar");
    jButton_ModifAdmVend.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_ModifAdmVendActionPerformed(evt);
        }
    });
    jButton_ModifAdmVend.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jButton_ModifAdmVendKeyPressed(evt);
        }
    });
    jPanel_ModifAdmVend.add(jButton_ModifAdmVend);
    jButton_ModifAdmVend.setBounds(160, 200, 71, 23);

    jButton_CancelarModifAdmVend.setText("Cancelar");
    jButton_CancelarModifAdmVend.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_CancelarModifAdmVendActionPerformed(evt);
        }
    });
    jPanel_ModifAdmVend.add(jButton_CancelarModifAdmVend);
    jButton_CancelarModifAdmVend.setBounds(240, 200, 75, 23);

    jLabel_nombreCliente14.setForeground(new java.awt.Color(255, 255, 255));
    jLabel_nombreCliente14.setText("Contrasena");
    jPanel_ModifAdmVend.add(jLabel_nombreCliente14);
    jLabel_nombreCliente14.setBounds(20, 70, 80, 23);
    jPanel_ModifAdmVend.add(jPasswordField_Modif);
    jPasswordField_Modif.setBounds(140, 70, 168, 25);

    dateChooserCombo_CumpModfVendAdm.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dateChooserCombo_CumpModfVendAdm.setCalendarBackground(new java.awt.Color(0, 51, 51));
dateChooserCombo_CumpModfVendAdm.setNothingAllowed(false);
dateChooserCombo_CumpModfVendAdm.setFormat(2);
dateChooserCombo_CumpModfVendAdm.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
jPanel_ModifAdmVend.add(dateChooserCombo_CumpModfVendAdm);
dateChooserCombo_CumpModfVendAdm.setBounds(140, 160, 168, 25);

jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
jLabel3.setForeground(new java.awt.Color(255, 255, 255));
jLabel3.setText("Modificar usuario");
jPanel_ModifAdmVend.add(jLabel3);
jLabel3.setBounds(10, 10, 157, 22);

setMaximumSize(new java.awt.Dimension(897, 477));
setMinimumSize(new java.awt.Dimension(760, 400));
setOpaque(false);
setPreferredSize(new java.awt.Dimension(760, 400));
setLayout(null);

jTable_Generica_AdmVend.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] {

    },
    new String [] {

    }
    ));
    jTable_Generica_AdmVend.setFillsViewportHeight(true);
    jTable_Generica_AdmVend.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable_Generica_AdmVendMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable_Generica_AdmVend);

    add(jScrollPane1);
    jScrollPane1.setBounds(0, 40, 760, 310);

    TextField_BuscadorVend.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TextField_BuscadorVendActionPerformed(evt);
        }
    });
    add(TextField_BuscadorVend);
    TextField_BuscadorVend.setBounds(50, 10, 270, 23);

    jLabel10.setText("Buscar");
    add(jLabel10);
    jLabel10.setBounds(10, 10, 32, 23);

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBtt.png"))); // NOI18N
    jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel4MouseClicked(evt);
        }
    });
    add(jLabel4);
    jLabel4.setBounds(20, 360, 40, 40);

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/editBtt.png"))); // NOI18N
    jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel5MouseClicked(evt);
        }
    });
    add(jLabel5);
    jLabel5.setBounds(90, 360, 40, 40);

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/trashBtt.png"))); // NOI18N
    jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel6MouseClicked(evt);
        }
    });
    add(jLabel6);
    jLabel6.setBounds(160, 360, 40, 40);

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/watchBtt.png"))); // NOI18N
    jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel7MouseClicked(evt);
        }
    });
    add(jLabel7);
    jLabel7.setBounds(230, 360, 40, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_Generica_AdmVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Generica_AdmVendMouseClicked
        if (evt.getClickCount() == 2) {
            //            this.jButton_AceptarBusqueda.doClick();
        }
    }//GEN-LAST:event_jTable_Generica_AdmVendMouseClicked

    private void jFormattedTextField_telefonoAdmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_telefonoAdmKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jFormattedTextField_telefonoAdm.transferFocus();
        }
    }//GEN-LAST:event_jFormattedTextField_telefonoAdmKeyPressed

    private void jFormattedTextField_direccionAdmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_direccionAdmKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jFormattedTextField_direccionAdm.transferFocus();
        }
    }//GEN-LAST:event_jFormattedTextField_direccionAdmKeyPressed

    private void jButton_CrearAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearAdministradorActionPerformed
        if (!"".equals(jFormattedTextField_nombreAdm.getText().trim())
                && !"".equals(jPasswordField_Adm.getText().trim())) {
            if (jRadioButton_Administrador.isSelected()) {
                crearPersona("Administrador");
            } else {
                crearPersona("Vendedor");
            }
            actualizarTabla();
            clearPanelCrear();
            jDialog_AdmiVend.dispose();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "Faltas datos de Usuario",
                    "Mensaje", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton_CrearAdministradorActionPerformed

    private void jButton_CrearAdministradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CrearAdministradorKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            // this.crearCliente();
        }
    }//GEN-LAST:event_jButton_CrearAdministradorKeyPressed

    private void jButton_CancelarCrearCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarCrearCliente4ActionPerformed
        clearPanelCrear();
        jDialog_AdmiVend.dispose();
    }//GEN-LAST:event_jButton_CancelarCrearCliente4ActionPerformed

    private void jButton_CrearCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearCliente5ActionPerformed
        clearVerAdmVendPanel();
        jDialog_AdmiVend.dispose();
    }//GEN-LAST:event_jButton_CrearCliente5ActionPerformed

    private void jButton_CrearCliente5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CrearCliente5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CrearCliente5KeyPressed

    private void jButton_CancelarCrearCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarCrearCliente5ActionPerformed
        clearVerAdmVendPanel();
        jDialog_AdmiVend.dispose();
    }//GEN-LAST:event_jButton_CancelarCrearCliente5ActionPerformed

    private void jDialog_AdmiVendWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog_AdmiVendWindowClosed
        clearVerAdmVendPanel();
        clearPanel();
        clearPanelCrear();
        jPanel_CrearAdmVend.setVisible(false);
        jPanel_VerAdmVend.setVisible(false);
    }//GEN-LAST:event_jDialog_AdmiVendWindowClosed

    private void jFormattedTextField_nombreAdmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_nombreAdmKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jFormattedTextField_nombreAdm.transferFocus();
        }
    }//GEN-LAST:event_jFormattedTextField_nombreAdmKeyPressed

    private void jPasswordField_AdmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_AdmKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jPasswordField_Adm.transferFocus();

        }
    }//GEN-LAST:event_jPasswordField_AdmKeyPressed

    private void TextField_BuscadorVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_BuscadorVendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_BuscadorVendActionPerformed

    private void jPanel_CrearAdmVendComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_CrearAdmVendComponentShown
        jPanel_VerAdmVend.setVisible(false);
    }//GEN-LAST:event_jPanel_CrearAdmVendComponentShown

    private void jPanel_VerAdmVendComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_VerAdmVendComponentShown
        jPanel_CrearAdmVend.setVisible(false);
    }//GEN-LAST:event_jPanel_VerAdmVendComponentShown

    private void jFormattedTextField_ModifnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModifnombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModifnombreKeyPressed

    private void jFormattedTextField_ModiftelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModiftelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModiftelefonoKeyPressed

    private void jFormattedTextField_ModifdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModifdireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModifdireccionKeyPressed

    private void jButton_ModifAdmVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifAdmVendActionPerformed
        try {
            if ("Administrador".equals(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 4).toString())) {
                modificarPersona("Administrador", jTable_Generica_AdmVend.
                        getValueAt(jTable_Generica_AdmVend.getSelectedRow(),
                                0).toString());
            } else {
                modificarPersona("Vendedor", jTable_Generica_AdmVend.
                        getValueAt(jTable_Generica_AdmVend.getSelectedRow(),
                                0).toString());
            }
            actualizarTabla();
        } catch (Exception e) {

        }
        clearPanel();
        jDialog_AdmiVend.dispose();
    }//GEN-LAST:event_jButton_ModifAdmVendActionPerformed

    private void jButton_ModifAdmVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ModifAdmVendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ModifAdmVendKeyPressed

    private void jButton_CancelarModifAdmVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarModifAdmVendActionPerformed
        clearPanel();
        jDialog_AdmiVend.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarModifAdmVendActionPerformed

    private void jPanel_ModifAdmVendComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel_ModifAdmVendComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel_ModifAdmVendComponentShown

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        showPanelOnDialog(jPanel_CrearAdmVend);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        cargarDatosModf();
        showPanelOnDialog(jPanel_ModifAdmVend);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            if ("Administrador".equals(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 4).toString())) {
                AdminBD.eliminarUsuario(jTable_Generica_AdmVend.getValueAt(
                        jTable_Generica_AdmVend.getSelectedRow(), 0).toString(),
                        "Administrador");

            } else {

                AdminBD.eliminarUsuario(jTable_Generica_AdmVend.getValueAt(
                        jTable_Generica_AdmVend.getSelectedRow(), 0).toString(),
                        "Vendedor");

            }
            actualizarTabla();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            jLabel_NombreVerAdmVend.setText(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 0).toString());
            jLabel_DirreVerAdmVend.setText(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 1).toString());
            jLabel_TeleVerAdmVend.setText(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 2).toString());
            jLabel_FechaCVerAdmVend.setText(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 3).toString());

        } catch (Exception e) {

        }
        
        showPanelOnDialog(jPanel_CrearAdmVend);
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_BuscadorVend;
    private javax.swing.ButtonGroup buttonGroup;
    private datechooser.beans.DateChooserCombo dateChooserCombo_CumpCrearVendAdm;
    private datechooser.beans.DateChooserCombo dateChooserCombo_CumpModfVendAdm;
    private javax.swing.JButton jButton_CancelarCrearCliente4;
    private javax.swing.JButton jButton_CancelarCrearCliente5;
    private javax.swing.JButton jButton_CancelarModifAdmVend;
    private javax.swing.JButton jButton_CrearAdministrador;
    private javax.swing.JButton jButton_CrearCliente5;
    private javax.swing.JButton jButton_ModifAdmVend;
    private javax.swing.JDialog jDialog_AdmiVend;
    private javax.swing.JFormattedTextField jFormattedTextField_Modifdireccion;
    private javax.swing.JFormattedTextField jFormattedTextField_Modifnombre;
    private javax.swing.JFormattedTextField jFormattedTextField_Modiftelefono;
    private javax.swing.JFormattedTextField jFormattedTextField_direccionAdm;
    private javax.swing.JFormattedTextField jFormattedTextField_nombreAdm;
    private javax.swing.JFormattedTextField jFormattedTextField_telefonoAdm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DirreVerAdmVend;
    private javax.swing.JLabel jLabel_FechaCVerAdmVend;
    private javax.swing.JLabel jLabel_FechaCumpleanos10;
    private javax.swing.JLabel jLabel_FechaCumpleanos7;
    private javax.swing.JLabel jLabel_FechaCumpleanos8;
    private javax.swing.JLabel jLabel_NombreVerAdmVend;
    private javax.swing.JLabel jLabel_TeleVerAdmVend;
    private javax.swing.JLabel jLabel_direccionCliente7;
    private javax.swing.JLabel jLabel_direccionCliente8;
    private javax.swing.JLabel jLabel_direccionCliente9;
    private javax.swing.JLabel jLabel_nombreCliente10;
    private javax.swing.JLabel jLabel_nombreCliente11;
    private javax.swing.JLabel jLabel_nombreCliente12;
    private javax.swing.JLabel jLabel_nombreCliente13;
    private javax.swing.JLabel jLabel_nombreCliente14;
    private javax.swing.JLabel jLabel_telefonoCliente7;
    private javax.swing.JLabel jLabel_telefonoCliente8;
    private javax.swing.JLabel jLabel_telefonoCliente9;
    private javax.swing.JPanel jPanel_CrearAdmVend;
    private javax.swing.JPanel jPanel_ModifAdmVend;
    private javax.swing.JPanel jPanel_VerAdmVend;
    private javax.swing.JPasswordField jPasswordField_Adm;
    private javax.swing.JTextField jPasswordField_Modif;
    private javax.swing.JRadioButton jRadioButton_Administrador;
    private javax.swing.JRadioButton jRadioButton_Vendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Generica_AdmVend;
    // End of variables declaration//GEN-END:variables

    private void crearPersona(String tipoUsuario) {
        String nombre = jFormattedTextField_nombreAdm.getText();
        String direccion = jFormattedTextField_direccionAdm.getText();
        String telefono = jFormattedTextField_telefonoAdm.getText();
        String fechaCumpleanos = dateF.format(
                dateChooserCombo_CumpCrearVendAdm.getSelectedDate().
                getTime());
        String clave = jPasswordField_Adm.getText().trim();
        if (fechaCumpleanos.equals("")) {
            fechaCumpleanos = null;
        }
        //si se crea la persona 
        if (AdminBD.insertarPersona(nombre, direccion, telefono,
                fechaCumpleanos)) {
            AdminBD.insertarUsuario(tipoUsuario, clave);
        }
    }

    private void modificarPersona(String tipoUsuario, String nombre) {
        String nuevoNombre = this.jFormattedTextField_Modifnombre.getText();
        String direccion = this.jFormattedTextField_Modifdireccion.getText();
        String telefono = this.jFormattedTextField_Modiftelefono.getText();
        String fechaCumpleanos = dateF.format(
                dateChooserCombo_CumpModfVendAdm.getSelectedDate().
                getTime());
        String clave = this.jPasswordField_Modif.getText().trim();
        if (fechaCumpleanos.equals("")) {
            fechaCumpleanos = null;
        }
        AdminBD.modificarUsuario(nombre, direccion, telefono,
                fechaCumpleanos, clave, tipoUsuario, nuevoNombre);
    }

    private boolean cargarDatosModf() {

        try {
            if ("Administrador".equals(jTable_Generica_AdmVend.getValueAt(
                    jTable_Generica_AdmVend.getSelectedRow(), 4).toString())) {

                AdminBD.ConsultarContrasena(jTable_Generica_AdmVend.getValueAt(
                        jTable_Generica_AdmVend.getSelectedRow(), 0).toString(),
                        "Administrador");
                jPasswordField_Modif.setText(AdminBD.getData()[0][0].toString());
            } else {

                AdminBD.ConsultarContrasena(jTable_Generica_AdmVend.getValueAt(
                        jTable_Generica_AdmVend.getSelectedRow(), 0).toString(),
                        "Vendedor");
                jPasswordField_Modif.setText(AdminBD.getData()[0][0].toString());
            }
            jFormattedTextField_Modifnombre.setText(jTable_Generica_AdmVend.
                    getValueAt(
                            jTable_Generica_AdmVend.getSelectedRow(), 0).toString());
            jFormattedTextField_Modifdireccion.setText(jTable_Generica_AdmVend.
                    getValueAt(
                            jTable_Generica_AdmVend.getSelectedRow(), 1).toString());
            jFormattedTextField_Modiftelefono.setText(jTable_Generica_AdmVend.
                    getValueAt(
                            jTable_Generica_AdmVend.getSelectedRow(), 2).toString());
            Calendar calendar = new GregorianCalendar();
            try {
                //Establecer fecha de cumpleanos
                Date date = dateFormat.parse(jTable_Generica_AdmVend.getValueAt(
                        jTable_Generica_AdmVend.getSelectedRow(), 3).toString());
                calendar.setTime(date);
                dateChooserCombo_CumpModfVendAdm.setSelectedDate(calendar);

            } catch (ParseException e) {
                //Si la fecha es nula pone fecha actual
                calendar.setTime(new Date());
                dateChooserCombo_CumpModfVendAdm.setSelectedDate(calendar);
            }

        } catch (Exception e) {

        }
        return false;
    }

    /**
     * Limpia los jFormattedTextField de panel modificar usuario
     */
    private void clearPanel() {
        jPasswordField_Modif.setText("");
        jFormattedTextField_Modifnombre.setText("");
        jFormattedTextField_Modifdireccion.setText("");
        jFormattedTextField_Modiftelefono.setText("");
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(new Date());
        dateChooserCombo_CumpModfVendAdm.setSelectedDate(calendar);
    }

    /**
     * Limpia los jFormattedTextField de panel Crear usuario
     */
    private void clearPanelCrear() {
        jFormattedTextField_nombreAdm.setText("");
        jFormattedTextField_direccionAdm.setText("");
        jFormattedTextField_telefonoAdm.setText("");
        jPasswordField_Adm.setText("");
        Calendar calendar = new GregorianCalendar();
        calendar.setTime(new Date());
        dateChooserCombo_CumpCrearVendAdm.setSelectedDate(calendar);

    }

    /**
     * Limpia los jLabel de ver vendedores y administradores
     */
    private void clearVerAdmVendPanel() {
        jLabel_NombreVerAdmVend.setText("");
        jLabel_DirreVerAdmVend.setText("");
        jLabel_TeleVerAdmVend.setText("");
        jLabel_FechaCVerAdmVend.setText("");

    }

    private void actualizarTabla() {
        AdminBD.consultarUsuarios();
        data = AdminBD.getData();
        String[] columnNames = AdminBD.getColumnNames();

        this.jTable_Generica_AdmVend.setModel(new MyTableModel_Generic(columnNames,
                data));
        //Crea el ordenador para la tabla generica
        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>(
                this.jTable_Generica_AdmVend.getModel());
        this.jTable_Generica_AdmVend.setRowSorter(ordenador);
        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
        qq.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        ordenador.setSortKeys(qq);
        jTable_Generica_AdmVend.requestFocus();
        jTable_Generica_AdmVend.changeSelection(0, 0, false, false);
        /**
         * Agrega el listener al JtextField del buscador *
         */
        this.TextField_BuscadorVend.getDocument().
                addDocumentListener(new ListenerBuscador(
                                this.TextField_BuscadorVend, ordenador));
    }
}
