/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;


import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author edward
 */
public final class Pan_Bodega extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Inventario
     */
    
    private static Pan_Bodega mPanelInventario=null;
    boolean ctrlPressed = false;
    boolean cPressed = false;
        
    public Pan_Bodega() {
        initComponents();
        personalizarTablaBodega();
         
    }
    
    public static Pan_Bodega getInstance(){
        if(mPanelInventario==null)
        {
            mPanelInventario=new Pan_Bodega();
        }
        
        return mPanelInventario;
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_VerProducto = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTextField_CodigoVerProducto = new javax.swing.JTextField();
        jLabel_Codigo2 = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jTextField_nombreVerProducto = new javax.swing.JTextField();
        jLabel_Precio2 = new javax.swing.JLabel();
        jTextField_PrecioVerProducto = new javax.swing.JTextField();
        jTextField_CostoVerProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel_Costo2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_DescripcionVerProducto = new javax.swing.JTextField();
        jTextField_CategoriaVerProducto = new javax.swing.JTextField();
        jDialog_ConfirmacionVerProducto = new javax.swing.JDialog();
        jTextField_IdProductoModificar1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable_verBodega = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField_busquedaBodega = new javax.swing.JTextField();
        jComboBox_categoriaBusquedaBodega = new javax.swing.JComboBox();
        bttWatch = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_Codigo2.setText("Codigo");

        jLabel_Nombre2.setText("Nombre");

        jLabel_Precio2.setText("Precio");

        jLabel_Costo2.setText("Costo");

        jLabel15.setText("Categoria");

        jLabel17.setText("Descripcion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel_Nombre2)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Precio2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_Costo2))
                                .addComponent(jLabel_Codigo2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_PrecioVerProducto)
                            .addComponent(jTextField_CostoVerProducto)
                            .addComponent(jTextField_CodigoVerProducto)
                            .addComponent(jTextField_nombreVerProducto)
                            .addComponent(jTextField_CategoriaVerProducto))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jTextField_DescripcionVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CodigoVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Codigo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nombreVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Nombre2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Precio2)
                    .addComponent(jTextField_PrecioVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_CostoVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Costo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_CategoriaVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_DescripcionVerProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog_VerProductoLayout = new javax.swing.GroupLayout(jDialog_VerProducto.getContentPane());
        jDialog_VerProducto.getContentPane().setLayout(jDialog_VerProductoLayout);
        jDialog_VerProductoLayout.setHorizontalGroup(
            jDialog_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_VerProductoLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jDialog_VerProductoLayout.setVerticalGroup(
            jDialog_VerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField_IdProductoModificar1.setText("idProducto");
        jTextField_IdProductoModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdProductoModificar1ActionPerformed(evt);
            }
        });
        jTextField_IdProductoModificar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdProductoModificar1KeyPressed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_ConfirmacionVerProductoLayout = new javax.swing.GroupLayout(jDialog_ConfirmacionVerProducto.getContentPane());
        jDialog_ConfirmacionVerProducto.getContentPane().setLayout(jDialog_ConfirmacionVerProductoLayout);
        jDialog_ConfirmacionVerProductoLayout.setHorizontalGroup(
            jDialog_ConfirmacionVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ConfirmacionVerProductoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_ConfirmacionVerProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_IdProductoModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jDialog_ConfirmacionVerProductoLayout.setVerticalGroup(
            jDialog_ConfirmacionVerProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_ConfirmacionVerProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_IdProductoModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(760, 400));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(760, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_verBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_verBodega.setFillsViewportHeight(true);
        jScrollPane7.setViewportView(jTable_verBodega);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 320));

        jLabel23.setText("Busqueda :");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, -1));
        add(jTextField_busquedaBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, 119, -1));

        jComboBox_categoriaBusquedaBodega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Descripcion", "Cantidad", "Precio" }));
        jComboBox_categoriaBusquedaBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaBusquedaBodegaActionPerformed(evt);
            }
        });
        add(jComboBox_categoriaBusquedaBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 0, -1, -1));

        bttWatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/watchBtt.png"))); // NOI18N
        bttWatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttWatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttWatchMouseClicked(evt);
            }
        });
        add(bttWatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_IdProductoModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdProductoModificar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        this.jDialog_ConfirmacionVerProducto.dispose();
        
       
       Direct_Control_BD mBD= Direct_Control_BD.getInstance();
       mBD.consultarProducto(this.jTextField_IdProductoModificar1.getText());
       String[] columnNames = mBD.getColumnNames();
       Object[][] data = mBD.getData();
       
       if(data.length==0){
           JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar"); 
       }
       else{
           
       this.jDialog_VerProducto.setSize(430,400);
       Pan_Bodega mPanel= Pan_Bodega.getInstance();
       this.jDialog_VerProducto.setLocation(mPanel.getLocation());
       this.jDialog_VerProducto.setVisible(true); 
       
       this.jTextField_nombreVerProducto.setText(data[0][0].toString());
       this.jTextField_nombreVerProducto.disable();
       this.jTextField_PrecioVerProducto.setText(data[0][1].toString());
       this.jTextField_PrecioVerProducto.disable();
       this.jTextField_CostoVerProducto.setText(data[0][2].toString());
       this.jTextField_CostoVerProducto.disable();
       
       String NombreCategoria = mBD.consultarNombreCategoriaXid(Integer.parseInt(data[0][3].toString()));
        if (data[0][4] != null) {
                this.jTextField_DescripcionVerProducto.setText(data[0][4].toString());
            }
        else{this.jTextField_DescripcionVerProducto.setText("No tiene descripcion");}
       
       this.jTextField_DescripcionVerProducto.disable();
       this.jTextField_CodigoVerProducto.setText(data[0][5].toString());
       this.jTextField_CodigoVerProducto.disable();
       
       this.jTextField_CategoriaVerProducto.setText(NombreCategoria);
       this.jTextField_CategoriaVerProducto.disable();
       
       
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_IdProductoModificar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jTextField_IdProductoModificar1.transferFocus();
        }
    }//GEN-LAST:event_jTextField_IdProductoModificar1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton3.doClick();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jComboBox_categoriaBusquedaBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaBusquedaBodegaActionPerformed
        this.agregarBuscador(this.jTable_verBodega,this.jTextField_busquedaBodega,this.jComboBox_categoriaBusquedaBodega.getSelectedIndex());
        this.jTextField_busquedaBodega.setText("");
        this.jTextField_busquedaBodega.requestFocusInWindow();
    }//GEN-LAST:event_jComboBox_categoriaBusquedaBodegaActionPerformed

    private void bttWatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttWatchMouseClicked
        this.verProdBodega();
    }//GEN-LAST:event_bttWatchMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bttWatch;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox_categoriaBusquedaBodega;
    private javax.swing.JDialog jDialog_ConfirmacionVerProducto;
    private javax.swing.JDialog jDialog_VerProducto;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel_Codigo2;
    private javax.swing.JLabel jLabel_Costo2;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Precio2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable_verBodega;
    private javax.swing.JTextField jTextField_CategoriaVerProducto;
    private javax.swing.JTextField jTextField_CodigoVerProducto;
    private javax.swing.JTextField jTextField_CostoVerProducto;
    private javax.swing.JTextField jTextField_DescripcionVerProducto;
    private javax.swing.JTextField jTextField_IdProductoModificar1;
    private javax.swing.JTextField jTextField_PrecioVerProducto;
    private javax.swing.JTextField jTextField_busquedaBodega;
    private javax.swing.JTextField jTextField_nombreVerProducto;
    // End of variables declaration//GEN-END:variables

    private void verEntrada(JTable table, String title) {
          int row = table.getSelectedRow();
            if (row >= 0) {
                VentanaDeInicio mVentana = VentanaDeInicio.getInstance();
                JPanel_verEntradaSalidaMercaderia panelVerMovimientoEntradaSalida = new JPanel_verEntradaSalidaMercaderia();
                mVentana.add(panelVerMovimientoEntradaSalida);
                panelVerMovimientoEntradaSalida.setSize(this.getSize());
                panelVerMovimientoEntradaSalida.setLocation(this.getLocation());
                mVentana.remove(this);
                panelVerMovimientoEntradaSalida.setVisible(true);
                mVentana.revalidate();
                mVentana.repaint();
                mVentana.setTitle(title);
                if(title.equals("Ver Salida de Mercaderia")){
                    panelVerMovimientoEntradaSalida.jLabel_tipoMov.setText("Salida de:");
                }
                Modelo_Facturacion model = (Modelo_Facturacion) table.getModel();
                panelVerMovimientoEntradaSalida.jLabel_NumerodeMovimiento.setText(model.getValueAt(row, 0).toString());
                panelVerMovimientoEntradaSalida.personalizarTablaVerMovimiento();
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "No se selecciono ninguna entrada de mercaderia",
                        "Alert!", JOptionPane.ERROR_MESSAGE);
            }
    }
    
    private void personalizarTablaBodega() {
        Direct_Control_BD AdministradorBD= Direct_Control_BD.getInstance();
        AdministradorBD.verBodega();
        String[] columnNames = {"Cod Producto", "Descripcion",
            "Cantidad", "Precio",
            "Costo", "Categoria"};
        Object[][] data = AdministradorBD.getData();
        //Crea la tabla generica para Facturas
        this.jTable_verBodega.setModel(new Modelo_Bodega(columnNames,data));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer
                ();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER );
        this.jTable_verBodega.getColumnModel().getColumn(0).setCellRenderer
                (centerRenderer);
        Modelo_Bodega model =(Modelo_Bodega)this.jTable_verBodega.getModel();
        //model.addRow(20);
        
        this.agregarBuscador(this.jTable_verBodega,this.jTextField_busquedaBodega,0);
}

    private void verProdBodega() {
        Modelo_Bodega model = (Modelo_Bodega) this.jTable_verBodega.getModel();
        int row = this.jTable_verBodega.getSelectedRow();
        if(row>0){
            String idProducto = model.getValueAt(row, 0).toString();
            this.jDialog_ConfirmacionVerProducto.setSize(200, 100);
            Pan_Bodega mPanel = Pan_Bodega.getInstance();
            this.jDialog_ConfirmacionVerProducto.setLocation(mPanel.getLocation());
            this.jTextField_IdProductoModificar1.setText(idProducto);
            this.jDialog_ConfirmacionVerProducto.setVisible(true);}
        else{
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agregarBuscador(JTable table, JTextField textfield, int columna) {
         //Crea el ordenador para la tabla generica
        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>
                (table.getModel());
        table.setRowSorter(ordenador);
        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
        qq.add(new RowSorter.SortKey(0,SortOrder.ASCENDING));
        ordenador.setSortKeys(qq);
        /**Agrega el listener al JtextField del buscador **/
        textfield.getDocument().addDocumentListener(new
                ListenerBuscador(textfield,ordenador,columna));
    }
    
     /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     *
     * @param numero
     * @return
     */
    private BigDecimal StringtoBigDecimal(String numero) {
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;

    }
    
    private void crearMovimiento(String detalle, BigDecimal precioProd, int movimiento) {
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.insertarmovimiento(detalle,movimiento,1,precioProd);
    }
    
    private void guardaProductoEnMovimiento(String idProducto, int idVersion, int cantidadMov, BigDecimal PrecioVenta) {
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        int idMovimiento= AdminBD.ObtenerUltimoidMovimiento();
        AdminBD.insertarProductoCantidadMovimiento(idProducto,idVersion,idMovimiento,cantidadMov,PrecioVenta);
    }


    
}
