/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;


import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author edward
 */
public final class Pan_Bodega extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Inventario
     */
    
    private static Pan_Bodega mPanelInventario=null;
    boolean ctrlPressed = false;
    boolean cPressed = false;
        
    public Pan_Bodega() {
        initComponents();
        personalizarTablaBodega();
         
    }
    
    public static Pan_Bodega getInstance(){
        if(mPanelInventario==null)
        {
            mPanelInventario=new Pan_Bodega();
        }
        
        return mPanelInventario;
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_VerProducto = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTextField_CodigoVerProducto = new javax.swing.JTextField();
        jLabel_Codigo2 = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jTextField_nombreVerProducto = new javax.swing.JTextField();
        jLabel_Precio2 = new javax.swing.JLabel();
        jTextField_PrecioVerProducto = new javax.swing.JTextField();
        jTextField_CostoVerProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel_Costo2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_DescripcionVerProducto = new javax.swing.JTextField();
        jTextField_CategoriaVerProducto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDialog_ConfirmacionVerProducto = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField_IdProductoModificar1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable_verBodega = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextField_busquedaBodega = new javax.swing.JTextField();
        jComboBox_categoriaBusquedaBodega = new javax.swing.JComboBox();
        bttWatch = new javax.swing.JLabel();

        jDialog_VerProducto.setUndecorated(true);
        jDialog_VerProducto.setResizable(false);
        jDialog_VerProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_VerProducto.setSize(310, 280);
        jDialog_VerProducto.setLocationRelativeTo(null);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);
        jPanel5.add(jTextField_CodigoVerProducto);
        jTextField_CodigoVerProducto.setBounds(80, 50, 210, 23);

        jLabel_Codigo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Codigo2.setText("Codigo");
        jPanel5.add(jLabel_Codigo2);
        jLabel_Codigo2.setBounds(10, 50, 40, 23);

        jLabel_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre2.setText("Nombre");
        jPanel5.add(jLabel_Nombre2);
        jLabel_Nombre2.setBounds(10, 80, 50, 23);
        jPanel5.add(jTextField_nombreVerProducto);
        jTextField_nombreVerProducto.setBounds(80, 80, 210, 23);

        jLabel_Precio2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Precio2.setText("Precio");
        jPanel5.add(jLabel_Precio2);
        jLabel_Precio2.setBounds(10, 110, 70, 23);
        jPanel5.add(jTextField_PrecioVerProducto);
        jTextField_PrecioVerProducto.setBounds(80, 110, 210, 23);
        jPanel5.add(jTextField_CostoVerProducto);
        jTextField_CostoVerProducto.setBounds(80, 140, 210, 23);
        jPanel5.add(jLabel14);
        jLabel14.setBounds(150, 153, 0, 0);

        jLabel_Costo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Costo2.setText("Costo");
        jPanel5.add(jLabel_Costo2);
        jLabel_Costo2.setBounds(10, 140, 28, 23);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Categoria");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 170, 60, 23);
        jPanel5.add(jLabel16);
        jLabel16.setBounds(410, 202, 0, 0);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Descripcion");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(10, 200, 60, 23);
        jPanel5.add(jTextField_DescripcionVerProducto);
        jTextField_DescripcionVerProducto.setBounds(80, 200, 210, 23);
        jPanel5.add(jTextField_CategoriaVerProducto);
        jTextField_CategoriaVerProducto.setBounds(80, 170, 210, 23);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ver Producto");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 10, 118, 22);

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(220, 240, 71, 23);

        jDialog_VerProducto.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 280));

        jDialog_ConfirmacionVerProducto.setUndecorated(true);
        jDialog_ConfirmacionVerProducto.setResizable(false);
        jDialog_ConfirmacionVerProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_ConfirmacionVerProducto.setSize(250, 110);
        jDialog_ConfirmacionVerProducto.setLocationRelativeTo(null);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ID del producto");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(10, 40, 90, 23);

        jTextField_IdProductoModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdProductoModificar1ActionPerformed(evt);
            }
        });
        jTextField_IdProductoModificar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdProductoModificar1KeyPressed(evt);
            }
        });
        jPanel7.add(jTextField_IdProductoModificar1);
        jTextField_IdProductoModificar1.setBounds(100, 40, 130, 23);

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(150, 70, 80, 23);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ver Producto");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(10, 10, 118, 22);

        jDialog_ConfirmacionVerProducto.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 110));

        setMinimumSize(new java.awt.Dimension(760, 400));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(760, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_verBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_verBodega.setFillsViewportHeight(true);
        jScrollPane7.setViewportView(jTable_verBodega);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 320));

        jLabel23.setText("Busqueda :");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, -1));
        add(jTextField_busquedaBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 0, 119, -1));

        jComboBox_categoriaBusquedaBodega.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Descripcion", "Cantidad", "Precio" }));
        jComboBox_categoriaBusquedaBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaBusquedaBodegaActionPerformed(evt);
            }
        });
        add(jComboBox_categoriaBusquedaBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 0, -1, -1));

        bttWatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/watchBtt.png"))); // NOI18N
        bttWatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttWatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttWatchMouseClicked(evt);
            }
        });
        add(bttWatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_categoriaBusquedaBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaBusquedaBodegaActionPerformed
        this.agregarBuscador(this.jTable_verBodega,this.jTextField_busquedaBodega,this.jComboBox_categoriaBusquedaBodega.getSelectedIndex());
        this.jTextField_busquedaBodega.setText("");
        this.jTextField_busquedaBodega.requestFocusInWindow();
    }//GEN-LAST:event_jComboBox_categoriaBusquedaBodegaActionPerformed

    private void bttWatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttWatchMouseClicked
        this.verProdBodega();
    }//GEN-LAST:event_bttWatchMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialog_VerProducto.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField_IdProductoModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdProductoModificar1ActionPerformed

    private void jTextField_IdProductoModificar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jTextField_IdProductoModificar1.transferFocus();
        }
    }//GEN-LAST:event_jTextField_IdProductoModificar1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.jDialog_ConfirmacionVerProducto.dispose();

        Direct_Control_BD mBD= Direct_Control_BD.getInstance();
        mBD.consultarProducto(this.jTextField_IdProductoModificar1.getText());
        String[] columnNames = mBD.getColumnNames();
        Object[][] data = mBD.getData();

        if(data.length==0){
            JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto",
                JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar");
        }
        else{

            Pan_Inventario mPanel= Pan_Inventario.getInstance();
            this.jDialog_VerProducto.setVisible(true);

            this.jTextField_nombreVerProducto.setText(data[0][0].toString());
            this.jTextField_nombreVerProducto.disable();
            this.jTextField_PrecioVerProducto.setText(data[0][1].toString());
            this.jTextField_PrecioVerProducto.disable();
            this.jTextField_CostoVerProducto.setText(data[0][2].toString());
            this.jTextField_CostoVerProducto.disable();

            String NombreCategoria = mBD.consultarNombreCategoriaXid(Integer.parseInt(data[0][3].toString()));
            if (data[0][4] != null) {
                this.jTextField_DescripcionVerProducto.setText(data[0][4].toString());
            }
            else{this.jTextField_DescripcionVerProducto.setText("No tiene descripcion");}

            this.jTextField_DescripcionVerProducto.disable();
            this.jTextField_CodigoVerProducto.setText(data[0][5].toString());
            this.jTextField_CodigoVerProducto.disable();

            this.jTextField_CategoriaVerProducto.setText(NombreCategoria);
            this.jTextField_CategoriaVerProducto.disable();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton3.doClick();
        }
    }//GEN-LAST:event_jButton3KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bttWatch;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox_categoriaBusquedaBodega;
    private javax.swing.JDialog jDialog_ConfirmacionVerProducto;
    private javax.swing.JDialog jDialog_VerProducto;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel_Codigo2;
    private javax.swing.JLabel jLabel_Costo2;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Precio2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable_verBodega;
    private javax.swing.JTextField jTextField_CategoriaVerProducto;
    private javax.swing.JTextField jTextField_CodigoVerProducto;
    private javax.swing.JTextField jTextField_CostoVerProducto;
    private javax.swing.JTextField jTextField_DescripcionVerProducto;
    private javax.swing.JTextField jTextField_IdProductoModificar1;
    private javax.swing.JTextField jTextField_PrecioVerProducto;
    private javax.swing.JTextField jTextField_busquedaBodega;
    private javax.swing.JTextField jTextField_nombreVerProducto;
    // End of variables declaration//GEN-END:variables
    
    public void personalizarTablaBodega() {
        Direct_Control_BD AdministradorBD= Direct_Control_BD.getInstance();
        AdministradorBD.verBodega();
        String[] columnNames = {"Cod Producto", "Descripcion",
            "Cantidad", "Precio",
            "Costo", "Categoria"};
        Object[][] data = AdministradorBD.getData();
        //Crea la tabla generica para Facturas
        this.jTable_verBodega.setModel(new Modelo_Bodega(columnNames,data));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer
                ();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER );
        this.jTable_verBodega.getColumnModel().getColumn(0).setCellRenderer
                (centerRenderer);
        Modelo_Bodega model =(Modelo_Bodega)this.jTable_verBodega.getModel();
        //model.addRow(20);
        
        this.agregarBuscador(this.jTable_verBodega,this.jTextField_busquedaBodega,0);
}

    private void verProdBodega() {
        Modelo_Bodega model = (Modelo_Bodega) this.jTable_verBodega.getModel();
        int row = this.jTable_verBodega.getSelectedRow();
        if(row>0){
            String idProducto = model.getValueAt(row, 0).toString();
            Pan_Bodega mPanel = Pan_Bodega.getInstance();
            this.jDialog_ConfirmacionVerProducto.setLocation(mPanel.getLocation());
            this.jTextField_IdProductoModificar1.setText(idProducto);
            this.jDialog_ConfirmacionVerProducto.setVisible(true);}
        else{
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void agregarBuscador(JTable table, JTextField textfield, int columna) {
         //Crea el ordenador para la tabla generica
        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>
                (table.getModel());
        table.setRowSorter(ordenador);
        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
        qq.add(new RowSorter.SortKey(0,SortOrder.ASCENDING));
        ordenador.setSortKeys(qq);
        /**Agrega el listener al JtextField del buscador **/
        textfield.getDocument().addDocumentListener(new
                ListenerBuscador(textfield,ordenador,columna));
    }
    
     /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     *
     * @param numero
     * @return
     */
    private BigDecimal StringtoBigDecimal(String numero) {
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;

    }
    
    private void crearMovimiento(String detalle, BigDecimal precioProd, int movimiento) {
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.insertarmovimiento(detalle,movimiento,1,precioProd);
    }
    
    private void guardaProductoEnMovimiento(String idProducto, int idVersion, int cantidadMov, BigDecimal PrecioVenta) {
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        int idMovimiento= AdminBD.ObtenerUltimoidMovimiento();
        AdminBD.insertarProductoCantidadMovimiento(idProducto,idVersion,idMovimiento,cantidadMov,PrecioVenta);
    }


    
}
