/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import db_managment.Direct_Control_BD;
import java.math.BigDecimal;
import java.math.MathContext;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Oscar Montes
 */
public class Pan_CerrarCaja extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_CerrarCaja
     */
    public Pan_CerrarCaja() {
        initComponents();
    }
    
    public void hideSaveButton(){
        saveBtt.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Cajero = new javax.swing.JLabel();
        jLabel_horaInicio = new javax.swing.JLabel();
        jLabel_horaCierre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField_totalContado = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField_totalVenta = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalTarjeta = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_VerCierre = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField_totalVentaConCaja = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        saveBtt = new javax.swing.JLabel();
        jFormattedTextField_totalContadoReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalTarjetaReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalVentaReportado = new javax.swing.JFormattedTextField();
        jFormattedTextField_totalVentaCajaReportado = new javax.swing.JFormattedTextField();
        jLabel_detalle = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 471));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 471));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Hora Inicio");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cajero");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Hora Cierre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel_Cajero.setText("Nombre Cajero");
        add(jLabel_Cajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel_horaInicio.setText("Hora Inicio");
        add(jLabel_horaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 154, -1));

        jLabel_horaCierre.setText("Hora Cierre");
        add(jLabel_horaCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 154, -1));

        jLabel4.setText("Total tarjeta");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 95, 20));

        jLabel5.setText("Total Contado");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, 17));

        jFormattedTextField_totalContado.setEditable(false);
        jFormattedTextField_totalContado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalContado.setText("0.00");
        add(jFormattedTextField_totalContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 151, -1));

        jLabel6.setText("Total Venta");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 128, 20));

        jFormattedTextField_totalVenta.setEditable(false);
        jFormattedTextField_totalVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVenta.setText("0.00");
        add(jFormattedTextField_totalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 151, -1));

        jFormattedTextField_totalTarjeta.setEditable(false);
        jFormattedTextField_totalTarjeta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalTarjeta.setText("0.00");
        add(jFormattedTextField_totalTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 151, -1));

        jTable_VerCierre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable_VerCierre);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 769, 175));

        jLabel7.setText("Total Venta + Monto Caja");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 142, 20));

        jFormattedTextField_totalVentaConCaja.setEditable(false);
        jFormattedTextField_totalVentaConCaja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVentaConCaja.setText("0.00");
        add(jFormattedTextField_totalVentaConCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 151, -1));

        jLabel8.setText("Total Contado Reportado");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 20));

        jLabel9.setText("Total Tarjeta  Reportado");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        jLabel10.setText("Total Venta Reportado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 20));

        jLabel11.setText("Total Venta + Monto Caja");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cerrar Caja");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        saveBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/saveBtt.png"))); // NOI18N
        saveBtt.setToolTipText("Aceptar y guardar cierre de caja");
        saveBtt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBttMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBttMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBttMouseExited(evt);
            }
        });
        add(saveBtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jFormattedTextField_totalContadoReportado.setEditable(false);
        jFormattedTextField_totalContadoReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalContadoReportado.setText("0.00");
        add(jFormattedTextField_totalContadoReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 136, -1));

        jFormattedTextField_totalTarjetaReportado.setEditable(false);
        jFormattedTextField_totalTarjetaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalTarjetaReportado.setText("0.00");
        jFormattedTextField_totalTarjetaReportado.setToolTipText("");
        add(jFormattedTextField_totalTarjetaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 136, -1));

        jFormattedTextField_totalVentaReportado.setEditable(false);
        jFormattedTextField_totalVentaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVentaReportado.setText("0.00");
        add(jFormattedTextField_totalVentaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 136, -1));

        jFormattedTextField_totalVentaCajaReportado.setEditable(false);
        jFormattedTextField_totalVentaCajaReportado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("C#,##0.00"))));
        jFormattedTextField_totalVentaCajaReportado.setText("0.00");
        add(jFormattedTextField_totalVentaCajaReportado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 136, -1));

        jLabel_detalle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_detalle.setText("Todo esta perfecto");
        add(jLabel_detalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 472, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel1/panelVF.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void saveBttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttMouseClicked
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        int idCierreVigente= AdminBD.obtenerultimoidCierre();
        String HoraCierre= this.jLabel_horaCierre.getText();
        BigDecimal totalTarjet = this.corregirDato(this.jFormattedTextField_totalTarjeta.getText());
        BigDecimal totalCont = this.corregirDato(this.jFormattedTextField_totalContado.getText());
        BigDecimal totalVendido = totalTarjet.add(totalCont);
        String observaciones= this.jLabel_detalle.getText();
        BigDecimal ReporteFinal= this.corregirDato(this.jFormattedTextField_totalVentaReportado.getText());
        BigDecimal totalTarjtReportado= this.corregirDato(this.jFormattedTextField_totalTarjetaReportado.getText());
        BigDecimal totalContReportado = this.corregirDato(this.jFormattedTextField_totalContadoReportado.getText());
        AdminBD.actualizarCierreDeCaja(HoraCierre, totalVendido, observaciones, ReporteFinal, totalCont, totalTarjet, totalContReportado, totalTarjtReportado, idCierreVigente);

        JF_Facturacion.getInstance().getPanelManager().back();
    }//GEN-LAST:event_saveBttMouseClicked

    private void saveBttMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttMouseEntered
        saveBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/saveBttOvr.png")));
    }//GEN-LAST:event_saveBttMouseEntered

    private void saveBttMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBttMouseExited
        saveBtt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/saveBtt.png")));
    }//GEN-LAST:event_saveBttMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JFormattedTextField jFormattedTextField_totalContado;
    javax.swing.JFormattedTextField jFormattedTextField_totalContadoReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalTarjeta;
    javax.swing.JFormattedTextField jFormattedTextField_totalTarjetaReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalVenta;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaCajaReportado;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaConCaja;
    javax.swing.JFormattedTextField jFormattedTextField_totalVentaReportado;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel4;
    javax.swing.JLabel jLabel5;
    javax.swing.JLabel jLabel6;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JLabel jLabel_Cajero;
    javax.swing.JLabel jLabel_detalle;
    javax.swing.JLabel jLabel_horaCierre;
    javax.swing.JLabel jLabel_horaInicio;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTable jTable_VerCierre;
    javax.swing.JLabel saveBtt;
    // End of variables declaration//GEN-END:variables

    void personalizarTablaCierre(BigDecimal totalcontadoreportado,BigDecimal totaltarjetareportado,BigDecimal totalventareportado,String Cajero,
        String fechaInicio,BigDecimal montoinicio) {
        this.jLabel_Cajero.setText(Cajero);
        this.jLabel_horaInicio.setText(fechaInicio);        
        String[] columnNames = {"Fecha","Concepto",
            "Num Fact","Tipo Pago","Monto"};
        List<Object[]> data = new ArrayList<Object[]>();      
        //Agrega el modelo a la factura
        Modelo_CierreCaja model=new Modelo_CierreCaja(columnNames,data);
        this.jTable_VerCierre.setModel(model);
        this.cargarListenerRenders();
        this.cargarFacturasCierre(model);
        this.cargarApartadoCreditosCierre(model);
        this.cargarDevolucionesCierre(model);
        BigDecimal totalTarjet = this.corregirDato(this.jFormattedTextField_totalTarjeta.getText());
        BigDecimal totalCont = this.corregirDato(this.jFormattedTextField_totalContado.getText());
        BigDecimal totalventaconcaja=totalTarjet.add(totalCont).add(montoinicio);
        this.jFormattedTextField_totalVenta.setValue(totalTarjet.add(totalCont));
        this.jFormattedTextField_totalVentaConCaja.setValue(totalventaconcaja);
        this.jFormattedTextField_totalContadoReportado.setValue(totalcontadoreportado);
        this.jFormattedTextField_totalTarjetaReportado.setValue(totaltarjetareportado);
        this.jFormattedTextField_totalVentaReportado.setValue(totalventareportado.subtract(montoinicio));
        this.jFormattedTextField_totalVentaCajaReportado.setValue(totalventareportado);
        if(totalventareportado.compareTo(totalventaconcaja)<0){
            this.jLabel_detalle.setText("Existe un faltante de: "+""+ totalventaconcaja.subtract(totalventareportado));
        }
        if(totalventareportado.compareTo(totalventaconcaja)>0){
            this.jLabel_detalle.setText("Existe un sobrante de: "+""+ totalventaconcaja.subtract(totalventareportado).abs());
        }
        /// Ordena la tabla con base a la fecha de la ultima compra
        RowSorter<Modelo_CierreCaja> sorter= new TableRowSorter<Modelo_CierreCaja>(model);
        this.jTable_VerCierre.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.DESCENDING));
        sorter.setSortKeys(sortKeys);
        model.addRow(20);
    
        
        //this.jTable_VerCierre.setAutoCreateRowSorter(true);
        
    }
    /**
     * Este metodo permite corregir el dato que tiene el signo de C y ademas que
     * puede tener comas ya que el tipo Decimal en la base solo puede tener
     * puntos y no comas.
     *
     * @param Dato
     * @return
     */
    private BigDecimal corregirDato(String Dato) {
        String datoAcorregir = Dato.replace("C", "");
        DecimalFormat decimalformat = (DecimalFormat) NumberFormat.getInstance();
        decimalformat.setParseBigDecimal(true);
        BigDecimal DatoCorregido = null;
        try {
            DatoCorregido = (BigDecimal) decimalformat.parseObject(datoAcorregir);
        } catch (ParseException ex) {
            Logger.getLogger(MyTableModelListener_FACT.class.getName()).log(Level.SEVERE, null, ex);
        }
        return DatoCorregido;

    }
    private void cargarFacturasCierre(Modelo_CierreCaja model) {
       
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierreFacturasContado(this.jLabel_horaInicio.getText(),this.jLabel_horaCierre.getText());
        Object[][] InfoFactsContadoCierre = AdminBD.getData();
        int numFilas = InfoFactsContadoCierre.length;
        for (int row = 0; row < numFilas; row++) {
            model.addRow(1);
            Object[] infofactscontado= InfoFactsContadoCierre[row];
            String Fecha= infofactscontado[0].toString();
            String Concepto= infofactscontado[1].toString();
            int NumFact = Integer.parseInt(infofactscontado[2].toString());
            String TipoPago=infofactscontado[3].toString();
            BigDecimal monto= this.StringtoBigDecimal(infofactscontado[4].toString());
            model.setValueAt(Fecha, row, 0);
            model.setValueAt(Concepto, row, 1);
            model.setValueAt(NumFact, row, 2);
            model.setValueAt(TipoPago, row, 3);
            model.setValueAt(monto, row, 4);
            
            
            }
    
    }
    private void cargarApartadoCreditosCierre(Modelo_CierreCaja model) {
       
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierreApartadosCreditos(this.jLabel_horaInicio.getText(),this.jLabel_horaCierre.getText());
        Object[][] InfoApartadoCreditosCierre = AdminBD.getData();
        int numFilasTablas = model.getRowCount();
        int numFilas= InfoApartadoCreditosCierre.length;
        for (int row = 0; row < numFilas; row++) {
            model.addRow(1);
            Object[] infoapscreditos= InfoApartadoCreditosCierre[row];
            String Fecha= infoapscreditos[0].toString();
            String Concepto= infoapscreditos[1].toString();
            int NumFact = Integer.parseInt(infoapscreditos[2].toString());
            String TipoPago=infoapscreditos[3].toString();
            BigDecimal monto= this.StringtoBigDecimal(infoapscreditos[4].toString());
            model.setValueAt(Fecha, numFilasTablas+row, 0);
            model.setValueAt(Concepto, numFilasTablas+row, 1);
            model.setValueAt(NumFact, numFilasTablas+row, 2);
            model.setValueAt(TipoPago, numFilasTablas+row, 3);
            model.setValueAt(monto, numFilasTablas+row, 4);
            
            
            }
    
    }
     private void cargarDevolucionesCierre(Modelo_CierreCaja model) {
       
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.verCierreDevoluciones(this.jLabel_horaInicio.getText(),this.jLabel_horaCierre.getText());
        Object[][] InfoDevCierre = AdminBD.getData();
        int numFilasTablas = model.getRowCount();
        int numFilas= InfoDevCierre.length;
        for (int row = 0; row < numFilas; row++) {
            model.addRow(1);
            Object[] infodev= InfoDevCierre[row];
            String Fecha= infodev[0].toString();
            String Concepto= infodev[1].toString();
            int NumFact = Integer.parseInt(infodev[2].toString());
            String TipoPago=infodev[3].toString();
            BigDecimal monto= this.StringtoBigDecimal(infodev[4].toString());
            model.setValueAt(Fecha, numFilasTablas+row, 0);
            model.setValueAt(Concepto, numFilasTablas+row, 1);
            model.setValueAt(NumFact, numFilasTablas+row, 2);
            model.setValueAt(TipoPago, numFilasTablas+row, 3);
            model.setValueAt(monto.negate(), numFilasTablas+row, 4);
            
            
            }
    
    }
    private void cargarListenerRenders() {
        //AGREGA EL LISTENER QUE PERMITE HACER TODOS LOS EVENTOS DENTRO DE LA 
        //TABLA DE VER CIERRE //IMPORTANTE ESTOS EVENTOS ESTAN EN LA CLASE DE
        //MY ListenerCierreDeCaja EN el metodo: tableChanged(TableModelEvent e)
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        this.jTable_VerCierre.getModel().addTableModelListener(new ListenerCierreCaja(this.jTable_VerCierre,this.jFormattedTextField_totalTarjeta,AdminBD,this.jFormattedTextField_totalContado));
           //Costumisando Precio y Cantidad (Solo van a permitir numeros)
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        this.jTable_VerCierre.getColumnModel().getColumn(2).
                setCellRenderer(rightRenderer);
        this.jTable_VerCierre.getColumnModel().getColumn(3).
                setCellRenderer(rightRenderer);
        this.jTable_VerCierre.getColumnModel().getColumn(4).
                setCellRenderer(new CurrencyRender());
        
    
    }

 /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     * @param numero
     * @return 
     */
    private BigDecimal StringtoBigDecimal(String numero){
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;
    
    }

    private void regresarVentanaPrincipal() {
        VentanaDeInicio mVentana= VentanaDeInicio.getInstance();
        mVentana.remove(this);
        mVentana.revalidate();
        mVentana.repaint();
        mVentana.setTitle("Joe");
        mVentana.add(mVentana.jPanel_VentanaPrincipal);
        mVentana.jPanel_VentanaPrincipal.setVisible(true);    
    }
    
}

