/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;


import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AbstractDocument;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author edward
 */
public final class Pan_Inventario extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_Inventario
     */
    
    private static Pan_Inventario mPanelInventario=null;
    boolean ctrlPressed = false;
    boolean cPressed = false;
        
    public Pan_Inventario() {
        initComponents();
        personalizarTablaInventario();
    }
    
    public static Pan_Inventario getInstance(){
        if(mPanelInventario==null)
        {
            mPanelInventario=new Pan_Inventario();
        }
        
        return mPanelInventario;
        
        
    }
    
       
    public void personalizarTablaInventario(){
      Direct_Control_BD AdministradorBD= Direct_Control_BD.getInstance();
        AdministradorBD.verInventario();
        String[] columnNames = AdministradorBD.getColumnNames();
        Object[][] data = AdministradorBD.getData();
        //Crea la tabla generica para Facturas
        
        this.jTable_Inventario.setModel(new Modelo_Inventario(columnNames,data));
        //Alinea la primer columna de esta tabla hacia el centro
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer
                ();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER );
        this.jTable_Inventario.getColumnModel().getColumn(0).setCellRenderer
                (centerRenderer);
        this.agregarBuscador(this.jTable_Inventario,this.jTextField_busquedaInventario,0);
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CrearProducto = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTextField_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Cantidad = new javax.swing.JTextField();
        jButton_CrearProducto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_CategoriaCrearProducto = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_CostoCrearProducto = new javax.swing.JTextField();
        jTextArea_DescripcionCrearProducto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField_Precio = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jDialog_EliminarProducto = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTextField_IdProducto = new javax.swing.JTextField();
        jButton_EliminarProducto = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDialog_ModificarProducto = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTextField_CodigoProducto = new javax.swing.JTextField();
        jLabel_Codigo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_nombre1 = new javax.swing.JTextField();
        jLabel_Precio = new javax.swing.JLabel();
        jTextField_Precio1 = new javax.swing.JTextField();
        jTextField_Costo = new javax.swing.JTextField();
        jButton_CrearProducto1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Costo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Categorias = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton_CrearCategoria = new javax.swing.JButton();
        jTextField_Descripcion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jDialog_ConfirmacionModificacionProducto = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jTextField_IdProductoModificar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jDialog_CrearCategoria = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_NombreCategoria = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jDialog_VerProducto = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTextField_CodigoVerProducto = new javax.swing.JTextField();
        jLabel_Codigo2 = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jTextField_nombreVerProducto = new javax.swing.JTextField();
        jLabel_Precio2 = new javax.swing.JLabel();
        jTextField_PrecioVerProducto = new javax.swing.JTextField();
        jTextField_CostoVerProducto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel_Costo2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_DescripcionVerProducto = new javax.swing.JTextField();
        jTextField_CategoriaVerProducto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDialog_ConfirmacionVerProducto = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField_IdProductoModificar1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_Inventario = new javax.swing.JTable();
        jComboBox_categoriaBusquedaInventario = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jTextField_busquedaInventario = new javax.swing.JTextField();
        bttAdd = new javax.swing.JLabel();
        bttWatch = new javax.swing.JLabel();
        bttEdit = new javax.swing.JLabel();
        bttErase = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        jDialog_CrearProducto.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog_CrearProducto.setMinimumSize(new java.awt.Dimension(390, 358));
        jDialog_CrearProducto.setUndecorated(true);
        jDialog_CrearProducto.setResizable(false);
        jDialog_CrearProducto.setSize(390, 358);
        jDialog_CrearProducto.setLocationRelativeTo(null);
        jDialog_CrearProducto.getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jTextField_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_codigoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextField_codigo);
        jTextField_codigo.setBounds(121, 49, 258, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo del Producto");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(11, 52, 96, 23);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del Producto");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(11, 90, 106, 23);

        jTextField_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreKeyTyped(evt);
            }
        });
        jPanel2.add(jTextField_nombre);
        jTextField_nombre.setBounds(120, 90, 258, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Precio del Producto");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 130, 106, 23);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad del Producto");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 170, 106, 23);

        jTextField_Cantidad.setText("0");
        jTextField_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CantidadKeyTyped(evt);
            }
        });
        jPanel2.add(jTextField_Cantidad);
        jTextField_Cantidad.setBounds(120, 170, 258, 23);

        jButton_CrearProducto.setText("Aceptar");
        jButton_CrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearProductoActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_CrearProducto);
        jButton_CrearProducto.setBounds(220, 320, 71, 23);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Categoria");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 210, 47, 23);

        jComboBox_CategoriaCrearProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_CategoriaCrearProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox_CategoriaCrearProductoFocusGained(evt);
            }
        });
        jComboBox_CategoriaCrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox_CategoriaCrearProductoKeyTyped(evt);
            }
        });
        jPanel2.add(jComboBox_CategoriaCrearProducto);
        jComboBox_CategoriaCrearProducto.setBounds(120, 210, 56, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descripcion");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 280, 54, 23);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Costo");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 240, 28, 23);

        jTextField_CostoCrearProducto.setText("0.00");
        jTextField_CostoCrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CostoCrearProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CostoCrearProductoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextField_CostoCrearProducto);
        jTextField_CostoCrearProducto.setBounds(120, 240, 258, 23);

        jTextArea_DescripcionCrearProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_DescripcionCrearProductoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextArea_DescripcionCrearProducto);
        jTextArea_DescripcionCrearProducto.setBounds(120, 280, 258, 23);

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(300, 320, 75, 23);

        jTextField_Precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jTextField_Precio.setText("0.00");
        jTextField_Precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_PrecioFocusGained(evt);
            }
        });
        jTextField_Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_PrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PrecioKeyTyped(evt);
            }
        });
        jPanel2.add(jTextField_Precio);
        jTextField_Precio.setBounds(120, 130, 258, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Crear Producto");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(11, 9, 137, 22);

        jDialog_CrearProducto.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 390, 358);

        jDialog_EliminarProducto.setUndecorated(true);
        jDialog_EliminarProducto.setResizable(false);
        jDialog_EliminarProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_EliminarProducto.setSize(240, 110);
        jDialog_EliminarProducto.setLocationRelativeTo(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jTextField_IdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_IdProducto);
        jTextField_IdProducto.setBounds(90, 40, 130, 23);

        jButton_EliminarProducto.setText("Eliminar");
        jButton_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EliminarProducto);
        jButton_EliminarProducto.setBounds(150, 70, 69, 23);

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ID del producto");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 40, 74, 23);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Eliminar Producto");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 10, 161, 22);

        jDialog_EliminarProducto.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 110));

        jDialog_ModificarProducto.setUndecorated(true);
        jDialog_ModificarProducto.setResizable(false);
        jDialog_ModificarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDialog_ModificarProductoKeyPressed(evt);
            }
        });
        jDialog_ModificarProducto.getContentPane().setLayout(null);
        jDialog_ModificarProducto.setSize(440, 270);
        jDialog_ModificarProducto.setLocationRelativeTo(null);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jTextField_CodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CodigoProductoKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_CodigoProducto);
        jTextField_CodigoProducto.setBounds(70, 80, 355, 23);

        jLabel_Codigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Codigo.setText("Codigo");
        jPanel3.add(jLabel_Codigo);
        jLabel_Codigo.setBounds(10, 80, 33, 23);

        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Nombre");
        jPanel3.add(jLabel_Nombre);
        jLabel_Nombre.setBounds(10, 110, 37, 23);

        jTextField_nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombre1KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_nombre1);
        jTextField_nombre1.setBounds(70, 110, 355, 23);

        jLabel_Precio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Precio.setText("Precio");
        jPanel3.add(jLabel_Precio);
        jLabel_Precio.setBounds(10, 140, 56, 23);

        jTextField_Precio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Precio1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Precio1KeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_Precio1);
        jTextField_Precio1.setBounds(70, 140, 355, 23);

        jTextField_Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_CostoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_CostoKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_Costo);
        jTextField_Costo.setBounds(70, 170, 355, 23);

        jButton_CrearProducto1.setText("Aceptar");
        jButton_CrearProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearProducto1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_CrearProducto1);
        jButton_CrearProducto1.setBounds(350, 230, 71, 23);
        jPanel3.add(jLabel9);
        jLabel9.setBounds(150, 286, 0, 0);

        jLabel_Costo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Costo.setText("Costo");
        jPanel3.add(jLabel_Costo);
        jLabel_Costo.setBounds(10, 170, 28, 23);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 50, 47, 23);

        jComboBox_Categorias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Categorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jComboBox_CategoriasKeyTyped(evt);
            }
        });
        jPanel3.add(jComboBox_Categorias);
        jComboBox_Categorias.setBounds(70, 50, 110, 23);
        jPanel3.add(jLabel6);
        jLabel6.setBounds(418, 338, 0, 0);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Descripcion");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 200, 54, 23);

        jButton_CrearCategoria.setText("Nueva");
        jButton_CrearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearCategoriaActionPerformed(evt);
            }
        });
        jButton_CrearCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton_CrearCategoriaFocusGained(evt);
            }
        });
        jPanel3.add(jButton_CrearCategoria);
        jButton_CrearCategoria.setBounds(190, 50, 63, 23);

        jTextField_Descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DescripcionKeyTyped(evt);
            }
        });
        jPanel3.add(jTextField_Descripcion);
        jTextField_Descripcion.setBounds(70, 200, 355, 23);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Modificar Producto");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 10, 171, 22);

        jDialog_ModificarProducto.getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 440, 270);

        jDialog_ConfirmacionModificacionProducto.setUndecorated(true);
        jDialog_ConfirmacionModificacionProducto.setResizable(false);
        jDialog_ConfirmacionModificacionProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_ConfirmacionModificacionProducto.setSize(240, 110);
        jDialog_ConfirmacionModificacionProducto.setLocationRelativeTo(null);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jTextField_IdProductoModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdProductoModificarKeyPressed(evt);
            }
        });
        jPanel4.add(jTextField_IdProductoModificar);
        jTextField_IdProductoModificar.setBounds(90, 40, 130, 23);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(140, 70, 80, 23);

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ID del producto");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 40, 74, 23);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Modificar Producto");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 10, 171, 22);

        jDialog_ConfirmacionModificacionProducto.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 110));

        jDialog_CrearCategoria.setUndecorated(true);
        jDialog_CrearCategoria.setResizable(false);
        jDialog_CrearCategoria.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_CrearCategoria.setSize(270, 120);
        jDialog_CrearCategoria.setLocationRelativeTo(null);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre");
        jPanel6.add(jLabel8);
        jLabel8.setBounds(20, 50, 37, 23);
        jPanel6.add(jTextField_NombreCategoria);
        jTextField_NombreCategoria.setBounds(70, 50, 190, 23);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(190, 90, 71, 23);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Nueva Categoría");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(10, 10, 150, 22);

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(110, 90, 75, 23);

        jDialog_CrearCategoria.getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 120));

        jDialog_VerProducto.setUndecorated(true);
        jDialog_VerProducto.setResizable(false);
        jDialog_VerProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_VerProducto.setSize(310, 280);
        jDialog_VerProducto.setLocationRelativeTo(null);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);
        jPanel5.add(jTextField_CodigoVerProducto);
        jTextField_CodigoVerProducto.setBounds(80, 50, 210, 23);

        jLabel_Codigo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Codigo2.setText("Codigo");
        jPanel5.add(jLabel_Codigo2);
        jLabel_Codigo2.setBounds(10, 50, 33, 23);

        jLabel_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre2.setText("Nombre");
        jPanel5.add(jLabel_Nombre2);
        jLabel_Nombre2.setBounds(10, 80, 37, 23);
        jPanel5.add(jTextField_nombreVerProducto);
        jTextField_nombreVerProducto.setBounds(80, 80, 210, 23);

        jLabel_Precio2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Precio2.setText("Precio");
        jPanel5.add(jLabel_Precio2);
        jLabel_Precio2.setBounds(10, 110, 56, 23);
        jPanel5.add(jTextField_PrecioVerProducto);
        jTextField_PrecioVerProducto.setBounds(80, 110, 210, 23);
        jPanel5.add(jTextField_CostoVerProducto);
        jTextField_CostoVerProducto.setBounds(80, 140, 210, 23);
        jPanel5.add(jLabel14);
        jLabel14.setBounds(150, 153, 0, 0);

        jLabel_Costo2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Costo2.setText("Costo");
        jPanel5.add(jLabel_Costo2);
        jLabel_Costo2.setBounds(10, 140, 28, 23);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Categoria");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 170, 47, 23);
        jPanel5.add(jLabel16);
        jLabel16.setBounds(410, 202, 0, 0);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Descripcion");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(10, 200, 54, 23);
        jPanel5.add(jTextField_DescripcionVerProducto);
        jTextField_DescripcionVerProducto.setBounds(80, 200, 210, 23);
        jPanel5.add(jTextField_CategoriaVerProducto);
        jTextField_CategoriaVerProducto.setBounds(80, 170, 210, 23);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ver Producto");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(10, 10, 118, 22);

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(220, 240, 71, 23);

        jDialog_VerProducto.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 280));

        jDialog_ConfirmacionVerProducto.setUndecorated(true);
        jDialog_ConfirmacionVerProducto.setResizable(false);
        jDialog_ConfirmacionVerProducto.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jDialog_ConfirmacionVerProducto.setSize(250, 110);
        jDialog_ConfirmacionVerProducto.setLocationRelativeTo(null);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ID del producto");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(10, 40, 74, 23);

        jTextField_IdProductoModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IdProductoModificar1ActionPerformed(evt);
            }
        });
        jTextField_IdProductoModificar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_IdProductoModificar1KeyPressed(evt);
            }
        });
        jPanel7.add(jTextField_IdProductoModificar1);
        jTextField_IdProductoModificar1.setBounds(90, 40, 140, 23);

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(150, 70, 80, 23);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ver Producto");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(10, 10, 118, 22);

        jDialog_ConfirmacionVerProducto.getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 110));

        setMinimumSize(new java.awt.Dimension(760, 400));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(760, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Inventario.setFillsViewportHeight(true);
        jScrollPane5.setViewportView(jTable_Inventario);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 760, 320));

        jComboBox_categoriaBusquedaInventario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Descripcion", "Cantidad", "Precio", "Costo", "Categoria" }));
        jComboBox_categoriaBusquedaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_categoriaBusquedaInventarioActionPerformed(evt);
            }
        });
        add(jComboBox_categoriaBusquedaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Busqueda :");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));
        add(jTextField_busquedaInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 116, -1));

        bttAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBtt.png"))); // NOI18N
        bttAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttAddMouseClicked(evt);
            }
        });
        add(bttAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        bttWatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/watchBtt.png"))); // NOI18N
        bttWatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttWatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttWatchMouseClicked(evt);
            }
        });
        add(bttWatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        bttEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/editBtt.png"))); // NOI18N
        bttEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttEditMouseClicked(evt);
            }
        });
        add(bttEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        bttErase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/trashBtt.png"))); // NOI18N
        bttErase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttErase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttEraseMouseClicked(evt);
            }
        });
        add(bttErase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/labelsBtt.png"))); // NOI18N
        jLabel28.setToolTipText("");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
//String idProducto, String nombre, int precio,
            //int costo, String fechaCreacion, String estado, String Descripcion,
            //int idCategoria
    private void jButton_CrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearProductoActionPerformed
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        BigDecimal Precio = this.StringtoBigDecimal(this.jTextField_Precio.getText().toString());
        String codigo = this.jTextField_codigo.getText();
        if(codigo.equals("")){
            
             JOptionPane.showMessageDialog(
                    null,
                    "Por favor ingrese un codigo",
                    "Alert!", JOptionPane.ERROR_MESSAGE);
             return;
        
        }
        if(this.jTextField_nombre.getText().equals("")){
            
             JOptionPane.showMessageDialog(
                    null,
                    "Por favor ingrese un nombre para el producto",
                    "Alert!", JOptionPane.ERROR_MESSAGE);
             return;
        
        }
        if(AdminBD.verSiExisteCod(codigo)){
            JOptionPane.showMessageDialog(
                    null,
                    "Por favor ingrese un codigo diferente para el producto.\n"
                            + "Ya existe ese codigo para otro producto",
                    "Alert!", JOptionPane.ERROR_MESSAGE);
            this.jTextField_codigo.setText("");
            this.jTextField_codigo.requestFocusInWindow();
             return;
        
        }
        
        try {
            int idCategoria = AdminBD.consultarIdCategoriaXNombre(this.jComboBox_CategoriaCrearProducto.getSelectedItem().toString());
            String Descripcion = this.jTextArea_DescripcionCrearProducto.getText();
            String Nombre = this.jTextField_nombre.getText();
            BigDecimal Costo = this.StringtoBigDecimal(this.jTextField_CostoCrearProducto.getText());
            int cantidad=Integer.parseInt(this.jTextField_Cantidad.getText());
            AdminBD.crearProducto(codigo, Nombre, Precio, Costo, dateFormat.format(date), "A", Descripcion, idCategoria);
            this.jTextField_Cantidad.setText("0");
            this.jTextField_Precio.setText("0.00");
            this.jTextField_CostoCrearProducto.setText("0.00");
            this.jTextField_codigo.setText("");
            this.jTextField_nombre.setText("");
            this.jTextArea_DescripcionCrearProducto.setText("");
            this.jDialog_CrearProducto.dispose();
            this.crearMovimiento("Creacion Producto",Precio,1);
            int idVersion= AdminBD.veridVersionActivaProductoPorCodigo(codigo);
            this.guardaProductoEnMovimiento(codigo, idVersion, cantidad, Precio);
            personalizarTablaInventario();

        } catch (NumberFormatException exc) {
            JOptionPane.showOptionDialog(this, "Faltan datos necesarios", "Error Producto",
                    JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "}, "Cancelar");
        }
             
    }//GEN-LAST:event_jButton_CrearProductoActionPerformed

    private void jButton_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarProductoActionPerformed
       Direct_Control_BD mBD= Direct_Control_BD.getInstance();
       
       mBD.consultarProducto(this.jTextField_IdProducto.getText());
       
       Object[][] data = mBD.getData();
       if(data.length==0)
       {
           JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar"); 
       }
       else{
  
       mBD.eliminarProducto(this.jTextField_IdProducto.getText());
       this.jTextField_IdProducto.setText("          ");
       this.jDialog_EliminarProducto.dispose();
       personalizarTablaInventario();
       }
       
       
    }//GEN-LAST:event_jButton_EliminarProductoActionPerformed

    private void jTextField_IdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdProductoActionPerformed
       
    private void jButton_CrearProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearProducto1ActionPerformed
        try {
            Direct_Control_BD mBD = Direct_Control_BD.getInstance();
            BigDecimal Precio = this.StringtoBigDecimal(this.jTextField_Precio1.getText());
            BigDecimal Costo = this.StringtoBigDecimal(this.jTextField_Costo.getText());
            int IdCategoria = mBD.consultarIdCategoriaXNombre(this.jComboBox_Categorias.getSelectedItem().toString());
            mBD.modificarProducto(this.jTextField_CodigoProducto.getText(),
                    this.jTextField_nombre1.getText(), Precio,
                    IdCategoria, Costo,
                    this.jTextField_Descripcion.getText());

            this.jDialog_ModificarProducto.dispose();
            personalizarTablaInventario();
        } catch (NumberFormatException exc) {
            JOptionPane.showOptionDialog(this, "El precio no es valido", "Error Producto",
                    JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "}, "Cancelar");
        }
    }//GEN-LAST:event_jButton_CrearProducto1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jDialog_ConfirmacionModificacionProducto.dispose();

        Direct_Control_BD mBD = Direct_Control_BD.getInstance();
        mBD.consultarProducto(this.jTextField_IdProductoModificar.getText());
        String[] columnNames = mBD.getColumnNames();
        Object[][] data = mBD.getData();
       //Nombre,Precio,Costo,idCategoriaProd,Descripcion

        if (data.length == 0) {
            JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto",
                    JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "}, "Cancelar");
        } else {
            //Para que solo acepte 10 enteros y 2 decimales despues del punto
            DocumentFilter onlyNumberFilter = new MyFilter();
            ((AbstractDocument) this.jTextField_Precio1.getDocument()).setDocumentFilter(onlyNumberFilter);
            ((AbstractDocument) this.jTextField_Costo.getDocument()).setDocumentFilter(onlyNumberFilter);
            Pan_Inventario mPanel = Pan_Inventario.getInstance();
            this.jDialog_ModificarProducto.setVisible(true);
            this.jTextField_nombre1.setText(data[0][0].toString());
            this.jTextField_Precio1.setText(data[0][1].toString());
            this.jTextField_Costo.setText(data[0][2].toString());
            String NombreCategoria = mBD.consultarNombreCategoriaXid(Integer.parseInt(data[0][3].toString()));
            if (data[0][4] != null) {
                this.jTextField_Descripcion.setText(data[0][4].toString());
            }
            else{
            this.jTextField_Descripcion.setText("No tiene descripcion");}
            this.jTextField_CodigoProducto.setText(data[0][5].toString());
            this.jTextField_CodigoProducto.disable();

            mBD.consultarCategorias();

            columnNames = mBD.getColumnNames();
            data = mBD.getData();

            this.jComboBox_Categorias.removeAllItems();
            for (int i = 0; i < data.length; i++) {
                this.jComboBox_Categorias.addItem(data[i][1]);
            }

            this.jComboBox_Categorias.setSelectedItem(NombreCategoria);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton_CrearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearCategoriaActionPerformed
       this.jDialog_CrearCategoria.setTitle("Crear Categoria");
       this.jDialog_CrearCategoria.setVisible(true);
       
       
       
    }//GEN-LAST:event_jButton_CrearCategoriaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Direct_Control_BD mBD= Direct_Control_BD.getInstance();
        mBD.insertarCategoria(this.jTextField_NombreCategoria.getText());
        this.jDialog_CrearCategoria.dispose();
        
      
       mBD.consultarCategorias();
       
       String[] columnNames = mBD.getColumnNames();
       Object[][] data = mBD.getData();
       
      
       
       this.jComboBox_Categorias.removeAllItems();
       for(int i=0; i<data.length; i++){
             this.jComboBox_Categorias.addItem(data[i][1]);
       }
       this.jComboBox_Categorias.setSelectedItem(this.jTextField_NombreCategoria.getText());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_IdProductoModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IdProductoModificar1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        this.jDialog_ConfirmacionVerProducto.dispose();
        
       
       Direct_Control_BD mBD= Direct_Control_BD.getInstance();
       mBD.consultarProducto(this.jTextField_IdProductoModificar1.getText());
       String[] columnNames = mBD.getColumnNames();
       Object[][] data = mBD.getData();
       
       if(data.length==0){
           JOptionPane.showOptionDialog(this, "El producto no existe", "Error Producto", 
           JOptionPane.ERROR_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{" Cancelar "},"Cancelar"); 
       }
       else{
           
       Pan_Inventario mPanel= Pan_Inventario.getInstance();
       this.jDialog_VerProducto.setVisible(true); 
       
       this.jTextField_nombreVerProducto.setText(data[0][0].toString());
       this.jTextField_nombreVerProducto.disable();
       this.jTextField_PrecioVerProducto.setText(data[0][1].toString());
       this.jTextField_PrecioVerProducto.disable();
       this.jTextField_CostoVerProducto.setText(data[0][2].toString());
       this.jTextField_CostoVerProducto.disable();
       
       String NombreCategoria = mBD.consultarNombreCategoriaXid(Integer.parseInt(data[0][3].toString()));
        if (data[0][4] != null) {
                this.jTextField_DescripcionVerProducto.setText(data[0][4].toString());
            }
        else{this.jTextField_DescripcionVerProducto.setText("No tiene descripcion");}
       
       this.jTextField_DescripcionVerProducto.disable();
       this.jTextField_CodigoVerProducto.setText(data[0][5].toString());
       this.jTextField_CodigoVerProducto.disable();
       
       this.jTextField_CategoriaVerProducto.setText(NombreCategoria);
       this.jTextField_CategoriaVerProducto.disable();
       
       
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_CostoCrearProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoCrearProductoKeyTyped
        int tecla= evt.getKeyChar();
        
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        }
        
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
         if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_CostoCrearProducto.transferFocus();

        }
        
    }//GEN-LAST:event_jTextField_CostoCrearProductoKeyTyped

    private void jTextField_CantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CantidadKeyTyped
        int tecla= evt.getKeyChar();
        
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
        
        int limite = 10;
        if (jTextField_Cantidad.getText().length() == limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
      if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jTextField_Cantidad.transferFocus();
            
        
        }
       
        
    }//GEN-LAST:event_jTextField_CantidadKeyTyped

    private void jTextField_CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CantidadKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_CantidadKeyPressed

    private void jTextField_CostoCrearProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoCrearProductoKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_CostoCrearProductoKeyPressed

    private void jTextField_Precio1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Precio1KeyPressed
       if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_Precio1KeyPressed

    private void jDialog_ModificarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDialog_ModificarProductoKeyPressed
        
    }//GEN-LAST:event_jDialog_ModificarProductoKeyPressed

    private void jTextField_CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoKeyTyped
       int tecla= evt.getKeyChar();
        
        if(tecla==KeyEvent.VK_COMMA){
            return;
        }
        if(tecla==KeyEvent.VK_PERIOD){
            return;
        }
        
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }
         if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_Costo.transferFocus();

        }
    }//GEN-LAST:event_jTextField_CostoKeyTyped

    private void jTextField_Precio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Precio1KeyTyped
        int tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_COMMA) {
            return;
        }
        if (tecla == KeyEvent.VK_PERIOD) {
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }

        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_Precio1.transferFocus();

        }
    
    }//GEN-LAST:event_jTextField_Precio1KeyTyped

    private void jTextField_CostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CostoKeyPressed
        if(evt.isControlDown()){
        evt.consume();}
    }//GEN-LAST:event_jTextField_CostoKeyPressed

    private void jTextField_codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_codigoKeyTyped
        int limite = 11;
        if (jTextField_codigo.getText().length() >= limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
        if (Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_codigo.transferFocus();

        }
    }//GEN-LAST:event_jTextField_codigoKeyTyped

    private void jTextField_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreKeyTyped
        int limite = 30;
        if (jTextField_nombre.getText().length() >= limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_nombre.transferFocus();

        }
            
    }//GEN-LAST:event_jTextField_nombreKeyTyped

    private void jTextField_CodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_CodigoProductoKeyTyped
      int limite = 11;
        if (jTextField_CodigoProducto.getText().length() >= limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
        if (Character.isLowerCase(evt.getKeyChar())) {
            evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        }
        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_CodigoProducto.transferFocus();

        }
      
    }//GEN-LAST:event_jTextField_CodigoProductoKeyTyped

    private void jTextField_nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombre1KeyTyped
        int limite = 30;
        if (jTextField_nombre1.getText().length() >= limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_nombre1.transferFocus();

        }
    }//GEN-LAST:event_jTextField_nombre1KeyTyped

    private void jComboBox_CategoriaCrearProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_CategoriaCrearProductoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_CategoriaCrearProductoFocusGained

    private void jComboBox_CategoriaCrearProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_CategoriaCrearProductoKeyTyped
       if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jComboBox_CategoriaCrearProducto.transferFocus();
            
        
        }
    }//GEN-LAST:event_jComboBox_CategoriaCrearProductoKeyTyped

    private void jComboBox_CategoriasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_CategoriasKeyTyped
        if(KeyEvent.VK_ENTER==evt.getKeyChar()){
            this.jComboBox_Categorias.transferFocus();
            
        
        }
    }//GEN-LAST:event_jComboBox_CategoriasKeyTyped

    private void jButton_CrearCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton_CrearCategoriaFocusGained
     
            this.jButton_CrearCategoria.transferFocus();
            
        
        
    }//GEN-LAST:event_jButton_CrearCategoriaFocusGained

    private void jTextField_IdProductoModificar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificar1KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jTextField_IdProductoModificar1.transferFocus();
        }
    }//GEN-LAST:event_jTextField_IdProductoModificar1KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton3.doClick();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTextField_IdProductoModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductoModificarKeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jTextField_IdProductoModificar.transferFocus();
        }
    }//GEN-LAST:event_jTextField_IdProductoModificarKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyChar()== KeyEvent.VK_ENTER){
            this.jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyPressed
    
    private void jTextArea_DescripcionCrearProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_DescripcionCrearProductoKeyTyped
        int limite = 30;
        if (jTextArea_DescripcionCrearProducto.getText().length() >= limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextArea_DescripcionCrearProducto.transferFocus();

        }
    }//GEN-LAST:event_jTextArea_DescripcionCrearProductoKeyTyped

    private void jTextField_DescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DescripcionKeyTyped
          int limite = 30;
        if (jTextField_Descripcion.getText().length() >= limite) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_Descripcion.transferFocus();

        }
    }//GEN-LAST:event_jTextField_DescripcionKeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.jTextField_Cantidad.setText("0");
        this.jTextField_Precio.setText("0.00");
        this.jTextField_CostoCrearProducto.setText("0.00");
        this.jTextField_codigo.setText("");
        this.jTextField_nombre.setText("");
        this.jTextArea_DescripcionCrearProducto.setText("");
        this.jDialog_CrearProducto.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox_categoriaBusquedaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_categoriaBusquedaInventarioActionPerformed
        this.agregarBuscador(this.jTable_Inventario,this.jTextField_busquedaInventario,this.jComboBox_categoriaBusquedaInventario.getSelectedIndex());
        this.jTextField_busquedaInventario.setText("");
        this.jTextField_busquedaInventario.requestFocusInWindow();
    }//GEN-LAST:event_jComboBox_categoriaBusquedaInventarioActionPerformed

    private void jTextField_PrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_PrecioFocusGained
        this.jTextField_Precio.selectAll();
    }//GEN-LAST:event_jTextField_PrecioFocusGained

    private void jTextField_PrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PrecioKeyPressed
        if (evt.isControlDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PrecioKeyPressed

    private void jTextField_PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PrecioKeyTyped
        int tecla = evt.getKeyChar();
        if (tecla == KeyEvent.VK_COMMA) {
            return;
        }
        if (tecla == KeyEvent.VK_PERIOD) {
            return;
        }
        if (!Character.isDigit(tecla) & !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();

        }

        if (KeyEvent.VK_ENTER == evt.getKeyChar()) {
            this.jTextField_Precio.transferFocus();

        }
    }//GEN-LAST:event_jTextField_PrecioKeyTyped

    private void bttAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttAddMouseClicked
        this.jDialog_CrearProducto.setVisible(true);

        Direct_Control_BD mBD= Direct_Control_BD.getInstance();
        mBD.consultarCategorias();
        String[] columnNames = mBD.getColumnNames();
        Object[][] data = mBD.getData();

        columnNames = mBD.getColumnNames();
        data = mBD.getData();

        this.jComboBox_CategoriaCrearProducto.removeAllItems();
        for(int i=0; i<data.length; i++){
            this.jComboBox_CategoriaCrearProducto.addItem(data[i][1]);
        }

        this.jComboBox_CategoriaCrearProducto.setSelectedItem("Sin Categoria");
        //Para que solo acepte 10 enteros y 2 decimales despues del punto
        DocumentFilter onlyNumberFilter = new MyFilter();
        ((AbstractDocument)this.jTextField_Precio.getDocument()).setDocumentFilter(onlyNumberFilter);
        ((AbstractDocument)this.jTextField_CostoCrearProducto.getDocument()).setDocumentFilter(onlyNumberFilter);
        
    }//GEN-LAST:event_bttAddMouseClicked

    private void bttWatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttWatchMouseClicked
        int row = this.jTable_Inventario.getSelectedRow();
        if(row>=0){
            String idProducto = this.jTable_Inventario.getValueAt(row, 0).toString();
            Pan_Inventario mPanel = Pan_Inventario.getInstance();            
            this.jTextField_IdProductoModificar1.setText(idProducto);
            this.jDialog_ConfirmacionVerProducto.setVisible(true);}
        else{
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttWatchMouseClicked

    private void bttEraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttEraseMouseClicked
        int row = this.jTable_Inventario.getSelectedRow();

        if (row >= 0) {
            Pan_Inventario mPanel= Pan_Inventario.getInstance();
            this.jTextField_IdProducto.setText(this.jTable_Inventario.getValueAt(row, 0).toString());
            this.jDialog_EliminarProducto.setVisible(true);}
        else {
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttEraseMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialog_VerProducto.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jDialog_CrearCategoria.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        Dialog_generarEtiquetas etiquetas = new Dialog_generarEtiquetas(null,true);
    }//GEN-LAST:event_jLabel28MouseClicked

    private void bttEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttEditMouseClicked
        int row = this.jTable_Inventario.getSelectedRow();

        if (row >= 0) {
            String idProducto = this.jTable_Inventario.getValueAt(row, 0).toString();
            this.jTextField_IdProductoModificar.setText(idProducto);
            this.jDialog_ConfirmacionModificacionProducto.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(
                null,
                "No se selecciono ningun producto",
                "Alert!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttEditMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bttAdd;
    private javax.swing.JLabel bttEdit;
    private javax.swing.JLabel bttErase;
    private javax.swing.JLabel bttWatch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_CrearCategoria;
    private javax.swing.JButton jButton_CrearProducto;
    private javax.swing.JButton jButton_CrearProducto1;
    private javax.swing.JButton jButton_EliminarProducto;
    private javax.swing.JComboBox jComboBox_CategoriaCrearProducto;
    private javax.swing.JComboBox jComboBox_Categorias;
    private javax.swing.JComboBox jComboBox_categoriaBusquedaInventario;
    private javax.swing.JDialog jDialog_ConfirmacionModificacionProducto;
    private javax.swing.JDialog jDialog_ConfirmacionVerProducto;
    private javax.swing.JDialog jDialog_CrearCategoria;
    private javax.swing.JDialog jDialog_CrearProducto;
    private javax.swing.JDialog jDialog_EliminarProducto;
    private javax.swing.JDialog jDialog_ModificarProducto;
    private javax.swing.JDialog jDialog_VerProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Codigo;
    private javax.swing.JLabel jLabel_Codigo2;
    private javax.swing.JLabel jLabel_Costo;
    private javax.swing.JLabel jLabel_Costo2;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Precio;
    private javax.swing.JLabel jLabel_Precio2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable_Inventario;
    private javax.swing.JTextField jTextArea_DescripcionCrearProducto;
    private javax.swing.JTextField jTextField_Cantidad;
    private javax.swing.JTextField jTextField_CategoriaVerProducto;
    private javax.swing.JTextField jTextField_CodigoProducto;
    private javax.swing.JTextField jTextField_CodigoVerProducto;
    private javax.swing.JTextField jTextField_Costo;
    private javax.swing.JTextField jTextField_CostoCrearProducto;
    private javax.swing.JTextField jTextField_CostoVerProducto;
    private javax.swing.JTextField jTextField_Descripcion;
    private javax.swing.JTextField jTextField_DescripcionVerProducto;
    private javax.swing.JTextField jTextField_IdProducto;
    private javax.swing.JTextField jTextField_IdProductoModificar;
    private javax.swing.JTextField jTextField_IdProductoModificar1;
    private javax.swing.JTextField jTextField_NombreCategoria;
    private javax.swing.JFormattedTextField jTextField_Precio;
    private javax.swing.JTextField jTextField_Precio1;
    private javax.swing.JTextField jTextField_PrecioVerProducto;
    private javax.swing.JTextField jTextField_busquedaInventario;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_nombre1;
    private javax.swing.JTextField jTextField_nombreVerProducto;
    // End of variables declaration//GEN-END:variables

   private void agregarBuscador(JTable table, JTextField textfield, int columna) {
         //Crea el ordenador para la tabla generica
        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>
                (table.getModel());
        table.setRowSorter(ordenador);
        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
        qq.add(new RowSorter.SortKey(0,SortOrder.ASCENDING));
        ordenador.setSortKeys(qq);
        /**Agrega el listener al JtextField del buscador **/
        textfield.getDocument().addDocumentListener(new
                ListenerBuscador(textfield,ordenador,columna));
    }
    
     /**
     * Este metodo convierte un string que es un decimal a bigdecimal
     *
     * @param numero
     * @return
     */
    private BigDecimal StringtoBigDecimal(String numero) {
        DecimalFormat decimalfC = (DecimalFormat) NumberFormat.getInstance();
        decimalfC.setParseBigDecimal(true);
        BigDecimal numeroCorregido = null;
        try {
            numeroCorregido = (BigDecimal) decimalfC.parseObject(numero);
        } catch (ParseException ex) {
            Logger.getLogger(JPanel_VerFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        return numeroCorregido;

    }
    
    private void crearMovimiento(String detalle, BigDecimal precioProd, int movimiento) {
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        AdminBD.insertarmovimiento(detalle,movimiento,1,precioProd);
    }
    
    private void guardaProductoEnMovimiento(String idProducto, int idVersion, int cantidadMov, BigDecimal PrecioVenta) {
        Direct_Control_BD AdminBD = Direct_Control_BD.getInstance();
        int idMovimiento= AdminBD.ObtenerUltimoidMovimiento();
        AdminBD.insertarProductoCantidadMovimiento(idProducto,idVersion,idMovimiento,cantidadMov,PrecioVenta);
    }


    
}
