/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package joe;

import db_managment.Direct_Control_BD;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;

import javax.swing.RowSorter;
import javax.swing.SortOrder;

import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Jason
 */
public class Pan_Clientes extends javax.swing.JPanel {

    Object[][] data;
    Direct_Control_BD AdminBD;
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    DateFormat dateFormatIng = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form NewJPanel_ClienteVendedor
     */
    public Pan_Clientes() {
        initComponents();
        AdminBD = Direct_Control_BD.getInstance();
        actualizaTablaParaClientes();
        addPanelsToDialog();
        hideAllPanelsOfDialogs();
    }

    private void addPanelsToDialog(){
        jDialog_CrearClte.add(jPanel_CrearCliente);
        jDialog_CrearClte.add(jPanel_ModifCliente);
        jDialog_CrearClte.add(jPanel_VerClte);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jDialog_CrearClte = new javax.swing.JDialog();
        jPanel_CrearCliente = new javax.swing.JPanel();
        jLabel_nombreCliente3 = new javax.swing.JLabel();
        jLabel_telefonoCliente3 = new javax.swing.JLabel();
        jLabel_direccionCliente3 = new javax.swing.JLabel();
        jLabel_FechaCumpleanos3 = new javax.swing.JLabel();
        jFormattedTextField_nombreClteVend = new javax.swing.JFormattedTextField();
        jFormattedTextField_telefonoClteVend = new javax.swing.JFormattedTextField();
        jFormattedTextField_direccionClteVend = new javax.swing.JFormattedTextField();
        jButton_CrearCliente = new javax.swing.JButton();
        jButton_CancelarCrearCliente = new javax.swing.JButton();
        dateChooserCombo_CumpCrearCliente = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        jPanel_VerClte = new javax.swing.JPanel();
        jLabel_nombreCliente4 = new javax.swing.JLabel();
        jLabel_telefonoCliente4 = new javax.swing.JLabel();
        jLabel_direccionCliente4 = new javax.swing.JLabel();
        jLabel_FechaCumpleanos4 = new javax.swing.JLabel();
        jButton_CrearCliente1 = new javax.swing.JButton();
        jLabel_DirreVerClteVend = new javax.swing.JLabel();
        jLabel_FechaCVerClteVend = new javax.swing.JLabel();
        jLabel_TeleVerClteVend = new javax.swing.JLabel();
        jLabel_NombreVerClteVend = new javax.swing.JLabel();
        jLabel_FechaCumpleanos5 = new javax.swing.JLabel();
        jLabel_CedCVerClteVend = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel_ModifCliente = new javax.swing.JPanel();
        jLabel_nombreCliente5 = new javax.swing.JLabel();
        jLabel_telefonoCliente5 = new javax.swing.JLabel();
        jLabel_direccionCliente5 = new javax.swing.JLabel();
        jLabel_FechaCumpleanos6 = new javax.swing.JLabel();
        jFormattedTextField_ModfnombreClteVend = new javax.swing.JFormattedTextField();
        jFormattedTextField_ModfdireccionClteVend = new javax.swing.JFormattedTextField();
        jButton_ModifCliente = new javax.swing.JButton();
        jButton_CancelarModifiCliente = new javax.swing.JButton();
        jFormattedTextField_ModfCedulaClteVend = new javax.swing.JFormattedTextField();
        jLabel_FechaCumpleanos7 = new javax.swing.JLabel();
        jFormattedTextField_ModftelefonoClteVend = new javax.swing.JFormattedTextField();
        dateChooserCombo_CumpModifCliente = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Generica = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        TextField_Buscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bkg = new javax.swing.JLabel();

        jDialog_CrearClte.setModal(true);
        jDialog_CrearClte.setUndecorated(true);
        jDialog_CrearClte.setResizable(false);
        jDialog_CrearClte.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jDialog_CrearClteWindowClosed(evt);
            }
        });
        jDialog_CrearClte.getContentPane().setLayout(null);

        jPanel_CrearCliente.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_CrearCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_CrearCliente.setMaximumSize(new java.awt.Dimension(390, 210));
        jPanel_CrearCliente.setMinimumSize(new java.awt.Dimension(390, 210));
        jPanel_CrearCliente.setPreferredSize(new java.awt.Dimension(390, 210));
        jPanel_CrearCliente.setLayout(null);
        jPanel_CrearCliente.setSize(390, 210);

        jLabel_nombreCliente3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente3.setText("Nombre del Cliente");
        jPanel_CrearCliente.add(jLabel_nombreCliente3);
        jLabel_nombreCliente3.setBounds(20, 40, 110, 20);

        jLabel_telefonoCliente3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefonoCliente3.setText("Telefono");
        jPanel_CrearCliente.add(jLabel_telefonoCliente3);
        jLabel_telefonoCliente3.setBounds(20, 100, 60, 23);

        jLabel_direccionCliente3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccionCliente3.setText("Direccion");
        jPanel_CrearCliente.add(jLabel_direccionCliente3);
        jLabel_direccionCliente3.setBounds(20, 70, 60, 23);

        jLabel_FechaCumpleanos3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCumpleanos3.setText("Fecha de Cumpleanos");
        jPanel_CrearCliente.add(jLabel_FechaCumpleanos3);
        jLabel_FechaCumpleanos3.setBounds(20, 130, 120, 23);

        jFormattedTextField_nombreClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_nombreClteVendKeyPressed(evt);
            }
        });
        jPanel_CrearCliente.add(jFormattedTextField_nombreClteVend);
        jFormattedTextField_nombreClteVend.setBounds(140, 40, 230, 23);

        jFormattedTextField_telefonoClteVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_telefonoClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_telefonoClteVendKeyPressed(evt);
            }
        });
        jPanel_CrearCliente.add(jFormattedTextField_telefonoClteVend);
        jFormattedTextField_telefonoClteVend.setBounds(140, 100, 230, 23);

        jFormattedTextField_direccionClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_direccionClteVendKeyPressed(evt);
            }
        });
        jPanel_CrearCliente.add(jFormattedTextField_direccionClteVend);
        jFormattedTextField_direccionClteVend.setBounds(140, 70, 230, 23);

        jButton_CrearCliente.setText("Aceptar");
        jButton_CrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearClienteActionPerformed(evt);
            }
        });
        jButton_CrearCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CrearClienteKeyPressed(evt);
            }
        });
        jPanel_CrearCliente.add(jButton_CrearCliente);
        jButton_CrearCliente.setBounds(200, 170, 71, 23);

        jButton_CancelarCrearCliente.setText("Cancelar");
        jButton_CancelarCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarCrearClienteActionPerformed(evt);
            }
        });
        jPanel_CrearCliente.add(jButton_CancelarCrearCliente);
        jButton_CancelarCrearCliente.setBounds(280, 170, 90, 23);

        dateChooserCombo_CumpCrearCliente.setCalendarBackground(new java.awt.Color(0, 51, 51));
        dateChooserCombo_CumpCrearCliente.setNothingAllowed(false);
        dateChooserCombo_CumpCrearCliente.setLocale(new java.util.Locale("es", "", ""));
        dateChooserCombo_CumpCrearCliente.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        jPanel_CrearCliente.add(dateChooserCombo_CumpCrearCliente);
        dateChooserCombo_CumpCrearCliente.setBounds(140, 130, 230, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Crear cliente");
        jPanel_CrearCliente.add(jLabel8);
        jLabel8.setBounds(10, 10, 320, 22);

        jPanel_VerClte.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_VerClte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_VerClte.setMaximumSize(new java.awt.Dimension(615, 445));
        jPanel_VerClte.setMinimumSize(new java.awt.Dimension(535, 235));
        jPanel_VerClte.setPreferredSize(new java.awt.Dimension(535, 235));
        jPanel_VerClte.setLayout(null);
        jPanel_VerClte.setSize(535, 235);
        jLabel_NombreVerClteVend.setText("");
        jLabel_TeleVerClteVend.setText("");
        jLabel_DirreVerClteVend.setText("");
        jLabel_CedCVerClteVend.setText("");
        jLabel_FechaCVerClteVend.setText("");

        jLabel_nombreCliente4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nombreCliente4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente4.setText("Nombre del Cliente");
        jPanel_VerClte.add(jLabel_nombreCliente4);
        jLabel_nombreCliente4.setBounds(10, 40, 140, 23);

        jLabel_telefonoCliente4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_telefonoCliente4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefonoCliente4.setText("Telefono");
        jPanel_VerClte.add(jLabel_telefonoCliente4);
        jLabel_telefonoCliente4.setBounds(10, 70, 140, 23);

        jLabel_direccionCliente4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_direccionCliente4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccionCliente4.setText("Dirección");
        jPanel_VerClte.add(jLabel_direccionCliente4);
        jLabel_direccionCliente4.setBounds(10, 100, 140, 23);

        jLabel_FechaCumpleanos4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_FechaCumpleanos4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCumpleanos4.setText("Fecha de Cumpleaños");
        jPanel_VerClte.add(jLabel_FechaCumpleanos4);
        jLabel_FechaCumpleanos4.setBounds(10, 160, 140, 23);

        jButton_CrearCliente1.setText("Aceptar");
        jButton_CrearCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearCliente1ActionPerformed(evt);
            }
        });
        jButton_CrearCliente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_CrearCliente1KeyPressed(evt);
            }
        });
        jPanel_VerClte.add(jButton_CrearCliente1);
        jButton_CrearCliente1.setBounds(450, 200, 71, 23);

        jLabel_DirreVerClteVend.setBackground(new java.awt.Color(0, 51, 51));
        jLabel_DirreVerClteVend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_DirreVerClteVend.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DirreVerClteVend.setText("...");
        jPanel_VerClte.add(jLabel_DirreVerClteVend);
        jLabel_DirreVerClteVend.setBounds(160, 100, 360, 23);

        jLabel_FechaCVerClteVend.setBackground(new java.awt.Color(0, 51, 51));
        jLabel_FechaCVerClteVend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_FechaCVerClteVend.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCVerClteVend.setText("...");
        jPanel_VerClte.add(jLabel_FechaCVerClteVend);
        jLabel_FechaCVerClteVend.setBounds(160, 160, 360, 23);

        jLabel_TeleVerClteVend.setBackground(new java.awt.Color(0, 51, 51));
        jLabel_TeleVerClteVend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_TeleVerClteVend.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TeleVerClteVend.setText("...");
        jPanel_VerClte.add(jLabel_TeleVerClteVend);
        jLabel_TeleVerClteVend.setBounds(160, 70, 360, 23);

        jLabel_NombreVerClteVend.setBackground(new java.awt.Color(0, 51, 51));
        jLabel_NombreVerClteVend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_NombreVerClteVend.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreVerClteVend.setText("...");
        jLabel_NombreVerClteVend.setToolTipText("");
        jPanel_VerClte.add(jLabel_NombreVerClteVend);
        jLabel_NombreVerClteVend.setBounds(160, 40, 360, 23);

        jLabel_FechaCumpleanos5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_FechaCumpleanos5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCumpleanos5.setText("Cédula");
        jPanel_VerClte.add(jLabel_FechaCumpleanos5);
        jLabel_FechaCumpleanos5.setBounds(10, 130, 140, 23);

        jLabel_CedCVerClteVend.setBackground(new java.awt.Color(0, 51, 51));
        jLabel_CedCVerClteVend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_CedCVerClteVend.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CedCVerClteVend.setText("...");
        jLabel_CedCVerClteVend.setToolTipText("");
        jPanel_VerClte.add(jLabel_CedCVerClteVend);
        jLabel_CedCVerClteVend.setBounds(160, 130, 360, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ver Cliente");
        jPanel_VerClte.add(jLabel7);
        jLabel7.setBounds(10, 10, 280, 22);

        jPanel_ModifCliente.setBackground(new java.awt.Color(153, 153, 153));
        jPanel_ModifCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_ModifCliente.setMaximumSize(new java.awt.Dimension(380, 300));
        jPanel_ModifCliente.setMinimumSize(new java.awt.Dimension(380, 300));
        jPanel_ModifCliente.setPreferredSize(new java.awt.Dimension(380, 300));
        jPanel_ModifCliente.setLayout(null);
        jPanel_ModifCliente.setSize(380, 300);

        jLabel_nombreCliente5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombreCliente5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente5.setText("Nombre del Cliente");
        jPanel_ModifCliente.add(jLabel_nombreCliente5);
        jLabel_nombreCliente5.setBounds(20, 40, 140, 20);

        jLabel_telefonoCliente5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_telefonoCliente5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_telefonoCliente5.setText("Telefono");
        jPanel_ModifCliente.add(jLabel_telefonoCliente5);
        jLabel_telefonoCliente5.setBounds(20, 80, 105, 14);

        jLabel_direccionCliente5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_direccionCliente5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_direccionCliente5.setText("Direccion");
        jPanel_ModifCliente.add(jLabel_direccionCliente5);
        jLabel_direccionCliente5.setBounds(20, 120, 105, 14);

        jLabel_FechaCumpleanos6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_FechaCumpleanos6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCumpleanos6.setText("Fecha de Cumpleanos");
        jPanel_ModifCliente.add(jLabel_FechaCumpleanos6);
        jLabel_FechaCumpleanos6.setBounds(20, 160, 150, 20);

        jFormattedTextField_ModfnombreClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_ModfnombreClteVendKeyPressed(evt);
            }
        });
        jPanel_ModifCliente.add(jFormattedTextField_ModfnombreClteVend);
        jFormattedTextField_ModfnombreClteVend.setBounds(180, 40, 168, 23);

        jFormattedTextField_ModfdireccionClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_ModfdireccionClteVendKeyPressed(evt);
            }
        });
        jPanel_ModifCliente.add(jFormattedTextField_ModfdireccionClteVend);
        jFormattedTextField_ModfdireccionClteVend.setBounds(180, 120, 168, 23);

        jButton_ModifCliente.setText("Aceptar");
        jButton_ModifCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModifClienteActionPerformed(evt);
            }
        });
        jButton_ModifCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ModifClienteKeyPressed(evt);
            }
        });
        jPanel_ModifCliente.add(jButton_ModifCliente);
        jButton_ModifCliente.setBounds(180, 250, 71, 23);

        jButton_CancelarModifiCliente.setText("Cancelar");
        jButton_CancelarModifiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarModifiClienteActionPerformed(evt);
            }
        });
        jPanel_ModifCliente.add(jButton_CancelarModifiCliente);
        jButton_CancelarModifiCliente.setBounds(270, 250, 75, 23);

        jFormattedTextField_ModfCedulaClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_ModfCedulaClteVendKeyPressed(evt);
            }
        });
        jPanel_ModifCliente.add(jFormattedTextField_ModfCedulaClteVend);
        jFormattedTextField_ModfCedulaClteVend.setBounds(180, 200, 168, 23);

        jLabel_FechaCumpleanos7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_FechaCumpleanos7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FechaCumpleanos7.setText("Cédula");
        jPanel_ModifCliente.add(jLabel_FechaCumpleanos7);
        jLabel_FechaCumpleanos7.setBounds(20, 200, 105, 20);

        jFormattedTextField_ModftelefonoClteVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField_ModftelefonoClteVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormattedTextField_ModftelefonoClteVendKeyPressed(evt);
            }
        });
        jPanel_ModifCliente.add(jFormattedTextField_ModftelefonoClteVend);
        jFormattedTextField_ModftelefonoClteVend.setBounds(180, 80, 168, 23);

        dateChooserCombo_CumpModifCliente.setCalendarBackground(new java.awt.Color(0, 51, 51));
        dateChooserCombo_CumpModifCliente.setNothingAllowed(false);
        dateChooserCombo_CumpModifCliente.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        jPanel_ModifCliente.add(dateChooserCombo_CumpModifCliente);
        dateChooserCombo_CumpModifCliente.setBounds(180, 160, 168, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modificar Cliente");
        jPanel_ModifCliente.add(jLabel6);
        jLabel6.setBounds(10, 10, 390, 22);

        setMaximumSize(new java.awt.Dimension(800, 471));
        setMinimumSize(new java.awt.Dimension(800, 471));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 471));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jTable_Generica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Generica.setFillsViewportHeight(true);
        jTable_Generica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_GenericaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Generica);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 760, 360);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1025, 429, 77, 23);
        jPanel1.add(TextField_Buscador);
        TextField_Buscador.setBounds(235, 5, 200, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 5, 40, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clientes");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 5, 86, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/watchBtt.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 420, 40, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/addBtt.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 420, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Buttons/editBtt.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 420, 40, 40);

        bkg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/Panel1/panelVF.png"))); // NOI18N
        jPanel1.add(bkg);
        bkg.setBounds(0, 0, 800, 471);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 470);
    }//GEN-END:initComponents

    private void jFormattedTextField_nombreClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_nombreClteVendKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jFormattedTextField_nombreClteVend.transferFocus();
        }
    }//GEN-LAST:event_jFormattedTextField_nombreClteVendKeyPressed

    private void jFormattedTextField_telefonoClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_telefonoClteVendKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jFormattedTextField_telefonoClteVend.transferFocus();
        }
    }//GEN-LAST:event_jFormattedTextField_telefonoClteVendKeyPressed

    private void jFormattedTextField_direccionClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_direccionClteVendKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jFormattedTextField_direccionClteVend.transferFocus();
        }
    }//GEN-LAST:event_jFormattedTextField_direccionClteVendKeyPressed

    private void jButton_CrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearClienteActionPerformed
        crearPersona();
        actualizaTablaParaClientes();
        jDialog_CrearClte.dispose();
    }//GEN-LAST:event_jButton_CrearClienteActionPerformed

    private void jButton_CrearClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CrearClienteKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            // this.crearCliente();
        }
    }//GEN-LAST:event_jButton_CrearClienteKeyPressed

    private void jButton_CancelarCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarCrearClienteActionPerformed

        this.jDialog_CrearClte.dispose();
        //    this.setFocusTablaFact(0);
    }//GEN-LAST:event_jButton_CancelarCrearClienteActionPerformed

    private void jTable_GenericaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_GenericaMouseClicked
        if (evt.getClickCount() == 2) {
            //            this.jButton_AceptarBusqueda.doClick();
        }
    }//GEN-LAST:event_jTable_GenericaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaDeInicio panelReportes = VentanaDeInicio.getInstance();
        setVisible(false);
        panelReportes.jPanel_VentanaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_CrearCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearCliente1ActionPerformed
        jDialog_CrearClte.dispose();
    }//GEN-LAST:event_jButton_CrearCliente1ActionPerformed

    private void jButton_CrearCliente1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_CrearCliente1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CrearCliente1KeyPressed

    private void jFormattedTextField_ModfnombreClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModfnombreClteVendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModfnombreClteVendKeyPressed

    private void jFormattedTextField_ModfdireccionClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModfdireccionClteVendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModfdireccionClteVendKeyPressed

    private void jButton_ModifClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModifClienteActionPerformed

        modificarPersona(data[0][0].toString());
        actualizaTablaParaClientes();

        jDialog_CrearClte.dispose();
    }//GEN-LAST:event_jButton_ModifClienteActionPerformed

    private void jButton_ModifClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ModifClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ModifClienteKeyPressed

    private void jButton_CancelarModifiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarModifiClienteActionPerformed
        this.jDialog_CrearClte.dispose();
    }//GEN-LAST:event_jButton_CancelarModifiClienteActionPerformed

    private void jFormattedTextField_ModfCedulaClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModfCedulaClteVendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModfCedulaClteVendKeyPressed

    private void jFormattedTextField_ModftelefonoClteVendKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_ModftelefonoClteVendKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_ModftelefonoClteVendKeyPressed

    private void jDialog_CrearClteWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog_CrearClteWindowClosed
        hideAllPanelsOfDialogs();
    }//GEN-LAST:event_jDialog_CrearClteWindowClosed

    private void hideAllPanelsOfDialogs(){
        jPanel_CrearCliente.setVisible(false);
        jPanel_CrearCliente.setEnabled(false);
        
        jPanel_ModifCliente.setVisible(false);
        jPanel_ModifCliente.setEnabled(false);
        
        jPanel_VerClte.setVisible(false);
        jPanel_VerClte.setEnabled(false);
    }
    
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        llenarEditarInformacionClteVend();
        
        showPanelOnDialog(jPanel_ModifCliente);
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        llenarInformacionClteVend();
        
        showPanelOnDialog(jPanel_VerClte);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        showPanelOnDialog(jPanel_CrearCliente);
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void showPanelOnDialog(javax.swing.JPanel pPanel){
        jDialog_CrearClte.setSize(pPanel.getSize());
        jDialog_CrearClte.setLocationRelativeTo(null);
        
        pPanel.setVisible(true);
        pPanel.setEnabled(true);
        jDialog_CrearClte.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_Buscador;
    private javax.swing.JLabel bkg;
    private datechooser.beans.DateChooserCombo dateChooserCombo_CumpCrearCliente;
    private datechooser.beans.DateChooserCombo dateChooserCombo_CumpModifCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_CancelarCrearCliente;
    private javax.swing.JButton jButton_CancelarModifiCliente;
    private javax.swing.JButton jButton_CrearCliente;
    private javax.swing.JButton jButton_CrearCliente1;
    private javax.swing.JButton jButton_ModifCliente;
    private javax.swing.JDialog jDialog_CrearClte;
    private javax.swing.JFormattedTextField jFormattedTextField_ModfCedulaClteVend;
    private javax.swing.JFormattedTextField jFormattedTextField_ModfdireccionClteVend;
    private javax.swing.JFormattedTextField jFormattedTextField_ModfnombreClteVend;
    private javax.swing.JFormattedTextField jFormattedTextField_ModftelefonoClteVend;
    private javax.swing.JFormattedTextField jFormattedTextField_direccionClteVend;
    private javax.swing.JFormattedTextField jFormattedTextField_nombreClteVend;
    private javax.swing.JFormattedTextField jFormattedTextField_telefonoClteVend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_CedCVerClteVend;
    private javax.swing.JLabel jLabel_DirreVerClteVend;
    private javax.swing.JLabel jLabel_FechaCVerClteVend;
    private javax.swing.JLabel jLabel_FechaCumpleanos3;
    private javax.swing.JLabel jLabel_FechaCumpleanos4;
    private javax.swing.JLabel jLabel_FechaCumpleanos5;
    private javax.swing.JLabel jLabel_FechaCumpleanos6;
    private javax.swing.JLabel jLabel_FechaCumpleanos7;
    private javax.swing.JLabel jLabel_NombreVerClteVend;
    private javax.swing.JLabel jLabel_TeleVerClteVend;
    private javax.swing.JLabel jLabel_direccionCliente3;
    private javax.swing.JLabel jLabel_direccionCliente4;
    private javax.swing.JLabel jLabel_direccionCliente5;
    private javax.swing.JLabel jLabel_nombreCliente3;
    private javax.swing.JLabel jLabel_nombreCliente4;
    private javax.swing.JLabel jLabel_nombreCliente5;
    private javax.swing.JLabel jLabel_telefonoCliente3;
    private javax.swing.JLabel jLabel_telefonoCliente4;
    private javax.swing.JLabel jLabel_telefonoCliente5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_CrearCliente;
    private javax.swing.JPanel jPanel_ModifCliente;
    private javax.swing.JPanel jPanel_VerClte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Generica;
    // End of variables declaration//GEN-END:variables
 public void actualizaTablaParaClientes() {
        AdminBD.consultarClientes();
        data = AdminBD.getData();
        String[] columnNames = AdminBD.getColumnNames();

        this.jTable_Generica.setModel(new MyTableModel_Generic(columnNames, data));
        //Crea el ordenador para la tabla generica
        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>(this.jTable_Generica.getModel());
        this.jTable_Generica.setRowSorter(ordenador);
        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
        qq.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        ordenador.setSortKeys(qq);
        jTable_Generica.requestFocus();
        jTable_Generica.changeSelection(0, 0, false, false);
        /**
         * Agrega el listener al JtextField del buscador *
         */
        this.TextField_Buscador.getDocument().addDocumentListener(new ListenerBuscador(this.TextField_Buscador, ordenador));

    }

//    public void actualizaTablaParaVendedores() {
//        AdminBD.consultarVendedores();
//        data = AdminBD.getData();
//        String[] columnNames = AdminBD.getColumnNames();
//
//        this.jTable_Generica.setModel(new MyTableModel_Generic(columnNames, data));
//        //Crea el ordenador para la tabla generica
//        TableRowSorter<TableModel> ordenador = new TableRowSorter<TableModel>(this.jTable_Generica.getModel());
//        this.jTable_Generica.setRowSorter(ordenador);
//        Vector<RowSorter.SortKey> qq = new Vector<RowSorter.SortKey>();
//        qq.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
//        ordenador.setSortKeys(qq);
//        jTable_Generica.requestFocus();
//        jTable_Generica.changeSelection(0, 0, false, false);
//        /**
//         * Agrega el listener al JtextField del buscador *
//         */
//        this.TextField_Buscador.getDocument().addDocumentListener(new ListenerBuscador(this.TextField_Buscador, ordenador));
//
//    }

    private void crearPersona() {
        String nombre = this.jFormattedTextField_nombreClteVend.getText();
        String direccion = this.jFormattedTextField_direccionClteVend.getText();
        String telefono = this.jFormattedTextField_telefonoClteVend.getText();
        String fechaCumpleanos = dateFormatIng.format(
                dateChooserCombo_CumpCrearCliente.getSelectedDate().
                getTime());
        if (fechaCumpleanos.equals("")) {
            fechaCumpleanos = null;
        }
        AdminBD.insertarCliente(nombre, direccion, telefono, fechaCumpleanos);
    }

    private void llenarInformacionClteVend() {
        AdminBD.consultarPersona(jTable_Generica.getValueAt(
                jTable_Generica.getSelectedRow(), 0).toString());
        data = AdminBD.getData();

        jLabel_NombreVerClteVend.setText(data[0][0].toString());
        jLabel_DirreVerClteVend.setText(data[0][1].toString());
        jLabel_TeleVerClteVend.setText(data[0][2].toString());
        try {
            jLabel_FechaCVerClteVend.setText(data[0][3].toString());
            jLabel_CedCVerClteVend.setText(data[0][4].toString());

        } catch (Exception e) {

        }

    }

    private void llenarEditarInformacionClteVend() {
        AdminBD.consultarPersona(jTable_Generica.getValueAt(
                jTable_Generica.getSelectedRow(), 0).toString());
        data = AdminBD.getData();

        jFormattedTextField_ModfnombreClteVend.setText(data[0][0].toString());
        jFormattedTextField_ModfdireccionClteVend.setText(data[0][1].toString());
        jFormattedTextField_ModftelefonoClteVend.setText(data[0][2].toString());
//        jFormattedTextField_ModfCedulaClteVend.setText(data[0][4].toString());

        Calendar calendar = new GregorianCalendar();
        try {
            //Establecer fecha de cumpleanos
            Date date = dateFormat.parse(data[0][3].toString());
            calendar.setTime(date);
            dateChooserCombo_CumpModifCliente.setSelectedDate(calendar);

        } catch (ParseException e) {
            //Si la fecha es nula pone fecha actual
            calendar.setTime(new Date());
            dateChooserCombo_CumpModifCliente.setSelectedDate(calendar);
        }

    }

    /**
     * peromite modificar la informacion de una persona(cliente o vendedor)
     *
     * @param tipoPersona
     * @param nombre
     */
    private void modificarPersona(String nombre) {

        String fecha = dateFormatIng.format(
                dateChooserCombo_CumpModifCliente.getSelectedDate().
                getTime());
        if ("".equals(fecha)) {// si la fecha es vacia, no la actualiza
            AdminBD.modificarPersona(jFormattedTextField_ModfnombreClteVend.
                    getText().toString(), jFormattedTextField_ModfdireccionClteVend.getText().toString(),
                    jFormattedTextField_ModftelefonoClteVend.getText().toString(),
                    jFormattedTextField_ModfCedulaClteVend.
                    getText().toString(), nombre);
        } else {
            AdminBD.modificarPersona(jFormattedTextField_ModfnombreClteVend.
                    getText().toString(), jFormattedTextField_ModfdireccionClteVend.getText().toString(),
                    jFormattedTextField_ModftelefonoClteVend.getText().toString(), fecha,
                    jFormattedTextField_ModfCedulaClteVend.
                    getText().toString(), nombre);
        }
    }
}
