/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import ManejoDeArchivos.XMLConfiguracion;
import db_managment.Direct_Control_BD;
import java.awt.Toolkit;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class StartWindow extends javax.swing.JFrame {

    private static StartWindow _instance = null;
    private static int _posX;
    private static int _posY;
    
    private static final int LOGGED_IN = 0;
    private static final int LOGGED_OUT = 1;
    
    private boolean _logged;
    
    /**
     * Creates new form StartWindow
     */
    public StartWindow() {
        _instance = this;
        _logged = false;
        
        initComponents();
        
        //Esto hay que quitarlo:
        bkgImage.setText("");
        bkgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/url.jpg")));
        
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        this.setSize(screenSize);
        this.setLocation(0, 0);
        bkColor.setSize(screenSize);
        _posX = this.getWidth()/2-jLayeredPane1.getWidth()/2;
        _posY = this.getHeight()/2-jLayeredPane1.getHeight()/2;
        jLayeredPane1.setLocation(_posX, _posY);       
        
        panActiveUsser.setLocation(600, 180);
        activeLoginPanel(LOGGED_OUT);
    }
    
    private void activeLoginPanel(int pPanel){
        if (pPanel == LOGGED_IN){
            panActiveUsser.setVisible(true);
            panActiveUsser.setEnabled(true);
            panLoggedoutUsser.setVisible(false);
            panLoggedoutUsser.setEnabled(false);
        } else {
            panActiveUsser.setVisible(false);
            panActiveUsser.setEnabled(false);
            panLoggedoutUsser.setVisible(true);
            panLoggedoutUsser.setEnabled(true);
        }
    }
    
    public static int getPosX(){
        return _posX;
    }
    
    public static int getPosY(){
        return _posY;
    }
    
    public void enableMe(){
        this.setEnabled(true);
    }
    
    public static StartWindow getInstance(){
        return _instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        panActiveUsser = new javax.swing.JPanel();
        labActiveName = new javax.swing.JLabel();
        bttLogout = new javax.swing.JLabel();
        panLoggedoutUsser = new javax.swing.JPanel();
        fieldUsser = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        bttLogin = new javax.swing.JLabel();
        bttConf = new javax.swing.JLabel();
        bttClient = new javax.swing.JLabel();
        bttRep = new javax.swing.JLabel();
        bttExit = new javax.swing.JLabel();
        bttFact = new javax.swing.JLabel();
        bttInv = new javax.swing.JLabel();
        bkgBase = new javax.swing.JLabel();
        lbCompanyName = new javax.swing.JLabel();
        bkgImage = new javax.swing.JLabel();
        bkColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/logOutImg.jpg"))); // NOI18N
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(625, 40, 131, 135);

        panActiveUsser.setBackground(new java.awt.Color(236, 233, 233));
        panActiveUsser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labActiveName.setFont(new java.awt.Font("Monotype Corsiva", 1, 20)); // NOI18N
        labActiveName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labActiveName.setText("Nombre activo");
        panActiveUsser.add(labActiveName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        bttLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttLogout.png"))); // NOI18N
        bttLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttLogoutMouseClicked(evt);
            }
        });
        panActiveUsser.add(bttLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLayeredPane1.add(panActiveUsser);
        panActiveUsser.setBounds(420, 20, 190, 150);

        panLoggedoutUsser.setOpaque(false);
        panLoggedoutUsser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panLoggedoutUsser.add(fieldUsser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));
        panLoggedoutUsser.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 30));

        bttLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/loginBtt.png"))); // NOI18N
        bttLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttLoginMouseClicked(evt);
            }
        });
        panLoggedoutUsser.add(bttLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLayeredPane1.add(panLoggedoutUsser);
        panLoggedoutUsser.setBounds(600, 180, 190, 150);

        bttConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttConfUnt.png"))); // NOI18N
        bttConf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttConf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttConfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttConfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttConfMouseExited(evt);
            }
        });
        jLayeredPane1.add(bttConf);
        bttConf.setBounds(746, 366, 42, 56);

        bttClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttClientes.png"))); // NOI18N
        bttClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttClientMouseClicked(evt);
            }
        });
        jLayeredPane1.add(bttClient);
        bttClient.setBounds(198, 362, 150, 124);

        bttRep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttReportes.png"))); // NOI18N
        bttRep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttRepMouseClicked(evt);
            }
        });
        jLayeredPane1.add(bttRep);
        bttRep.setBounds(572, 362, 150, 124);

        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttExitUnt.png"))); // NOI18N
        bttExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttExitMouseExited(evt);
            }
        });
        jLayeredPane1.add(bttExit);
        bttExit.setBounds(746, 434, 41, 53);

        bttFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttFact.png"))); // NOI18N
        bttFact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttFactMouseClicked(evt);
            }
        });
        jLayeredPane1.add(bttFact);
        bttFact.setBounds(11, 362, 150, 124);

        bttInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttInventario.png"))); // NOI18N
        bttInv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttInv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttInvMouseClicked(evt);
            }
        });
        jLayeredPane1.add(bttInv);
        bttInv.setBounds(385, 362, 150, 124);

        bkgBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/panelInicio.png"))); // NOI18N
        jLayeredPane1.add(bkgBase);
        bkgBase.setBounds(0, 0, 800, 500);

        lbCompanyName.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lbCompanyName.setText("NOMBRE DE LA EMPRESA AQUI");
        lbCompanyName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLayeredPane1.add(lbCompanyName);
        lbCompanyName.setBounds(10, 64, 510, 60);

        bkgImage.setText("ImagenDeFondo");
        jLayeredPane1.add(bkgImage);
        bkgImage.setBounds(0, 24, 620, 320);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 800, 500);

        bkColor.setBackground(new java.awt.Color(153, 153, 153));
        bkColor.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        bkColor.setMinimumSize(new java.awt.Dimension(800, 500));
        bkColor.setOpaque(true);
        bkColor.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(bkColor);
        bkColor.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean valUsser(boolean pNeedAdmin){
        if (!_logged){
            JOptionPane.showMessageDialog(
                    jLayeredPane1, 
                    "Debes iniciar sesión antes de continuar", 
                    "¡Atención!", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (pNeedAdmin && isAdmin()){
            JOptionPane.showMessageDialog(
                    jLayeredPane1, 
                    "Necesitas permisos de administrador para poder continuar", 
                    "¡Error!", 
                    JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            return true;
        }
    }
    
    /**
     * 
     * @return 
     */
    private boolean isAdmin(){
        return false;
    }
    
    private void bttExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_bttExitMouseClicked

    private void bttFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttFactMouseClicked
        if (valUsser(false)){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JF_Facturacion("Joseph Loaiza", "Jefe").setVisible(true);
                }
            });
            this.setEnabled(false);
        }
    }//GEN-LAST:event_bttFactMouseClicked

    private void bttExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExitMouseEntered
        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttExitTch.png")));
    }//GEN-LAST:event_bttExitMouseEntered

    private void bttExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExitMouseExited
        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttExitUnt.png")));
    }//GEN-LAST:event_bttExitMouseExited

    private void bttInvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttInvMouseClicked
        if (valUsser(true)){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JF_Inventario().setVisible(true);
                }
            });
            this.setEnabled(false);
        }
    }//GEN-LAST:event_bttInvMouseClicked

    private void bttLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttLoginMouseClicked
        String usser = fieldUsser.getText();
        String pass = new String(fieldPassword.getPassword());
        
        if (usser.isEmpty()){
            JOptionPane.showMessageDialog(
                    jLayeredPane1, 
                    "Por favor digite su usuario", 
                    "¡Atención!", 
                    JOptionPane.WARNING_MESSAGE);
        } else if (pass.isEmpty()){
            JOptionPane.showMessageDialog(
                    jLayeredPane1, 
                    "Por favor digite su contraseña", 
                    "¡Atención!", 
                    JOptionPane.WARNING_MESSAGE);
        } else {
            
            Direct_Control_BD base = db_managment.Direct_Control_BD.getInstance();
            int authentique = base.verificarUsuario(usser, pass);
            if (authentique == 0){
                JOptionPane.showMessageDialog(
                    jLayeredPane1, 
                    "No se ha podido ingresar. Por favor revise su usuario y contraseña", 
                    "¡Error!", 
                    JOptionPane.ERROR_MESSAGE);
            } else{
                _logged = true;
                JOptionPane.showMessageDialog(
                    jLayeredPane1, 
                    "Bienvenido "+usser, 
                    "¡Hola!", 
                    JOptionPane.INFORMATION_MESSAGE);
                XMLConfiguracion xml = ManejoDeArchivos.XMLConfiguracion.getInstance();
                xml.establecerUsuario(usser);
                activeLoginPanel(LOGGED_IN);
                labActiveName.setText(usser);
                if (authentique == 1){
                    // ES ADMIN
                } else {
                    //ES VENDEDOR
                }
                
                fieldUsser.setText("");
                fieldPassword.setText("");
                
            }
        }
        
        
    }//GEN-LAST:event_bttLoginMouseClicked

    private void bttRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttRepMouseClicked
        if (valUsser(true)){
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new JF_Reportes().setVisible(true);
                }
            });
            this.setEnabled(false);
        }
    }//GEN-LAST:event_bttRepMouseClicked

    private void bttClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttClientMouseClicked
        if (valUsser(true)){
            
        }
    }//GEN-LAST:event_bttClientMouseClicked

    private void bttConfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttConfMouseEntered
        bttConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttConfTch.png")));
    }//GEN-LAST:event_bttConfMouseEntered

    private void bttConfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttConfMouseExited
        bttConf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttConfUnt.png")));
    }//GEN-LAST:event_bttConfMouseExited

    private void bttLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttLogoutMouseClicked
        ManejoDeArchivos.XMLConfiguracion.getInstance().establecerUsuario("");
        _logged = false;
        
        panActiveUsser.setVisible(false);
        panActiveUsser.setEnabled(false);
        
        panLoggedoutUsser.setEnabled(true);
        panLoggedoutUsser.setVisible(true);
    }//GEN-LAST:event_bttLogoutMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ManejoDeArchivos.XMLConfiguracion.getInstance().establecerUsuario("");
    }//GEN-LAST:event_formWindowClosing

    private void bttConfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttConfMouseClicked
        if (valUsser(true)){
            
        }
    }//GEN-LAST:event_bttConfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkColor;
    private javax.swing.JLabel bkgBase;
    private javax.swing.JLabel bkgImage;
    private javax.swing.JLabel bttClient;
    private javax.swing.JLabel bttConf;
    private javax.swing.JLabel bttExit;
    private javax.swing.JLabel bttFact;
    private javax.swing.JLabel bttInv;
    private javax.swing.JLabel bttLogin;
    private javax.swing.JLabel bttLogout;
    private javax.swing.JLabel bttRep;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel labActiveName;
    private javax.swing.JLabel lbCompanyName;
    private javax.swing.JPanel panActiveUsser;
    private javax.swing.JPanel panLoggedoutUsser;
    // End of variables declaration//GEN-END:variables
}
