/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package joe;

import java.awt.Toolkit;
import java.awt.Dimension;

/**
 *
 * @author Joseph
 */
public class StartWindow extends javax.swing.JFrame {

    private static StartWindow _instance = null;
    
    /**
     * Creates new form StartWindow
     */
    public StartWindow() {
        _instance = this;
        
        initComponents();
        
        //Esto hay que quitarlo:
        bkgImage.setText("");
        bkgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/url.jpg")));
        
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        this.setSize(screenSize);
        this.setLocation(0, 0);
        bkColor.setSize(screenSize);
        
        jLayeredPane1.setLocation(
                this.getWidth()/2-jLayeredPane1.getWidth()/2, 
                this.getHeight()/2-jLayeredPane1.getHeight()/2);
        
    }

    public void enableMe(){
        this.setEnabled(true);
    }
    
    public static StartWindow getInstance(){
        return _instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        bttExit = new javax.swing.JLabel();
        bttFact = new javax.swing.JLabel();
        bkgBase = new javax.swing.JLabel();
        lbCompanyName = new javax.swing.JLabel();
        bkgImage = new javax.swing.JLabel();
        bkColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttExitUnt.png"))); // NOI18N
        bttExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bttExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bttExitMouseExited(evt);
            }
        });
        jLayeredPane1.add(bttExit);
        bttExit.setBounds(746, 434, 41, 53);

        bttFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttFact.png"))); // NOI18N
        bttFact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttFactMouseClicked(evt);
            }
        });
        jLayeredPane1.add(bttFact);
        bttFact.setBounds(11, 362, 150, 124);

        bkgBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/panelInicio.png"))); // NOI18N
        jLayeredPane1.add(bkgBase);
        bkgBase.setBounds(0, 0, 800, 500);

        lbCompanyName.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lbCompanyName.setText("NOMBRE DE LA EMPRESA AQUI");
        lbCompanyName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLayeredPane1.add(lbCompanyName);
        lbCompanyName.setBounds(10, 64, 510, 60);

        bkgImage.setText("ImagenDeFondo");
        jLayeredPane1.add(bkgImage);
        bkgImage.setBounds(0, 24, 620, 320);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 800, 500);

        bkColor.setBackground(new java.awt.Color(153, 153, 153));
        bkColor.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        bkColor.setMinimumSize(new java.awt.Dimension(800, 500));
        bkColor.setOpaque(true);
        bkColor.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(bkColor);
        bkColor.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_bttExitMouseClicked

    private void bttFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttFactMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Facturacion("Joseph Loaiza", "Jefe").setVisible(true);
            }
        });
        this.setEnabled(false);
    }//GEN-LAST:event_bttFactMouseClicked

    private void bttExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExitMouseEntered
        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttExitTch.png")));
    }//GEN-LAST:event_bttExitMouseEntered

    private void bttExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttExitMouseExited
        bttExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/System/Images/PanelInicio/bttExitUnt.png")));
    }//GEN-LAST:event_bttExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bkColor;
    private javax.swing.JLabel bkgBase;
    private javax.swing.JLabel bkgImage;
    private javax.swing.JLabel bttExit;
    private javax.swing.JLabel bttFact;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbCompanyName;
    // End of variables declaration//GEN-END:variables
}
